### PR TITLE
Switch to final config loader

### PR DESCRIPTION
**Pull request by SpenserJ**
Now that we've run with the `config.loader.js` for a few days, everyone's config.js file should be located in `configs/custom.js`, alongside with multiple environment configs. It should now be safe for us to switch over to `config.js` as our primary config loader, instead of having two identical files to ensure everything is merged properly.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 ac7280b3de1d8d80af46277bfcb44f7ebfbb25e4

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by plor** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=5nk"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (100%)
:-1:: 0 (0%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
