### PR TITLE
allow people to vote with hearts.

### PR DESCRIPTION
**Pull request by JWesorick**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 1a9b4153957b3e83affd0a48948d835336f013ac

**Comment by thmas** [comment]
:+1: :heart:

**Comment by rntz** [comment]
:-1: like the idea, but the regex is too permissive

**Comment by satyarth** [comment]
:-1:

**Comment by OLef1air** [comment]
:-1:

**Comment by jvt** [comment]
:-1:

**Comment by rickardnorlander** [comment]
:-1:

**Comment by hyperhtml** [comment]
:-1:

**Comment by rdancer** [comment]
:-1:  Why is this necessary? :broken_heart:

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Pull request closed without merging**
