### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rdancer**
Explain better how to make a comment on the PR a voting one, and encourage commenters to leave an explanation, not just the vote.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* a7ff0a329bc8df6d15642d025dd25e6f9f988ba1

**Comment by OLef1air** [comment]
:+1: :+1: :+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by mappum** [comment]
:+1: Maybe it's a bit verbose, but it's good to communicate that information

**Comment by erasmospunk** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
