### PR TITLE
Enable some sort of module like mod_rpaf for Apache

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Enable some sort of module like [mod_rpaf](https://github.com/gnif/mod_rpaf) for Apache which allows up to see the actual IP from the Ngnix server instead of returning :ffff:127.0.0.1: or 127.0.0.1 or anything along those lines

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 fa43e908177ccebd8adfbfb4da8a4b05e5f10f4a

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by SpenserJ** [comment]
Its already passed through as a header. You can get the real IP

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 fa43e908177ccebd8adfbfb4da8a4b05e5f10f4a

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
@SpenserJ: Add the header to the stdout log please

**Comment by SpenserJ** [comment]
https://github.com/botwillacceptanything/botwillacceptanything/blob/master/configs/nginx/nginx.conf#L16

Feel free to add it yourself. Its the standard X-Forward-For header, which should work pretty well with [Morgan](https://github.com/expressjs/morgan), the module that handles logging for the webserver.

**Comment by SpenserJ** [comment]
@AlphaT3ch Express has support for X-Forward-For built in. They tell you how to set it up in http://expressjs.com/guide/behind-proxies.html

**Comment by dbpokorny** [comment]
@AlphaT3ch , you said: "@SpenserJ: Add the header to the stdout log please"

My remarks in this note are in the context of the your interaction with the project. Think before you type.

:-1: Anyone can submit a PR that temporarily makes @AlphaT3ch's PRs (and only those PRs) require a 68% margin instead of a 67% margin (temporarily, for the next 10 hours, so no effect if you don't submit any PRs in the next 10 hours). I'll leave it up to @SpenserJ whether he thinks such a move would be prudent at this point in time. Or maybe he would go further and suggest a change that goes beyond mere symbolism, say 76% margin for 30 hours.

Alternatively, we could temporarily diminish the power of your vote, say a 97% effective vote for the next 15 hours. Or some of both. None of this is in the code, but it could be added. It would take time, code review, the community would have to approve, &c.

As an alternative to disciplinary measures, the BWAA project could implement a real names policy.

My point is: @AlphaT3ch, kick it up a notch.

**Comment by SpenserJ** [comment]
@dbpokorny I appreciate the support on this, but I don't know if anything would be worth implementing. I would assume @AlphaT3ch will implement this change, since it is a one-liner. I don't think anything should be asked of anyone, as this is a community project where we can all make the changes we want to see. If there is ever confusion, or someone needs help, we're always willing in IRC, but there are times where people do need to step up to the plate and give it a shot themselves first.

@AlphaT3ch, I look forward to seeing your PR for this.

**Comment by KyleDavidE** [comment]
:-1: 162.243.149.229

**Comment by OLef1air** [comment]
:-1:

**Comment by OLef1air** [comment]
This has been done, #474

**Comment by dbpokorny** [comment]
"I don't think anything should be asked of anyone, as this is a community project where we can all make the changes we want to see."

As individuals? Or as a team? http://www.dailymotion.com/video/x12tlt5_winter-wrap-up-mlp-fim-s1-e11_tech

**Comment by plor** [comment]
:-1:

**Pull request closed without merging**
