### PR TITLE
[Retry] Make some space for actual projects, now with fixed typo.

### PR DESCRIPTION
**Pull request by vespakoen**
Same as last one, typo now fixed.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 5fafd7b3040b2ad4e7448426c7ecbb8f24600d34

**Comment by vespakoen** [comment]
:+1:

**Comment by RaitoBezarius** [comment]
:+1:

**Comment by lambtron** [comment]
:+1:

**Comment by clay-to-n** [comment]
:+1:

**Comment by ajbouh** [comment]
:+1:

**Comment by dhruska** [comment]
:+1:

**Comment by geoffnix** [comment]
:+1:

**Comment by christianbundy** [comment]
:+1:

**Comment by runvnc** [comment]
:+1:

**Comment by generalhenry** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
