### PR TITLE
Strip whitespace from the end of the lines, also add another badge

### PR DESCRIPTION
**Pull request by shalecraig**
Please see above now we have more badges :)

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* b8e925445090d5abc6adccd6c1e4716032000f4d

**Comment by SpenserJ** [comment]
Still against badges for the sake of badges :-1:

**Comment by korczis** [comment]
:-1:

**Comment by dos1** [comment]
this badge is a very nice commentary about the use of badges :+1:

**Comment by Prior99** [comment]
:+1:

**Comment by pandzieciol** [comment]
:+1:

**Comment by skrzyp** [comment]
:+1:

**Comment by hun7err** [comment]
:+1:

**Comment by dos1** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=6gs"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

These users aren't stargazers, so their votes were not counted: 
 * @botwillacceptanything

**Comment by bigsergey** [comment]
:+1:

**Pull request merged**
