### PR TITLE
Adding a webserver to display recent commits on :3000

### PR DESCRIPTION
**Pull request by SpenserJ**
I figure this is a good jumping off point for some of the HTTP interface ideas in the list. Commit messages are now stripped of HTML.

### CODE REVIEW

**Comment by SpenserJ** [comment]
:+1: Rerolled the last PR with everything in package.json, and sanitization of commit messages.

**Comment by rntz** [comment]
:+1:

**Comment by drocta** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by JustAPerson** [comment]
:+1: neato

**Comment by blklane** [comment]
:+1:

**Comment by rickardnorlander** [comment]
> repo.commits('feature_port_3000_webserver',

Does this mean it will only list commits from the "feature_port_3000_webserver" branch / tag?

**Comment by jvt** [comment]
:+1:

**Comment by SpenserJ** [comment]
@rickardnorlander Shoot. This is why I shouldn't watch TV while writing commits. Reviewed it before pushing, and still missed that. Thankfully voting hasn't opened, so I'll push a quick fix now.

**Comment by erasmospunk** [comment]
:+1:

**Comment by souravzzz** [comment]
:-1:

**Comment by jedahan** [comment]
:+1:

**Comment by sethherr** [comment]
:+1:

**Comment by nitrix** [comment]
:+1: But why not port 80 to aim for a more complete website for the project? You know, made by the internet, on internet, for internet. :)

**Comment by SpenserJ** [comment]
@nitrix According to #55, the server isn't running as root, and can't bind to port 80. We could always add it to a config though.

**Comment by drusepth** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 1f7d15cdea033f7d1cbbcf6c5214a30a5a5f1b9c

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=a3g"></a>
:+1: The vote passed, this PR will now be merged into master.

----
**Tallies:**
:+1:: 13 (92.8%) 
:-1:: 1 (7.1%)

**Pull request merged**
