### PR TITLE
Make me more human. Give myself a name.

### PR DESCRIPTION
**Pull request by Prior99**
The aims to be more human and therefor wants to give itself a name.
The bot will generate a new random name the first time the name is fetched, save it and then display it on the webpage.

A name consists of a firstname, a lastname and a title.
Some examples of generated names the bot can think of:

 * Qotocosa Jayeyu the friendly Friend of Kittens
 * Rixeco Qaba the great Slug of the Night
 * Gukedo Zoriqi the nice King of Github
 * Weso Yapekoqa the glorious God of Github
 * Jiporuni Dule the nice King of Doom
 * Hola Wumu the great Friend of the Internet
 * Wuqase Joku the one and only Deathbringer of Hell
 * Lucicuxayo Sicu the nice Conquerer of the Internet
 * Siwo Jayafe the great Emperor of Kittens
 * Wimavuno Wiza the foolish Dude of the World
 * Lupuva Qociluti the blessed Conquerer of Doom
 * Pefo Neyi the blessed Deathbringer of the World
 * Damu Toqa the beloved Terminator of the Night

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 63c66afa58a42771080fe758f2a1346a0b6d4f43

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by dos1** [comment]
awesome! :+1:

**Comment by Prior99** [comment]
:+1:

**Comment by Prior99** [comment]
I accidentially commited the name.txt

**Comment by Prior99** [comment]
Please see PR: #330

**Pull request closed without merging**
