### PR TITLE
Update voting.js

### PR DESCRIPTION
**Pull request by blister**
Add missing period to warning message.

### CODE REVIEW

**Comment by blister** [comment]
:+1:

**Comment by fiveminuteargument** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 74baa679ba5ee3ec8cd3c642c6b0bfeda1b503a4

**Comment by Simon-Coetzee** [comment]
:+1:

**Comment by wsterzik** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by haani** [comment]
:+1:

**Comment by geoffnin** [comment]
:+1:

**Comment by clay-to-n** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by karolba** [comment]
:+1:

**Comment by jrgifford** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by johnku1** [comment]
:+1:

**Comment by frederickfogerty** [comment]
:+1:

**Comment by voxtex** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
