### PR TITLE
Folder structure - folder for data/src + travis CI + badge

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by dos1** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 19b38f6db5ad24d8297c1f423c8ee1a9006a7ca8

**Comment by SpenserJ** [comment]
Curious how this will work if it gets merged before the webhook branch. :+1: Either way!

**Comment by AlphaT3ch** [comment]
:+1: and how will this get merged?

**Comment by korczis** [comment]
@SpenserJ  I think it should work fine as I merged all your changes into my branch

**Comment by korczis** [comment]
Time to stretch the system to its limits

**Comment by dos1** [comment]
@SpenserJ: shouldn't be an issue; however, if webhook PR gets rejected, voting for this one effectively means voting for both of these PRs

**Comment by SpenserJ** [comment]
@korczis @dos1 I more mean what happens if this gets merged before webhooks, because at that point there is nothing in webhooks to merge. Not a problem, just an interesting chicken vs egg issue for the bot to figure out.

**Comment by dos1** [comment]
@SpenserJ : then merging webhooks PR won't change anything. It should still work fine though

**Comment by korczis** [comment]
@SpenserJ I got it now. Maybe some "dummy" commit (?)

**Comment by korczis** [comment]
So one more time ..

**Pull request closed without merging**
