### PR TITLE
BWAA Media RC2

### PR DESCRIPTION
**Pull request by dbpokorny**
Use UTC instead of local time so media is globally synced

Most of the media here is entertainment-related. The media sync capability means that the entire BWAA team can "take classes" at the same time and discuss the material presented. Alternatively, a specialized bot (teaching tool) could be engineered to only accept commits targeted at the "current project". In this way, interaction with the bot would become a matter of the team members progressively overcoming harder engineering obstacles. Upon satisfaction of the victory condition, the bot would move onto the next challenge and present instruction with text, audio, and/or video informing the team of the parameters of the next challenge. Asking team members to collaborate in public on github makes it easier for senior developers to spot groups that are having problems (technical and personal).

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* d3f1a1391ae061f6b11b36211850bed796326a7e

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by dos1** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by korczis** [comment]
:-1: what is this good for? run your own WP

**Comment by pandzieciol** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Comment by dbpokorny** [comment]
oh dear, the bots are going haywire this is a huge mess

**Comment by korczis** [comment]
@dbpokorny Maybe you can help with fixing this :)

**Comment by dbpokorny** [comment]
In case anyone is wondering what happened, I checked out Prior99's bot and copied my configs in without thinking about it, so the bot did what it thought was the right thing and started scribbling over dbpokorny/botwillacceptanything. Removing my github auth from the configs should fix this.

**Pull request closed without merging**
