### PR TITLE
votingConfig -> votingParams

### PR DESCRIPTION
**Pull request by dbpokorny**
This PR removes anything voting-related from the configs and adds voting parameters to params.js.

Configs = how to get the bot to run on your computer
Params = the reflection of the will of the botwillacceptanything community

Allow me to quote from config.js

  // If configs/custom.js doesn't exist right now, copy the template.
  if (fs.existsSync('./configs/custom.js') === false) {
    fse.copySync('./configs/template.js', './configs/custom.js');
  }

This means that configs/custom.js will become stale as soon as configs/template.js changes. This means that any change to configs/template.js will require the sysadmin to delete configs/custom.js and restart the bot for the change to have any effect.

In contrast, the parameters in params.js are not copied. The data is reloaded every time the bot restarts (which happens when the bot accepts a PR). Any changes to params.js in a PR will be reflected as soon as the bot restarts.

### CODE REVIEW

**Comment by SpenserJ** [comment]
I'm not sure you're catching what `config.js` does when it loads the config. Check out [Line #36](https://github.com/botwillacceptanything/botwillacceptanything/blob/master/config.js#L36), which will merge the custom config on top of the template. The only time you would need to "delete" (or more likely, modify) `configs/custom.js` is when you want one of the new features enabled, otherwise template will just provide a default value.

:-1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 328d4503a114b4522bbe65653037f2ae83dc7ea3

**Comment by dbpokorny** [comment]
@SpenserJ why are you fighting this? Please tell me the rationale for having voting parameters in the configs. They seem totally unrelated to me. Business logic does not go in configs. Voting is business logic.

**Comment by SpenserJ** [comment]
@dbpokorny Your `params.js` file is tracked by git. What happens when I'm developing, and I want to test with a `minVotes` of 2? I'll have to edit a file that is tracked by git, at which point I may accidentally commit my change for testing.

The reason it loads the config template is so that we can provide defaults, and the reason it merges `configs/custom.js` over top is so that it can be changed in a gitignored file. It copies the template on the first run so that it is obvious which file a user should edit.

**Comment by dbpokorny** [comment]
@SpenserJ this is a conflict of interest for the sysadmin. I've submitted a PR that moves the sysadmin one step away from the voting. I'm getting resistance from the sysadmin. This is what this feels like:

"LOTR The Fellowship of the Ring - Farewell Dear Bilbo" https://www.youtube.com/watch?v=4Yy0pPTrHlk

**Comment by SpenserJ** [comment]
@dbpokorny I think moving the sysadmin away from the voting is reasonable, however making it impossible for the sysadmin to control voting configuration blocks the bot from being used outside of its own network (speaking to the distributed concept that has been discussed in IRC). I can see this being used for random projects that need voting functionality, and not just as a botnet where everything is hardcoded.

**Comment by avdg** [comment]
:-1: for not running `npm test` ;-)

**Comment by dbpokorny** [comment]
oh so that's how you test. Thanks avdg.

We could just extract the voting code and put it in a separate repo?

**Comment by dbpokorny** [comment]
If we have voting in a separate repo, then we can configure the bot to send out notifications when any "voting PR" (PR against the voting repo) is accepted. What kind of reception do you think "the anythingbot is now accepting PRs 3/5" would get? By "3/5" I mean "5 min votes and 3 to pass". By "notification" I mean email.

**Pull request closed without merging**
