### PR TITLE
Updated voteStartedComment text

### PR DESCRIPTION
**Pull request by mappum**
Some of the text was out of date, or formatted badly.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 5c4c065d4e3f014eb670f935812e641dd66b4f8a

**Comment by OliverCole** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by satyarth** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by jvt** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7c1"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (100%) 
:-1:: 0 (0%)

**Pull request merged**
