### PR TITLE
Fix the "under construction" sign

### PR DESCRIPTION
**Pull request by dos1**
YOU DIDN'T EVEN TEST THE CHANGE BEFORE VOTING ON IT DID YOU? :>

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* dc2be845a5eb2f2531d9a12a8bbce11fd98511be

**Comment by SpenserJ** [comment]
:+1:

**Comment by jedahan** [comment]
:+1:

**Comment by matter123** [comment]
:+1:

**Comment by databyte** [comment]
:+1:

**Comment by dazoe** [comment]
A scrolling under construction message?! I this GeoCities?
Well even though I don't like it, it does need to be fixed...
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1: Nice catch

**Comment by korczis** [comment]
You did not tested this before PR?

**Comment by korczis** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=bog"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @databyte

**Pull request merged**
