### PR TITLE
Make some space for actual projects

### PR DESCRIPTION
**Pull request by vespakoen**
Hacking the bot alone is no fun...

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 80744f9db2d02761641b18f19b9c02e1aeba0825

**Comment by vespakoen** [comment]
:+1:

**Comment by jamescostian** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by nsporillo** [comment]
:+1:

**Comment by erasmospunk** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Comment by vespakoen** [comment]
Nice! din't know that, making a new pull

**Pull request closed without merging**
