### PR TITLE
First draft of contributor guide

### PR DESCRIPTION
**Pull request by bradleybuda**
Add some tips for configuring the bot to run locally

### CODE REVIEW

**Comment by OLef1air** [comment]
:+1:

**Comment by mszaro** [comment]
:+1:

**Comment by bpeters** [comment]
:+1:

**Comment by fiveminuteargument** [comment]
:+1:

**Comment by ClintLiddick** [comment]
:+1:

**Comment by cwar** [comment]
:+1:

**Comment by JWesorick** [comment]
:+1: Also how about some faqs? Mine keeps asking for my username and password even though its in the config.

**Comment by jordanmueller** [comment]
:+1:

**Comment by JWesorick** [comment]
:+1:

**Comment by Xandaros** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Comment by rdancer** [comment]
:+1:

**Pull request merged**
