### PR TITLE
Added IRC notifications

### PR DESCRIPTION
**Pull request by mappum**
Leaves messages in IRC when PRs are opened and when voting closes.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 1639d134813ae251cd8e68b99898c98308f8092e

**Comment by dos1** [comment]
:+1:

**Comment by korczis** [comment]
:+1:

**Comment by dos1** [comment]
Taking that back, you've commited a change that removes time and vote limits! :-1:

**Comment by samis** [comment]
:+1:

**Comment by mappum** [comment]
@dos1 Whoops, good catch!

**Pull request closed without merging**
