### PR TITLE
New construction sign on website

### PR DESCRIPTION
**Pull request by AlphaT3ch**
The old construction site had a bad background and needed to load an external png image. This one has a transparent background and is loaded with a nice data uri to not need to load external png images.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* c8fa89aab587b957d04d76a34993dd5fff0d47c5

**Comment by SpenserJ** [comment]
I'm not sure if this is a worthwhile change. It has increased the size of `data/views/layouts/main.hbs` to 82KB, which has to be processed when rendering any page. A base64 image cannot be cached by the browser, which means this is serving ~82KB worth of content on every page load, instead of the ~4KB that it was before. :-1:

**Comment by dbpokorny** [comment]
:-1:

**Comment by plor** [comment]
:-1:

**Comment by avdg** [comment]
:-1: Separate image serving was still better.

Generated pages are not cached, while the image could be. Note the 304 returns if you are able to use the web tools.

**Comment by RyanMilb** [comment]
:-1:

**Comment by dos1** [comment]
why the hell is this in data url? :-1:

**Comment by shalecraig** [comment]
Just like the #305 -> #310 transition, please close & fix.

:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 1 (12.5%) 
:-1:: 7 (87.5%)

**Pull request closed without merging**
