### PR TITLE
Change license to WTFPL v2

### PR DESCRIPTION
**Pull request by mplewis**
Much more permissive software license. Provides the bot with more freedom.

Support bot rights!

### CODE REVIEW

**Comment by OLef1air** [comment]
:-1:

**Comment by karolba** [comment]
:-1: , original was more funny.

**Comment by fiveminuteargument** [comment]
:-1:

**Comment by jish** [comment]
:-1:

**Comment by bradleybuda** [comment]
:-1:

**Comment by mszaro** [comment]
:-1:

**Comment by awilliamson** [comment]
:-1:

**Comment by rdancer** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

**Pull request closed without merging**
