### PR TITLE
Idea - Self testing

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by awilliamson** [comment]
:-1: Anarchy

**Comment by rntz** [comment]
:+1:

**Comment by AgentME** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by hintss** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 5236508a8f2b2284edc0da9783911aed7f91139a

**Comment by JWesorick** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by erasmospunk** [comment]
:+1:

**Comment by drocta** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
