### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Updated README.md to include the environment that the bot is running in and a link to the IRC chatroom.

### CODE REVIEW

**Comment by roby65** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballotbox: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* fa704f08644eb9ee9745a4498d6c7e82289155ed

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by HenrySipp** [comment]
:+1:

**Comment by magnusstubman** [comment]
:+1:

**Comment by r04r** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by rdancer** [comment]
:+1:  It would be nice if the `irc` scheme URI was standardized the same as `http` or `mailto` is

**Comment by AlphaT3ch** [comment]
@rdancer It actually is! You just need to have an IRC client installed which some people might not have and they'd get confused... Just linking it to a web client should be easy for everyone.

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=dq0"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (100%) 
:-1:: 0 (0%)

**Pull request merged**
