### PR TITLE
Add a clock to the votes page

### PR DESCRIPTION
**Pull request by dbpokorny**

### CODE REVIEW

**Comment by dbpokorny** [comment]
Demo: http://anythingbot.org:3000/votes

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 fd72548e27d84832a993d4613b7b60bc0490ed64

**Comment by SpenserJ** [comment]
Neither of the times shown are correct for me. It isn't taking my timezone into account

**Comment by dbpokorny** [comment]
Local time is bot's local time, not your local time. Right now http://anythingbot.org:3000/votes is showing UTC=6:34pm, which is what I get when I google "utc time", so it is working for me. I don't know why UTC time would be wrong for you...?

**Comment by dbpokorny** [comment]
laptop in california: 12:38 Pacific Time

45.33.74.211 is a machine in Newark, NJ set to EDT, which is correct for the
physical location of the device

45.33.74.211:3000/votes
    Local time: Sun Apr 26 2015 15:37:27 GMT-0400 (EDT) (+56247)
    UTC time: Sun Apr 26 2015 19:37:27 GMT-0400 (EDT) (+70647)

anythingbot.org is a machine in Fremont, CA set to UTC, which is incorrect for the
physical location of the device

http://anythingbot.org:3000/votes
    Local time: Sun Apr 26 2015 19:40:16 GMT+0000 (UTC) (+70816)
    UTC time: Sun Apr 26 2015 19:40:16 GMT+0000 (UTC) (+70816)

---

If I correct anythingbot.org's time so that it reflects the physical location of
the device, I get

http://anythingbot.org:3000/votes

    Local time: Sun Apr 26 2015 12:50:47 GMT-0700 (PDT) (+46247)
    UTC time: Sun Apr 26 2015 19:50:47 GMT-0700 (PDT) (+71447)

---

UTC time now (google) is 7:55 PM

**Pull request closed without merging**
