### PR TITLE
Clean up tweets

### PR DESCRIPTION
**Pull request by zztemp**
I removed the tweet for losing pull requests because I think it is too much, and I added the pull request name to the opening tweet.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* bc9c41070a9208ff619c6423e151df0e4b3f2d06

**Comment by CptnBrittish** [comment]
:-1:  I think all information about the evolution of the bot should be showen

**Comment by dos1** [comment]
:+1:

**Comment by samis** [comment]
:-1: It's not like we have a max limit of X tweets.

**Comment by jish** [comment]
:+1:

**Comment by mappum** [comment]
:+1:  I like that, it was spamming my twitter feed.

**Comment by gpersons** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1: Agreed mappum!

**Comment by SpenserJ** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7p5"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (77.7%) 
:-1:: 2 (22.2%)

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Pull request closed without merging**
