### PR TITLE
Require supermajority (65%) for vote to pass

### PR DESCRIPTION
**Pull request by sparky222b**
Ensure future bot quality by requiring a supermajority to edit.

### CODE REVIEW

**Comment by sparky222b** [comment]
:+1:

**Comment by chrismeller** [comment]
:+1:

**Comment by Xandaros** [comment]
:+1:

**Comment by fiveminuteargument** [comment]
:+1:

**Comment by mszaro** [comment]
:+1:

**Comment by jtrivedi** [comment]
:+1:

**Comment by rntz** [comment]
:+1:

**Comment by jgod** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:  Why was there an assignment there before?

**Comment by dos1** [comment]
:-1:

**Comment by TimDaub** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 5e66e1a5292e69558277c27462d6396462cd3e15

**Comment by begizi** [comment]
:+1:

**Comment by mappum** [comment]
:+1: Nice!

**Comment by enjoylife** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Comment by thenightwassave** [comment]
@rickardnorlander That was my mistake when I ripped out the original check from the original function.

**Pull request merged**
