### PR TITLE
Reverse votes

### PR DESCRIPTION
**Pull request by Benaiah**
Make votes do the opposite of what it says they do. Fun.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 14a6a6e2623dbe3a34c82780eafa53d60bc58a06

**Comment by edwardhotchkiss** [comment]
:-1:

**Comment by mappum** [comment]
Lol, nice try :-1:

**Comment by clay-to-n** [comment]
:+1:
Why not?

**Comment by Benaiah** [comment]
Closed because I accidentally included somebody else's PR in mine

**Pull request closed without merging**
