### PR TITLE
ARL draft spec v1

### PR DESCRIPTION
**Pull request by dbpokorny**
The Wikipedia page for Total Request Live http://en.wikipedia.org/wiki/Total_Request_Live explains the basic mechanic. FTA:

"TRL played the ten most requested videos of the day, as requested by viewers who voted online for their favorite video. The countdown started with the tenth most requested video and ended with the most requested. As of October 22, 2007, TRL's countdown was based on votes, charts, ringtones, download, radio airplay, and streams, meaning that the most user requested video might not have been the number 1 video. The show generally aired Monday through Thursday for one hour, though the scheduling and length of the show fluctuated over the years. Despite the word "Live" in the title of the show, many episodes were actually pre-recorded."

For the philosophers...

Github PR: vote for bot programming (aka code)

Reddit ARL: vote for human programming (aka media items)

Anyway, I was thinking that if people want this, we should work it out like this: if you like what you see and you want to work on it, say something like, "I'll take 5.2" or "I'll take websockets" or whatever.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 82a03207c067254aa869446c54fb117fe1766da2

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by RafaelCosman** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=254"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 5 (100%)
:-1:: 0 (0%)

These following 1 voter(s) were not _stargazers_, so their votes were not counted:

- :monkey: @coveralls

*Non-stargazers*: Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
