### PR TITLE
Add and remove auto-labels using promises.

### PR DESCRIPTION
**Pull request by timweightman**
Hi all-

This is a major refactor / re-write to make use of promises for the auto-labelling code. It also breaks out the files into more maintainable and extensible modules.

I modified integrations/index.js to auto-load only top-level "*.js" files, ensuring that it doesn't recurse subdirectories. This will now mean that we can group related modules under folders, keeping just an entry file (i.e. integrations/github.js) at the top level.

I've run through it several times on my local with working webhooks etc, have ironed out any issues I found.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* ec5053a8f8454c79fae7fc76f33ca5e30e873cf8

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: Looks awesome!

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Pull request closed without merging**
