### PR TITLE
Please downvote.

### PR DESCRIPTION
**Pull request by dos1**
Nothing to see here.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 d43b7272103354d81e844039752b93e64fe43133

**Comment by SpenserJ** [comment]
:-1:

**Comment by avdg** [comment]
:monkey:

**Comment by plor** [comment]
:-1:

**Comment by pandzieciol** [comment]
:+1:

**Comment by grantbacon** [comment]
:-1:

**Comment by samis** [comment]
:-1:

**Comment by OLef1air** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.


----
**Tallies:**
:+1:: 2 (28.5%)
:-1:: 5 (71.4%)

These following 1 voter(s) were not _stargazers_, so their votes were not counted:

- :monkey: @coveralls

*Non-stargazers*: Be sure to :star:star the repository if you want to have your say!

**Comment by dbpokorny** [comment]
:-1: we need to make it so more people can downvote these

**Pull request closed without merging**
