### PR TITLE
Add public config file

### PR DESCRIPTION
**Pull request by avdg**
Where we add public secrets with votes!

### Details

This would allow us later to add public data like public passwords from users for authentication and authorization (so it says which users have access to what stuff).

The primary purpose would be for vaults, where we can add users democratically (so we see who has access to what).

They can add public passwords. Then they can mess up with private values where they are allowed with like tokens and other stuff they prefer to hide it from public. And all that, pretty securely as long everyone keeps an eye on this file ;-)

Please take care about this file as it will have super powers :-)

Note: this is part of commits related to #149

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* abfba9f074131621eb1102c9ba15365a5c40b651

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by dbpokorny** [comment]
:-1: I like the idea, but this is just a config file with commented lines

**Comment by avdg** [comment]
Yeah, the big changes made me panic and delay the actual implementation, though its way better now than it was before.

After some thinking I thought it would be nice to merge this stuff later.

**Pull request closed without merging**
