### PR TITLE
Removed annoying length warning

### PR DESCRIPTION
**Pull request by mappum**
I didn't like that change, it spams most PRs.

### CODE REVIEW

**Comment by mappum** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1: YEAH!

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* edf1d7f48e9c5d17231976f7ff9acac365570372

**Comment by SpenserJ** [comment]
:+1: Thank goodness!

**Comment by roby65** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by rdancer** [comment]
:+1: That was a quick one! :-)

**Comment by mappum** [comment]
Untested D:

**Comment by SpenserJ** [comment]
Shameful! Better hope it all works!

**Comment by satyarth** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=6v1"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7np"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Pull request closed without merging**
