### PR TITLE
Lower majority

### PR DESCRIPTION
**Pull request by drsirmrpresidentfathercharles**
Lower the majority amount to a lower, fairer, 51%.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 1b85d35ed6250c0a801d60dce7bae886ba19c0c1

**Comment by dos1** [comment]
:+1:

**Comment by drsirmrpresidentfathercharles** [comment]
:+1:

**Comment by mappum** [comment]
Why is that fairer? It's better to err on the side of rejecting a repo IMO. :-1:

**Comment by SpenserJ** [comment]
:-1: If its so evenly split, the PR could probably use some refinement.

**Comment by VeoPVM** [comment]
:+1:

**Comment by zztemp** [comment]
:-1: I think it is better for the ratio to be high, maybe even higher than it is now.

**Comment by korczis** [comment]
:+1:

**Comment by avdg** [comment]
I guess it all depends on how much risk our admins can handle...

**Comment by avdg** [comment]
:-1: for now

**Comment by mappum** [comment]
@avdg I want this to be able to run without any admins. For that, we'll need high supermajorities. (But not so high that people can DoS PRs by downvoting).

**Comment by avdg** [comment]
@mappum I guess 65% could be fair because if pr fails, it can be submitted again. That vs a 45% win that has a 'permanent' effect.

I'll remove my vote for now...

**Comment by zztemp** [comment]
:-1:

**Comment by Stary2001** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 4 (50%) 
:-1:: 4 (50%)

These users aren't stargazers, so their votes were not counted: 
 * @Stary2001

**Pull request closed without merging**
