### PR TITLE
Removed Ponies and Pinkness

### PR DESCRIPTION
**Pull request by OLef1air**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 9925dbde93746fa41092dcaf46cc4c8dfccef3c0

**Comment by OLef1air** [comment]
:+1:

**Comment by RyanCopley** [comment]
:-1:

> :monkey: @RyanCopley, we can't count your vote because you must :star:star the repository.
> If you want your vote to count
> - :star:star the repository
> - Wait for **3** minute(s)
> - Remove this message (including the :monkey:`:monkey:`), or post a new vote.

**Comment by samis** [comment]
:-1: No need to remove the entirely. Making them an optional style / website theme / thing would be a good idea. After all, I find the ponies / pinkness add some 'flavor' to the website.

**Comment by RyanCopley** [comment]
:-1:

**Comment by Dieyousay** [comment]
:-1: It doesn't need less ponies, it needs more.

**Comment by dbpokorny** [comment]
:-1:

**Comment by SpenserJ** [comment]
:+1: I like the idea of cleaning up the interface. I agree that having them as optional would be nice, but I'd rather add them in again later.

**Comment by dequis** [comment]
:+1:

**Comment by Stary2001** [comment]
:-1:

**Comment by soccermitchy** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by OLef1air** [comment]
There have been 10 votes and 4 hours since voting began why hasn't this been rejected?

**Comment by thenightwassave** [comment]
10 votes but its 50% both ways. Required 65%.

**Comment by OLef1air** [comment]
Thanks

**Comment by avdg** [comment]
This code has changed: https://github.com/botwillacceptanything/botwillacceptanything/commit/cfb45988c773dc27f977e7808d7dcb5d372fb0fc#diff-0808401482a44ccb945b82f8b6148385L383

Meaning the bot will only react when there is a majority

**Comment by vifino** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 5 (45.4%) 
:-1:: 6 (54.5%)

These users aren't stargazers, so their votes were not counted: 
 * @coveralls

**Pull request closed without merging**
