### PR TITLE
Bootstrap Style

### PR DESCRIPTION
**Pull request by Prior99**
The page currently looks '95-style so I added bootstrap and a few fixes for our page to make it look decent even on mobile devices.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* f10f314fff3f1295a7543c2b7679d8e23477d06a

**Comment by Prior99** [comment]
:+1:

**Comment by Moerrrlin** [comment]
:+1:

**Comment by hiliev** [comment]
:+1:

**Comment by shalecraig** [comment]
:-1: please use a cdn for bootstrap.

http://www.bootstrapcdn.com/

**Comment by PurHur** [comment]
:+1: CDNs are the root of all mitm attacks so. NÄH

**Comment by Prior99** [comment]
@shalecraig I agree with purhur but if this is general consensus I will patch it to use cdn instead of locally hosted libraries (by the way there already are locally hosted libraries in this repository which is why I decided to go for a local copy). non the less the current style is ugly as fu** and should be exchanged for a more modern approach, migrating to cdn can be done in a later PR after this one has passed, including migration of Chart.js)

**Comment by Prior99** [comment]
@PurHur Additionally I want to add that using cdns for each-and-everything highly increases the amount of HTTP-connections to be done for loading the website which can not be done in a keep-alive-connection so for each library hosted on a cdn there will be one additional connection to be established which largly increases the loading time.

Using a cdn for one or two libraries might be okay, but when it comes to bootstrap which has 3 files to include, jquery, Chart and maybe npm we come to 5 or more connections not including fonts and images. If we host them locally this can all be done using one keep-alive connection which is not possible when using external hosters.

**Comment by mappum** [comment]
:+1: @shalecraig CDNs would be a big point of weakness. Not that anyone has a reason to attack the bot yet...

**Comment by korczis** [comment]
:-1: 

Can we use bower for bootstrap installation?

**Comment by korczis** [comment]
http://getbootstrap.com/getting-started/#download-bower

**Comment by AppleDreck** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7jg"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

**Comment by Prior99** [comment]
Ohh, just look at it's beauty <3

**Comment by dos1** [comment]
Ahahahahahaha it already passed but still deserves my vote :+1:

**Comment by SpenserJ** [comment]
This is horrible! It has broken the mobile functionality entirely, since the menu is covered by the github flag. :-1: even though it doesn't count

**Pull request merged**
