### PR TITLE
Update ideas.md

### PR DESCRIPTION
**Pull request by rdancer**
Interact with other users on Twitter/Reddit/IRC

### CODE REVIEW

**Comment by MaerF0x0** [comment]
LGTM

**Comment by SpenserJ** [comment]
:+1:

**Comment by blklane** [comment]
:+1:

**Comment by jvt** [comment]
:+1

**Comment by mgberlin** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* fc755b41ec0585d1fe387e6fde504c4c7ea33a0e

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=a3g"></a>
:+1: The vote passed, this PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (100%) 
:-1:: 0 (0%)

**Pull request closed without merging**
