### PR TITLE
Reduced polling even more

### PR DESCRIPTION
**Pull request by mappum**
Just to be sure the bot doesn't hit Github's API request rate limit. The *real* fix is to use webhooks and conditional requests instead of haphazardly using up all our requests.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* fecf5aefec62f50dea1b2b714d5b47c60462ddf2

**Comment by mappum** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1: This is REALLY needed

**Comment by possibilities** [comment]
:+1:

**Comment by rspeer** [comment]
:+1:

**Comment by znrg** [comment]
+1

**Comment by znrg** [comment]
:+1:

**Comment by dazoe** [comment]
:+1:

**Comment by cyntran** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=rj"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @possibilities
 * @znrg
 * @znrg

**Pull request merged**
