### PR TITLE
Travis CI, Badges, Better Folder structure, etc

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* d4f0131063fc1079734a94845480cc4b0fe92c16

**Comment by generalhenry** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: for the third time :grin:

**Comment by korczis** [comment]
Hopefully now ;-)

**Comment by dos1** [comment]
first two were fine, but I don't like this one :-1:

**Comment by mappum** [comment]
:+1:

**Comment by dos1** [comment]
meh, just kidding :D
:+1:

**Comment by thenightwassave** [comment]
:+1:
haha

**Comment by korczis** [comment]
@dos1 I just was about to ask you what is wrong with this one ;-)

**Comment by avdg** [comment]
:+1:

**Comment by korczis** [comment]
Can some of the owners enable travis for https://github.com/botwillacceptanything/botwillacceptanything and fix badge link in README.md after this gets merged?

**Comment by rspeer** [comment]
:+1:

**Comment by mappum** [comment]
@korczis Sure, I'll do that.

**Comment by tcyrus** [comment]
:+1:

**Comment by mappum** [comment]
We'll have to fix the build badge in a new PR. @korczis Can you do that after this merges?

I already enabled Travis for the repo.

**Comment by korczis** [comment]
@mappum ok

**Comment by dos1** [comment]
ping

**Comment by rspeer** [comment]
:+1:

**Comment by drsirmrpresidentfathercharles** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=575"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 10 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=575"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 10 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Comment by mappum** [comment]
@korczis I reverted this because it broke normal bot operation. You can resubmit it if you fix it and test it.

**Pull request merged**
