### PR TITLE
Post random kitten image when pull request is merged

### PR DESCRIPTION
**Pull request by dos1**
One image is persistent per bot instance - so with each merged pull request it's going to be different (unless the logic of bot restart is changed)

Another try after #28, which failed due to merge conflict :(

### CODE REVIEW

**Comment by mayli** [comment]
:+1: Nice patch

**Comment by OLef1air** [comment]
Still good :+1:

**Comment by AgentME** [comment]
:+1:

**Comment by rntz** [comment]
:+1:

**Comment by ehaughee** [comment]
:+1:

**Comment by thmas** [comment]
:-1:

**Comment by fiveminuteargument** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* c2d781a0c6bb1b95b3c46e39622c5ecc5e4a2fac

**Comment by jusio** [comment]
:+1:

**Comment by JWesorick** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by bradleybuda** [comment]
:-1: 

Not resistant to API failures. Can't let a cat API take the bot down

**Comment by shalecraig** [comment]
:-1: as it is, I agree with @bradleybuda

**Comment by bradleybuda** [comment]
Would be better to use an embedded image ala `http://thecatapi.com/api/images/get?format=src&type=gif` - that way we don't need to make the call in order to post a comment.

**Comment by dos1** [comment]
@bradleybuda: Actually, it is. A failure to get a kitten won't disturb a bot's operation - the "kitten" variable will be empty, so it will work like before.

**Comment by rdancer** [comment]
<a target="_blank" href="http://thecatapi.com/?id=5ka"></a>
:+1:  I like this!

**Comment by dos1** [comment]
@bradleybuda: But I agree that embedded image will be better. Good thing for next pull request :)

**Comment by lol768** [comment]
:+1:

**Comment by AgentME** [comment]
@bradleybuda Would that should show the same image to everyone? I like the shared experience and consistency of knowing everyone sees the same one.

**Comment by dos1** [comment]
@AgentME: Good catch! It wouldn't.

**Comment by lol768** [comment]
Hmm, would GitHub's image proxy cache it and therefore end up showing the same image anyway?

**Comment by AgentME** [comment]
Probably only for a limited amount of time, and maybe just in specific geographic regions if they have multiple caching servers.

**Comment by dos1** [comment]
Plus the embedded image with constant url can raise copyright issues: http://thecatapi.com/docs.html#get

**Comment by songgao** [comment]
:+1:

**Comment by Xandaros** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
