### PR TITLE
Added IRC channel to README

### PR DESCRIPTION
**Pull request by mappum**
I created an IRC channel for the BWAA community. #botwillacceptanything on Freenode.

### CODE REVIEW

**Comment by mappum** [comment]
:+1:

**Comment by Xandaros** [comment]
:+1:

**Comment by karolba** [comment]
:+1:

**Comment by ClintLiddick** [comment]
:+1:

**Comment by awilliamson** [comment]
:+1:

**Comment by mayli** [comment]
:+1:

**Comment by rdancer** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by Xandaros** [comment]
:+1:

**Comment by rntz** [comment]
Hey @mappum you should probably update this so it doesn't have a merge conflict, otherwise I think the bot won't merge it.

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged
The changes in this PR conflict with other changes, so we couldn't automatically merge it.
You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Pull request closed without merging**
