### PR TITLE
Docker Scripts, attempt #3

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* e7333adc7c5cd31eaf1df63b5878f2e320981020

**Comment by dos1** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by jedahan** [comment]
:+1:

**Comment by mappum** [comment]
:+1: I had been waiting for Docker stuff to happen for a while

**Comment by pandzieciol** [comment]
:+1:

**Comment by caffeinewriter** [comment]
:+1:

**Comment by korczis** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=43q"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Pull request merged**
