### PR TITLE
Added twitter to package.json

### PR DESCRIPTION
**Pull request by mappum**
Should have been in the twitter PR, I had to install it manually.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* c818fd18ad0fc8fcefd1ee0e6d35862094cbeed9

**Comment by avdg** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* c818fd18ad0fc8fcefd1ee0e6d35862094cbeed9

**Comment by mappum** [comment]
Opening for a new vote (does that even work?)

**Comment by kyleshockey** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by gpersons** [comment]
:+1:

**Comment by clay-to-n** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=5qn"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @kyleshockey

**Pull request merged**
