### PR TITLE
Randomly decide how much the bot likes people

### PR DESCRIPTION
**Pull request by shalecraig**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* a02043b0198b334bdf052895cceff907c8d30772

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by dos1** [comment]
Nah, it should have some kind of persistency. Randomizing might be good at the first contact though :-1:

**Comment by thenightwassave** [comment]
:-1:

Yeah now it just says something random to you when you join. Totally removes the point of levels at all.

**Comment by samis** [comment]
I agree with the above statement. A mixture of randomization and persistence is required. Will upvote if this is done. Perhaps it uses a persistent marker as the 'base' or starting point and then randomly decides how *much* it likes / hates you. :-1:

**Comment by shalecraig** [comment]
@samis  & @thenightwassave want to hop into irc?

**Comment by samis** [comment]
I am in IRC. Want my nick?

**Comment by thenightwassave** [comment]
I am too. :)

**Comment by shalecraig** [comment]
please take a look at the irc convo about this PR

**Comment by SpenserJ** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by PurHur** [comment]
:-1:

**Comment by pandzieciol** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 4 (50%) 
:-1:: 4 (50%)

**Pull request closed without merging**
