### PR TITLE
English grammar; and remove a redundant assignment in #16.

### PR DESCRIPTION
**Pull request by Quuxplusone**
No intended functional change.

### CODE REVIEW

**Comment by Quuxplusone** [comment]
:+1:

**Comment by fiveminuteargument** [comment]
:+1:

**Comment by jgod** [comment]
:+1:

**Comment by jrfinkel** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by thmas** [comment]
:+1:

**Comment by AgentME** [comment]
:+1:

**Comment by hintss** [comment]
:+1:

**Comment by begizi** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 8447eb33ef7b91061c091dc7f94d1617ee9dddd3

**Comment by avdg** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by AgentME** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged
The changes in this PR conflict with other changes, so we couldn't automatically merge it.
You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Comment by Quuxplusone** [comment]
I'm not going to keep updating this PR. Someone else take it from here.

**Pull request closed without merging**
