### PR TITLE
Made bot friendlier

### PR DESCRIPTION
**Pull request by mappum**
The bot was a little insulting before. I'd like our robot overlord to be friendlier :smile:

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* a8558e6a62040ec391d79a56052276706f2d7e5d

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: :+1: :+1: :heart:

**Comment by shalecraig** [comment]
:+1:

**Comment by shalecraig** [comment]
also, what: https://github.com/botwillacceptanything/botwillacceptanything/pull/284#issuecomment-92578747

**Comment by SpenserJ** [comment]
@shalecraig The bot votes on posts that it likes or dislikes. https://github.com/botwillacceptanything/botwillacceptanything/blob/master/lib/voting.js#L147-L165

**Comment by Petah** [comment]
:-1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by hansenitsolutions** [comment]
:-1:

**Comment by jedahan** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MjA4MzMzMQ"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (87.5%) 
:-1:: 1 (12.5%)

These users aren't stargazers, so their votes were not counted: 
 * @hansenitsolutions

**Pull request merged**
