### PR TITLE
Keep twitter credentials in the vault

### PR DESCRIPTION
**Pull request by mwerner**
This is making use of the vault for twitter credentials.

I hit these endpoints to populate the `secrets.yml` file on the server:

```
http://162.243.149.229:3000/secrets?twitter_consumer_key=xPBdmKMtzBVNCP7sosmCd9mJV
http://162.243.149.229:3000/secrets?twitter_consumer_secret=VYaUwAsQpsfMyNnAtVmim5RpJ7kxxxp7hE2BoZQQe3qraA7Qtn
http://162.243.149.229:3000/secrets?twitter_token_key=3148038378-jZ7yFPOKZZBcbFV0Ws3gAWmB4kdvOdGWvKAJjRb
http://162.243.149.229:3000/secrets?twitter_token_secret=8snyglTPXq80XbDNAUd6vfImSep4emX4A9ViDZNeJ19Qn
```

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* bee3df056fdc4c85134edc7ffb012601e9022b37

**Comment by mappum** [comment]
FYI I keep seeing errors from the vault code: https://gist.github.com/mappum/b6d1b6594645410f2897

**Comment by rspeer** [comment]
Am I missing something? Doesn't posting the credentials in a PR completely defeat the point?

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* bee3df056fdc4c85134edc7ffb012601e9022b37

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by drsirmrpresidentfathercharles** [comment]
This is very important. :+1: The credentials are already in the repository history, so they will need to be regenerated by whomever has access to the Twitter account.

**Comment by dos1** [comment]
:+1:

**Comment by pandzieciol** [comment]
:+1:

**Comment by mwerner** [comment]
@rspeer yeah, but they're already in the diff. I just wanted to provide a double check to make sure i copied the correct keys

**Comment by kblanks** [comment]
:+1:

**Comment by digitalvapor** [comment]
:+1:

**Comment by drsirmrpresidentfathercharles** [comment]
I'm aware they're in the diff. They need to be regened so that they are
secure.

**Comment by generalhenry** [comment]
:+1:

**Comment by lukeheath** [comment]
:+1: I have Twitter credentials. I also created botwillacceptanything@gmail.com if needed. @mwerner - DM @anythingbot on Twitter or email and I'll send you new secrets.

**Comment by dos1** [comment]
@lukeheath: I think it's @mappum you should send the credentials to.

**Comment by mwerner** [comment]
@lukeheath you can just set those values to different keys using the `/secrets` edpoint and make a PR to use the updated keys.

**Comment by lukeheath** [comment]
@mwerner - Cool I'll do that shortly.

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=5n6"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 9 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=5n6"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 9 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Comment by lukeheath** [comment]
@mwerner  - Looks like no go. Try again? Although if anyone can hit the /secrets endpoint with new keys, couldn't they easily change to another account? 

Maybe makes sense to send the keys directly to @mappum so the endpoint doesn't have to be public. Thoughts?

**Comment by mwerner** [comment]
Yeah we might as well take this opportunity to get unknown keys in use. @mappum if you can regenerate the keys and post them to the `/secrets` endpoint with new keys, just let me know the keys and I'll update this PR

**Pull request closed without merging**
