### PR TITLE
TinyUrls in Tweets

### PR DESCRIPTION
**Pull request by AlphaT3ch**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 0591f28853e1f3e9b41aaecb7cac3207999b1f08

**Comment by zztemp** [comment]
Do we need to shorten URLs? I thought Twitter did this automatically with t.co.

**Comment by rspeer** [comment]
Yo dawg, I heard you like short URLs, so I put a short URL in Twitter's URL shortener.

:-1:

**Comment by rspeer** [comment]
Also, yeah, it's got a syntax error.

**Comment by AlphaT3ch** [comment]
@rspeer I couldn't test it, but I've used the package before so I thought it'd be good. @zztemp Not with the API

**Pull request closed without merging**
