### PR TITLE
Preparation for launcher.js

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballotbox: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 7725b70df5cbb78681c0a9442e05ec244b390cac

**Comment by avdg** [comment]
Any use cases we all can agree about?

**Comment by SpenserJ** [comment]
Wouldn't it be more valuable to add in the launcher.js right now, and skip the boilerplate that checks for it? I like the concept, but :-1: until we have something more substantial

**Comment by rickardnorlander** [comment]
My idea is that a launcher could do these steps:
1. Perform self test.
2 a). If fails, run last good version.
2 b). If succeeds, store current version as last good
3. Launch the correct version

The advantages of keeping it in a separate process is that all timers and callbacks are cleared. This minimizes risks of concurrency issues.

**Comment by SpenserJ** [comment]
@rickardnorlander As far as I can tell, adding a launcher to this commit would have caused it to restart with the launcher immediately. As long as we test the merge before pushing, I don't see any reason why it wouldn't be stable switching to the launcher immediately.

I do like all of the ideas that a launcher brings.

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 7725b70df5cbb78681c0a9442e05ec244b390cac

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Pull request closed without merging**
