### PR TITLE
Grammar Stuff

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Just put some basic grammar corrections in there. Bot's IP taken from [issue #55](https://github.com/botwillacceptanything/botwillacceptanything/issues/55).

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* e504d3a06e3415a2748b7509e35bfd55ee1a10d3

**Comment by gitnik** [comment]
:+1:

**Comment by kramsee** [comment]
:+1:

**Comment by vytis** [comment]
:+1:

**Comment by karolba** [comment]
:-1: everybody knows what `PR` means

**Comment by atroche** [comment]
:-1:

**Comment by GvS666** [comment]
:-1:

**Comment by mitar** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 3 (60%) 
:-1:: 2 (40%)

These users aren't stargazers, so their votes were not counted: 
 * @gitnik
 * @atroche

**Pull request closed without merging**
