### PR TITLE
Add PR title to Tweet.

### PR DESCRIPTION
**Pull request by jish**
Take two of https://github.com/botwillacceptanything/botwillacceptanything/pull/158

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 352473c208e4be6b5c2131409236283b1c1f9cf9

**Comment by mwerner** [comment]
:+1:

**Comment by rickardnorlander** [comment]
It would be good to do a substring to make sure it fits in a tweet

**Comment by AlphaT3ch** [comment]
@rickardnorlander Good point! Anyways, nice addition! :+1:

**Comment by AlphaT3ch** [comment]
Also, we have to take it out of ideas.md

**Comment by pandzieciol** [comment]
:+1:

**Comment by korczis** [comment]
What about CHANGELOG.md ?

**Comment by dos1** [comment]
who cares about changelogs? :+1:

**Comment by CptnBrittish** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by avdg** [comment]
We should add `Changelog changed` in changelog.

**Comment by dos1** [comment]
@avdg: #164!

**Comment by devn** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=c7r"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Comment by clay-to-n** [comment]
Wow thanks for doing this!

**Pull request merged**
