### PR TITLE
Make number of votes required dependent on changes

### PR DESCRIPTION
**Pull request by patrickmclaren**
Make smaller changes easier to merge than larger changes. Can be thought of as encouraging small (incremental) mutations over larger mutations. Setting MIN_VOTES_WEIGHT=80 for approx. lines changed.

### CODE REVIEW

**Comment by mszaro** [comment]
:+1:

**Comment by patrickmclaren** [comment]
:+1:

**Comment by hintss** [comment]
*someone makes a PR that just comments out a line*

**Comment by rickardnorlander** [comment]
:-1:  This means just one vote needed for small changes

**Comment by hintss** [comment]
:-1:

**Comment by rdancer** [comment]
:-1:

**Comment by rdancer** [comment]
:-1:  Good idea, if you could measure semantically, not syntactically, small changes. If people take time to evaluate proposals (a daring assumption during the best of times), the voting process as-is already encourages smaller, self-contained, well-documented patches.

**Comment by thmas** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* b4273aacb337492f73107ed9055b66da97ec0706

**Comment by jvt** [comment]
:-1:  Good idea, however it could be abused via its execution. Needs a little more refinement to ensure there would be no abuse for small incremental changes.

**Comment by patrickmclaren** [comment]
Agreed. Did not consider author's vote - too used to SO, HN and reddit wherein the author's vote is implicit. Will make a small change with new PR, if it's approved, it can then be iterated upon to limit other potential for abuse. Perhaps someone could add a test suite to validate each PR for minimal functionality.

**Pull request closed without merging**
