### PR TITLE
Ignore instead of being rude

### PR DESCRIPTION
**Pull request by shalecraig**
re-rolling #359 

This improves things by always greeting people nicely in irc :)

cc @thenightwassave, @SpenserJ, @RyanMilb, @avdg

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 9948061ff0a56e7162d29bc9a52db5bb0adab79b

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by samis** [comment]
:+1:  for now. I do however, feel that the bot should be able to express both positive and negative emotions. We can achieve that in the future with a seperate PR.

**Comment by PurHur** [comment]
:-1: Your solution is not the yellow from the egg.

**Comment by thenightwassave** [comment]
:+1:

**Comment by avdg** [comment]
@PurHur https://www.google.be/search?q=the+yellow+from+the+egg&tbm=isch

**Comment by dos1** [comment]
Instead of ignoring, write better texts :-1:

**Comment by samis** [comment]
I agree with dos1 on principle. However, this is a good fix until we get better texts

**Comment by timweightman** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7nt"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (77.7%) 
:-1:: 2 (22.2%)

**Pull request merged**
