### PR TITLE
Add some porn

### PR DESCRIPTION
**Pull request by dos1**
Add some nice porn for bot to enjoy :+1:

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 886824f50755221eede8a9b219ce6dff2b393d70

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by korczis** [comment]
:+1: This one is good and usefull

**Comment by dos1** [comment]
@botwillacceptanything: I knew you will like it!

**Comment by samis** [comment]
:+1: Win.

**Comment by rickardnorlander** [comment]
:+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by VeoPVM** [comment]
:+1:

**Comment by idunnowhy9000** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: Beautiful!

**Comment by mappum** [comment]
Hawt :+1:

**Comment by AlphaT3ch** [comment]
WOW! Best pr0n I've ever watched! Thanks for the good times man! :+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 886824f50755221eede8a9b219ce6dff2b393d70

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=ecg"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 11 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
:+1:

**Pull request merged**
