### PR TITLE
Travis CI build notifications

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* e18ea8f28f7aa64d3391b2fec18347b2b1aa6379

**Comment by avdg** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by boie0025** [comment]
:+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by scottwarren** [comment]
:+1

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* e18ea8f28f7aa64d3391b2fec18347b2b1aa6379

**Comment by r04r** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by korczis** [comment]
What is up?

**Comment by dos1** [comment]
Up is a Disney/Pixar movie. You should definitely check it out!

**Comment by dos1** [comment]
Hmm, did the voting time reset with that new "voting procedure reminder" post?

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=b10"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 10 (100%) 
:-1:: 0 (0%)

**Comment by dos1** [comment]
Nope, it didn't :)

**Comment by korczis** [comment]
Finally.

**Pull request merged**
