### PR TITLE
abandon all hope ye who enter here

### PR DESCRIPTION
**Pull request by dbpokorny**
This PR allows anyone in the chat room to ask the anythingbot to pre-empt the video feed. Currently there is only one playlist (creating, modifying, and deleting playlists dynamically with chat commands can be implemented by a subsequent PR).

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 e823211f52511a65b99fa4d48a174e05e976bdb9

**Comment by dos1** [comment]
hopefully you tested it™ :+1:

**Comment by dbpokorny** [comment]
lol you think I know how to test it xD

**Comment by catsgame** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=d3a"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 5 (100%)
:-1:: 0 (0%)

These following 1 voter(s) were not _stargazers_, so their votes were not counted:

- :monkey: @coveralls

*Non-stargazers*: Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
