### PR TITLE
Let it communicate with others

### PR DESCRIPTION
**Pull request by jbwyme**
Let's make it possible to contribute publicly available services to the bot

### CODE REVIEW

**Comment by chrismeller** [comment]
This doesn't actually provide any functionality. :-1:

**Comment by thmas** [comment]
:-1:

**Comment by jrfinkel** [comment]
sorry josh! :-1:

**Comment by hintss** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 44ae5f8fe29456c5bcec3ed2c16eb4ff1308ea06

**Comment by dos1** [comment]
have at least one thumb up: :+1:

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged
The changes in this PR conflict with other changes, so we couldn't automatically merge it.
You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Pull request closed without merging**
