### PR TITLE
BWAA-TV Reroll

### PR DESCRIPTION
**Pull request by dbpokorny**
Consumerism is awesome! I love how sentiment analysis is conditioning me to write bright and cheerful messages! Hi bot!

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* d7ee524e1fbbb28bcf82338f15ca7bb8f2d0a8e2

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by SpenserJ** [comment]
:-1: for scamming the not. But I like the idea

**Comment by shalecraig** [comment]
:-1: for scamming the bot

**Comment by dbpokorny** [comment]
ugh, downvote all you want, these are the most random videos. If this goes down in flames and I have the time...wait, I'll just have it serve the 6.001 lectures. Closing this down

**Comment by SpenserJ** [comment]
I'm expecting it to pass. Scamming the bot isn't really a problem, and I want to see this go live :+1:

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Pull request closed without merging**
