### PR TITLE
Update PR merged tweet text.

### PR DESCRIPTION
**Pull request by jish**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 6c87143f2075e7c3b0dc16aecd9dd65b118d6622

**Comment by zztemp** [comment]
:+1:

**Comment by avdg** [comment]
:-1: `pr` defined as global while used later as local in a function

**Comment by mwerner** [comment]
:+1: consistent with the other messaging

**Comment by jish** [comment]
@avdg good catch, let's see if I can add another commit, or if it will auto-close.

**Comment by dos1** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Pull request closed without merging**
