### PR TITLE
The anythingbot recognizes the United States of America

### PR DESCRIPTION
**Pull request by dbpokorny**
well not exactly. The syntax is taken from "ifconfig" and the directives don't really make any sense at all...there is a larger point here, which is that it is possible to "direct" the "public" (i.e. http) performance of the anythingbot based on directives given "behind the curtain" (i.e. irc chat).

So the idea is to create a kind of "Wizard of Oz" -like effect for those users who hit the http endpoints before going to chat. Of course anyone can play the role of wizard, but you have to know the "secret commands" (which are of course publicly available in the source code on github, but you have to read the source to find them, which takes a certain amount of courage)

If at some point the thought crosses your mind, "this kinda sorta makes sense" then I apologize, that was NEVER my intention.

### CODE REVIEW

**Comment by dbpokorny** [comment]
oops, forgot: you can test it out at anythingbot.org:3000 and by giving directives to "simplebot1" in irc

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 c46342d93026ff68650bf1a9d5207a6aa90790bc

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by dbpokorny** [comment]
closing this out, this is a terrible idea, just fork the anythingbot and go work on the complainbot if you like this

**Comment by dbpokorny** [comment]
In case anyone is wondering, this isn't some kind of sike. I really did have some crazy idea...anyway, to prove this to you, here is the complete list of commands I had ready before I came to my senses and figured out that the road leads to either (A) a dead end or (B) "Thelma & Louise:Ending Scene".

Anyway, for the philistines, I am *not* suggesting that a new french revolution will solve the problems the USA has. That would be a version of the situation Mark Knopfler found himself in with regards to "Money for Nothing" (source: http://en.wikipedia.org/wiki/Money_for_Nothing_%28song%29)

The lyrics for the song were criticised as being homophobic.[citation needed]

In a late 1984 interview in Rolling Stone magazine, Knopfler expressed mixed feelings on the controversy:

I got an objection from the editor of a gay newspaper in London – he actually said it was below the belt. Apart from the fact that there are stupid gay people as well as stupid other people, it suggests that maybe you can't let it have so many meanings – you have to be direct. In fact, I'm still in two minds as to whether it's a good idea to write songs that aren't in the first person, to take on other characters. The singer in "Money for Nothing" is a real ignoramus, hard hat mentality – somebody who sees everything in financial terms. I mean, this guy has a grudging respect for rock stars. He sees it in terms of, well, that's not working and yet the guy's rich: that's a good scam. He isn't sneering.[14]

Just replace "homophobic" with "homicidal", "songs" with "pull requests", "ignoramus" with "revolutionary nutcase", and a few others you can figure out on your own, and you have an approximation of my thoughts on the matter. Anyway, here goes:

anythingbot usa cia : Sister Sledge - We Are Family
anythingbot usa empire : Backstreet Boys - Larger Than Life
anythingbot usa moon : MTV Moon Landing
anythingbot usa goat : Heliofant - I, pet goat II
anythingbot usa llama : The Emperor's New Groove Kuzco Turns Into a Llama
anythingbot usa flea : The Emperor's New Groove - Pull the Lever, Kronk
anythingbot usa weird : Weird Al Yankovic UHF Rambo Scene
anythingbot usa guitar : Jimi Hendrix - The Star Spangled Banner [ American Anthem ] ( Live at Woodstock 1969 )
anythingbot usa nwo : GHW Bush SOTU Address January 29, 1991 "A New World Order"
anythingbot usa nsa : BEST TWERK CHOREO!
anythingbot usa threestooges : Charlie Rose - An hour with Zbigniew Brzezinski, Brent Scowcroft & Henry Kissinger
anythingbot usa economy : 111222 Counter cultural Values \ \ Thanissaro Bhikkhu \ \ Dhamma Talks
anythingbot usa 80s : VHS Logos - Marinate Mix
anythingbot usa war : Dr. Strangelove (1964) - War Room Scene
anythingbot usa peace : President John F. Kennedy's "Peace Speech"
anythingbot usa twerk : The Matrix- Agent Dodge
anythingbot usa freedom : Don't Tell Mom... the Babysitters Dead Trailer 1991
anythingbot usa slavery : 'N Sync - Bye Bye Bye
anythingbot usa britney : Britney Spears - ...Baby One More Time
anythingbot usa justin : Justin Timberlake - Ellen ( gingerbread man)
anythingbot usa mtv : Dire Straits - Money For Nothing music video (Good quality, all countries)
anythingbot usa miracle : Miracle Max
anythingbot usa jfk : Ask Not What Your Country Can Do For You!
anythingbot usa money : Milton Friedman - Greed
anythingbot usa solve : The French Revolution: Crash Course World History #29

anythingbot usa help : say "what aspect of USA culture would you like to explore?
I understand " + autogen the list because there are too many

**Pull request closed without merging**
