### PR TITLE
Add an example config.

### PR DESCRIPTION
**Pull request by jish**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 401859ce03df1820877e2aca030fdfc495bc8297

**Comment by korczis** [comment]
:-1:

There is already example config.

See https://github.com/botwillacceptanything/botwillacceptanything/blob/master/config.template.js

**Comment by korczis** [comment]
It seems the development is too quick....

**Comment by mappum** [comment]
What he said ^ :-1:

**Comment by SpenserJ** [comment]
:-1:

**Comment by jish** [comment]
Sorry, didn't see it there... :(

**Comment by korczis** [comment]
@jish it is mentioned in README.md

**Comment by jish** [comment]
> "It seems the development is too quick...."

**Comment by jish** [comment]
It wasn't there last time I checked.

**Pull request closed without merging**
