### PR TITLE
Best Favicon!

### PR DESCRIPTION
**Pull request by AlphaT3ch**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 34fd495038d05a90862e6337148265edd59542b5

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by FangedTerror802** [comment]
:+1:

**Comment by OLef1air** [comment]
:-1:

**Comment by shalecraig** [comment]
Can't see the favicon in the diff :cry: 

:-1:

**Comment by AlphaT3ch** [comment]
@OLef1air and @shalecraig: The new favicon can be viewed here
https://raw.githubusercontent.com/AlphaT3ch/botwillacceptanything/master/data/favicon.ico

**Comment by OLef1air** [comment]
I know but I don't like the whole mlp theme

**Comment by dos1** [comment]
I have a hard time to decide how to vote. I believe it should be Twilight Sparkle, as we already got Pinkie (earth pony) in badges and Rainbow Dash (pegasus) on website. Unicorn race is not represented anywhere (well, technically she's an alicorn now, but I guess it still counts as unicorn)

**Comment by RyanCopley** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=309"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (85.7%)
:-1:: 1 (14.2%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
