### PR TITLE
Feature webserver display stdout

### PR DESCRIPTION
**Pull request by SpenserJ**
Rerolling #97 to fix the package.json issues

### CODE REVIEW

**Comment by SpenserJ** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballotbox: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 8ef53382cb3dd0191c28f7be53a943418bc8ae30

**Comment by r04r** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by roby65** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1: Cool!

**Comment by rickardnorlander** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTcwNjIwNQ"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (100%) 
:-1:: 0 (0%)

**Pull request merged**
