### PR TITLE
Add Pinkie Pie badge

### PR DESCRIPTION
**Pull request by dos1**
Badges are awesome! We need more badges! There are never too many badges!

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 996c86a52260a991bea3d4800e829d91b79fca86

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by SpenserJ** [comment]
Screw you @botwillacceptanything. Accept anything but this! :-1:

**Comment by AlphaT3ch** [comment]
Pinky poo :-1:

**Comment by korczis** [comment]
:-1: We need useful badges, not any pinky poo ... Sorry @dos1

**Comment by pandzieciol** [comment]
:+1:

**Comment by plor** [comment]
I'll bite :+1:

**Comment by shalecraig** [comment]
:+1: badgebadgebadge

mlp

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 5 (62.5%) 
:-1:: 3 (37.5%)

**Comment by dos1** [comment]
;_;

**Pull request closed without merging**
