### PR TITLE
Develop a Definition of Done

### PR DESCRIPTION
**Pull request by SpenserJ**
Moving forward, all PRs must meet the criteria listed in the Definition of Done, including this PR.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 4c2f390904070e0c57ca012369fe5f43afe4d8d9

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by korczis** [comment]
:+1: It is good to have rules specified ...

**Comment by RyanMilb** [comment]
:+1:

**Comment by dos1** [comment]
takes the fun out :-1:

**Comment by dbpokorny** [comment]
:-1: We already have a definition of done: 8 votes.

**Comment by pandzieciol** [comment]
:-1:

**Comment by SpenserJ** [comment]
This would help prevent unfinished functionality, or code that isn't tested. Voting just means that we like it, not that its known to work. How many people are actually testing code before they upvote?

**Comment by dbpokorny** [comment]
Nobody is testing code, this whole project is cowboy performance art http://en.wikipedia.org/wiki/Cowboy_coding

**Comment by korczis** [comment]
@dbpokorny Nobody was testing the code because there was no testing framework engaged into CI pipeline.

**Comment by SpenserJ** [comment]
My thoughts exactly. If we've never had a testing procedure, and everyone is against a stable bot, there is no point in implementing processes to improve the quality of code. But I'd rather not need to restart the bot every 12-24 hours to make sure it works properly.

**Comment by dos1** [comment]
Yes for testing framework being available; some mechanism for automatic restarts when something goes wrong; maybe even automated emergency merge/revert protocol.
No for strict rules about which PR can and which cannot go in. 

Users should be able to screw up and others should be able to mock them because of that. Otherwise difference between this project and other projects on github will be just theoretical.

**Comment by bartg** [comment]
I like what @SpenserJ mentioned but it changes this fun project to normal Open Source project. Community should be responsible for making it work. It breaks, vote for the fix. :-1:

**Comment by samis** [comment]
I agree. This just changes the project into a project-with-a-minor twist. :-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 4 (50%) 
:-1:: 4 (50%)

These users aren't stargazers, so their votes were not counted: 
 * @botwillacceptanything
 * @bartg

**Pull request closed without merging**
