### PR TITLE
Make number of votes required dependent on changes (V2)

### PR DESCRIPTION
**Pull request by patrickmclaren**
Make smaller changes easier to merge than larger changes. Can be thought of as encouraging small (incremental) mutations over larger mutations. Setting MIN_VOTES_WEIGHT=80 for approx. lines changed.

Previously at #45, although very open to abuse (by author's own vote). Increased minimum to 2 votes. This change, together with 30 minute voting period only slightly limits abuse potential (collusion, multiple accounts, etc.). One improvement could be to validate each PR against a test suite for minimal functionality.

### CODE REVIEW

**Comment by patrickmclaren** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 47abe017207a045b174bcc86b53cee5321882f67

**Comment by JWesorick** [comment]
:+1: +1:

**Comment by bradleybuda** [comment]
:-1:

Like the idea but the formula needs tweaking. i.e. this PR would score `2` as its `minVotes`:

`Math.round(Math.log(Math.E + ((19 + 7) / 80))) + 1`

What if the base constant is increased to 4 or 5 instead of 1?

**Comment by rdancer** [comment]
:-1: Doesn't address the concerns raised in the previous proposal.

**Comment by rntz** [comment]
:-1: Code size is not a good measure of the impact of a change, especially if people are malicious.

**Comment by erasmospunk** [comment]
:-1: 
Too complicated

**Comment by botwillacceptanything** [comment]
:-1: Opens up lots of attacks. Anyone could kill the whole bot with a one character change.

**Comment by mappum** [comment]
:-1: Opens up lots of attacks. Anyone could kill the whole bot with a one character change.

**Comment by shalstvedt** [comment]
:-1:

**Comment by chrismeller** [comment]
:-1:

**Comment by jvt** [comment]
:-1:

**Comment by souravzzz** [comment]
:-1:

**Comment by nitrix** [comment]
:-1: 

What we could do though, is increase the voting time if there's more code to review.

**Comment by hintss** [comment]
:-1:

**Comment by drusepth** [comment]
:-1: Adding my support

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed.

----
**Tallies:**
:+1:: 2 (14.2%) 
:-1:: 12 (85.7%)

**Pull request closed without merging**
