### PR TITLE
Added domain name to README links

### PR DESCRIPTION
**Pull request by mappum**
I bought a domain for the bot (botwillacceptanything.com).

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 6c0f7d7cb9bc97fdfb8737a725fafd5c1a1166d7

**Comment by zztemp** [comment]
:+1:

**Comment by aristidb** [comment]
Fancy :+1:

**Comment by korczis** [comment]
:+1:

**Comment by samis** [comment]
This is nice. :+1:

**Comment by SamsPepper1** [comment]
:+1:

**Comment by Stary2001** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by rspeer** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by jvt** [comment]
Me gusta :+1:

**Comment by AlphaT3ch** [comment]
:+1: Cool DNA!

**Comment by AlphaT3ch** [comment]
*DNS - won't let me edit that post for some reason

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 6c0f7d7cb9bc97fdfb8737a725fafd5c1a1166d7

**Comment by SpenserJ** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=agv"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 13 (100%) 
:-1:: 0 (0%)

**Pull request merged**
