### PR TITLE
Replaced all offensive words with non-offensive ones:

### PR DESCRIPTION
**Pull request by Prior99**
I replaced all offensive words with non-offensive ones so @shalecraig doesn't get offended and can live in his colorfull pink fluffy world :-)

### Places

before                               | after
---------------------------------|------
hell                                    | flowerfield
hospital                             | ponyranch
4chan                               | the bed
your mothers anus            | garden
somewhere else                | meadow

### Person Actions

before                               | after
---------------------------------|------
die                                    | cuddle
suffocate                          | peep
suffer a horrible death     | dream
get rekt                            | sleep
get killed                          | play with me
get cancer                        | ride ponys
get raped                         | lie in the grass

### Attributes

before                               | after
---------------------------------|------
ugly                                   | beautiful
stinky                                | cute
wothless                           | fluffy
stupid                                | tiny
dumb                                | nice

### Multiplicators
before                               | after
---------------------------------|------
fucking                              | cute

### Names

before                               | after
---------------------------------|------
bitch                                 | bunny
idiot                                   | flower
fucker                               | fluff
retard                               | bird
kid                                    | puppy
douchebag                      | kitty
morron                             | beetle
asshole                             | chocolate
goatf***er                         | -

### Bot Actions:

before                               | after
---------------------------------|------
kill                                     | cuddle
punch                               | stroke
beat                                  | kiss
kick                                  | tickle
ban                                  | snuggle

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 78f9fb486119d6935cf65ca5dd2ff22ac48f7b83

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by Prior99** [comment]
:+1:

**Comment by timweightman** [comment]
@Prior99 Thanks for doing this- I'd be happy even if they were just less grotesquely heinous...

I also have [#370](https://github.com/botwillacceptanything/botwillacceptanything/pull/370) which allows us to configure whether bot is evil or not, and fixed heaps of linting errors in communicator.js.
I recommend more :+1:'s! (Plus here's one for you)

**Comment by dbpokorny** [comment]
:+1:

**Comment by shalecraig** [comment]
:+1:

**Comment by Prior99** [comment]
Thanks, but it doesn't matter, I am currently working on a full-feature conversationsystem including mood, and bot-sex-talk with reactions and stuff.

**Comment by nadavoosh** [comment]
+1

**Comment by shalecraig** [comment]
@nadavoosh : need to type `:+1:` to make the :+1: symbol. It doesn't work otherwise.

**Comment by PurHur** [comment]
:+1:

**Comment by dos1** [comment]
loving the description <3

**Pull request closed without merging**
