### PR TITLE
Always install dependencies and log out the IP that the bot is running on at startup

### PR DESCRIPTION
**Pull request by jbwyme**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 45932ef7f24dba71106b0abdf343c3ddac57fc86

**Comment by shalstvedt** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 45932ef7f24dba71106b0abdf343c3ddac57fc86

**Comment by mappum** [comment]
:+1:

**Comment by CptnBrittish** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:-1: This will not automatically merge due to an old fork being pull requested. Try deleting the current fork, forking the current one, making your changes then pull requesting it.

**Comment by OLef1air** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 2 (40%) 
:-1:: 3 (60%)

**Pull request closed without merging**
