### PR TITLE
[minor, whitespace] aesthetic enhancements & shit

### PR DESCRIPTION
**Pull request by edwardhotchkiss**
:8ball:

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 06214978b4fac7740160d1570506a4800a1f53ce

**Comment by jvt** [comment]
:+1:

**Comment by lambtron** [comment]
:+1:

**Comment by parhamr** [comment]
:+1:

**Comment by jamescostian** [comment]
... Why the extra new line at the beginning of README.md, main.js, and voting.js??

**Comment by edwardhotchkiss** [comment]
It's an aesthetics thing.

**Comment by clay-to-n** [comment]
:+1:

**Comment by jamescostian** [comment]
@edwardhotchkiss but in that case why don't you follow apply the same aesthetics to all of the other files? And why don't you apply the same aesthetics to [your own code](https://github.com/edwardhotchkiss/short/blob/4da3d4e2a4e3faa33cc4865d651639bde47a06cc/lib/short.js)?

**Comment by jamescostian** [comment]
Never mind, I'm an idiot, I just realized you're trolling lol

**Comment by edwardhotchkiss** [comment]
Suckerpunched by a child

**Comment by shalstvedt** [comment]
:+1:

**Comment by JWesorick** [comment]
:+1:

**Comment by generalhenry** [comment]
:+1:

**Comment by dos1** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
