### PR TITLE
Ignore sublime projects.

### PR DESCRIPTION
**Pull request by shalecraig**
Yeah. that.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 3733cf139e5a5632462cd7942f6f84b951ad79e5

**Comment by OLef1air** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by avdg** [comment]
there is .git/info/exclude for that, before we end up having all ignore files in .gitignore for everyone's favorite editor and tools ;-)

actually, https://help.github.com/articles/ignoring-files/#create-a-global-gitignore may be a better idea since its global instead of being local untracked gitignore file...

**Comment by RyanCopley** [comment]
:-1:

**Comment by shalecraig** [comment]
I work with a project that checks in their sublime-projects, so I don't have it in my global gitignore :cry:. 

TIL about `.git/info/exclude`. If this fails, I'll just put it there.

**Comment by dbpokorny** [comment]
"before we end up having all ignore files in .gitignore for everyone's favorite editor and tools"

avdg: why this is an outcome to be avoided

shalecraig: have you ever heard of a "rider"? http://en.wikipedia.org/wiki/Rider_%28legislation%29

If you sneak an extra line into a .gitignore in a larger project, then you may find that developers who don't care one way or the other about what goes in the .gitignore will support your PR.

Not having used .git/info/exclude, I don't know which is the bigger inconvenience: to have more in .gitignore or more in .git/info/exclude.

**Comment by avdg** [comment]
"why this is an outcome to be avoid"ed

@dbpokorny Interesting point

I'm used to projects where there are only a few committers, the others are contributors and have to pass their contributions to their lieutenants or code maintainers who have the rights to put the code in the version management system (vcs) - in this case it's a repository using git. It's very tiresome for them to always commit code that doesn't do anything for them.

But this code base is different. Instead of a few (limited) contributors, we can all vote code into the repository so the whole experience is different. Now we end up even more in the situation "can we maintain this code" and yeah, its a nice to have to keep the repo clean so we don't have too many monkeys around wondering what stuff we don't use is actually doing.

So in short, if we can care, it shouldn't be a problem.

But since everybody use different tools, maybe other settings I wouldn't know where we would end up. And yeah, I've seen lots of people who use git lazily and just commit everything without checking their patch and end up adding unintentionally changes they don't want to commit.

It makes me go "dunno" - should people learn their tools, or should we create better tools that clearly tells this should be local, this should be in the repo and this should be in the system config, but that only makes the problem bigger (or we need to make it easy to communicate about this).

I really don't know... For me it's a red flag and want to keep such stuff outside the repo, but it also makes life easier and even though it isn't the "ideal" solution, I guess we can take care of this yet...

**Comment by avdg** [comment]
Strictly speaking, I would like to see this as an os/filesystem standardization problem so it's solving a problem with not only git, but other version control systems...

But this would be the ideal thing, and the world can't have too many ideal things at once so...

**Comment by Prior99** [comment]
Why not :+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=75"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (85.7%)
:-1:: 1 (14.2%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
