### PR TITLE
Clean up the JSHint warnings

### PR DESCRIPTION
**Pull request by SpenserJ**
JSHint warnings are displayed in Travis, and can make it harder to spot the true test failures. This should clean most of them up.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 1bc33d4ada3d43a0076da9267571ac6b8bfb293a

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by wsterzik** [comment]
:+1:

**Comment by plor** [comment]
:-1: voting down for indentation.  Also would be good to add some test coverage.

**Comment by SpenserJ** [comment]
@plor What is the problem with the indentation, other than its all over the place right now? I'm looking to get all of the errors in JSHint cleaned up, so that the Travis CI builds are easier to understand. Fixing the indentation of everything will come at a later date, since it'll probably conflict with absolutely everything.

[Old Build - 122 lines of linting errors](https://travis-ci.org/botwillacceptanything/botwillacceptanything/jobs/59318052#L332-L454) - [New Build - 1 linting error](https://travis-ci.org/botwillacceptanything/botwillacceptanything/jobs/59446175#L339)

**Comment by plor** [comment]
@SpenserJ I just noticed spaces added in the context of tabs and it threw me off.  I'm normally in the tabs for indents camp, so knee-jerked on that.  I'll negate my first vote :+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by SpenserJ** [comment]
@plor Ah, I see what you mean. Our `.jshintrc` says to use two-space indentation, and that is what I have Vim set to, so I didn't even see the difference.

**Comment by OLef1air** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by Stary2001** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=1m2"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (85.7%)
:-1:: 1 (14.2%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
