### PR TITLE
Replace polling every 3m with webhooks

### PR DESCRIPTION
**Pull request by SpenserJ**
This is quite a large rewrite of some of the core voting code, so testing is essential on this one. I've already run through quite a few, and it seems to work extremely well, but more testing never hurts.

To implement it, follow the new instructions in the README.md, and set up your GitHub Webhooks to point at the server. Everything else should fall into place smoothly.

### CODE REVIEW

**Comment by mappum** [comment]
Awesome! This is the most important PR yet. :+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* aca387d1dbef813259269f8c3ab3ea48569575b7

**Comment by AlphaT3ch** [comment]
:+1: Awesome!

**Comment by dbpokorny** [comment]
:+1:

**Comment by SpenserJ** [comment]
Fingers crossed it all works out of the box. I did 14 PRs worth of testing in my fork, and it only switches about half the system away from polling, but its a good start.

**Comment by barranger** [comment]
:+1:

**Comment by avdg** [comment]
Risky, but :+1:

**Comment by dos1** [comment]
:+1:

**Comment by dos1** [comment]
BTW. what a nice pull request number for such change: #128 :)

**Comment by gpersons** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=5cq"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 9 (100%) 
:-1:: 0 (0%)

**Pull request merged**
