### PR TITLE
Add gitter chat

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 94dc5633911885c66f616ef762dad2b1adf6da4d

**Comment by SpenserJ** [comment]
Gitter is throwing a 404 on that URL right now. What is the value of adding gitter when we already have a healthy IRC channel? :-1:

**Comment by korczis** [comment]
It needs to be setup by somebody from admin team.

IE, some of the owners should click that link and enable integration..

In my opinion gitter is much easier to use that IRC, you do not have extra client for it, you have browser already.

**Comment by thenightwassave** [comment]
This would split the community in two. The only way to have one unified chat is to start with Gitter and then use their IRC mode. 

There is many IRC web clients too, one hosted on freenode itself.

:-1:

**Comment by SpenserJ** [comment]
Personally, I prefer to use IRC over another website. I have Irssi running in my terminal, and can switch between code and IRC quite easily, while Gitter means navigating the dozen tabs that I usually have open. I'm also a bit extreme in how much I do in the terminal though.

**Comment by korczis** [comment]
I liked IRC in 90's but these days Joe the Average does not even knows what IRC is.

**Comment by dos1** [comment]
:-1:

**Pull request closed without merging**
