### PR TITLE
Keep vote open until supermajority either way is achieved

### PR DESCRIPTION
**Pull request by rntz**
Currently the vote fails if there are < 65% upvotes. With this patch, it stays open until there are either >65% upvotes **or** >65% downvotes.

Also, currently, if a PR has 4 upvotes, and someone adds 1 downvote, this causes the vote to succeed! Downvoting should never cause a PR to pass! So now it checks that there are **either** at least 5 upvotes **or** at least 5 downvotes before closing the vote.

### CODE REVIEW

**Comment by rspeer** [comment]
:+1:

**Comment by rntz** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by biggerfisch** [comment]
:+1:

**Comment by rdancer** [comment]
:-1: Timing out on PRs which didn't get enough support in time is a good thing. Zombie proposals are not. Nothing stops the proposer from re-submitting.

**Comment by rspeer** [comment]
I'd hardly call a vote that's been open for 30 minutes a "zombie proposal". I'd suggest a separate PR to make deadlocked votes time out after a much longer period.

**Comment by mappum** [comment]
:-1:

**Comment by biggerfisch** [comment]
@rdancer This doesn't actually seem to modify the time at all, just stops a downvote from passing a PR (as yours technically did as of my comment!)

**Comment by rntz** [comment]
Hm, it is true that this lets a PR stay open indefinitely. That shouldn't be too hard to fix. I'm going to be busy soon, so maybe I'll try fixing it later today or tomorrow.

**Comment by rdancer** [comment]
@biggerfisch A deadline by which votes are to be cast is vital. Not voting *for* an issue is a vote in its own right.

**Comment by drocta** [comment]
:-1: I agree, votes should default to failing, at least until there is a proper self test before restarting. Even then there definitely should be a max time period for a PR to stay open.

**Comment by erasmospunk** [comment]
:-1: 
I like the negative supermajority but the pulls should close after a certain amount of time.

**Comment by jvt** [comment]
:-1:

**Comment by drusepth** [comment]
:+1:

**Comment by hintss** [comment]
:-1:

**Comment by nsporillo** [comment]
:-1:

**Comment by sparky222b** [comment]
For reasons above, I, the originator of the supermajority feature, vote :-1:. Per typical political interpretation, a supermajority requires X% for a vote to succeed; however failure is achieved exclusively through failure to secure a supermajority before either exhausting all votes, or reaching a timeout. In our case,  only the latter applies. 

So really this fix violates what a supermajority is.

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 821019b0ebbb195eb61abeefeec2df93052c467d

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed.

----
**Tallies:**
:+1:: 5 (41.6%) 
:-1:: 7 (58.3%)

These users aren't stargazers, so their votes were not counted: 
 * @sparky222b

**Pull request closed without merging**
