### PR TITLE
Scheme query: add history and not crashing so much

### PR DESCRIPTION
**Pull request by dbpokorny**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 94923cabec48761fc689138beed871aae2eb8b13

**Comment by dbpokorny** [comment]
This is a re-roll of https://github.com/botwillacceptanything/botwillacceptanything/pull/375

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: Still want to see what this does :grinning:

**Comment by dbpokorny** [comment]
@spenserJ it teaches scheme

**Comment by shalecraig** [comment]
:+1: why not scheme.

**Comment by SpenserJ** [comment]
@dbpokorny And it is run via `node lib/scheme/query.js`?

**Comment by dbpokorny** [comment]
It can go on the /scheme http endpoint as well, something like http://www.biwascheme.org/demo/pictlang.html

**Comment by OLef1air** [comment]
:+1:

**Comment by Prior99** [comment]
:+1: what is this

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=9jq"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (100%)
:-1:: 0 (0%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
