### PR TITLE
Use markdown for voting ended comment. (updated)

### PR DESCRIPTION
**Pull request by timweightman**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 e3df13ec77819682f20fff6fc31cbef126417a70

**Comment by samis** [comment]
Good use of templating. :+1:

**Comment by avdg** [comment]
:+1:

**Comment by timweightman** [comment]
Thanks @samis!

**Comment by dos1** [comment]
:+1:

**Comment by SpenserJ** [comment]
Why Markdown instead of Handlebars, like we have in the rest of the site?

**Comment by dos1** [comment]
It's actually just a misnamed PR. Markdown isn't a templating system.

**Comment by wsterzik** [comment]
:+1: 

> :monkey: @wsterzik, we can't count your vote because you must :star:star the repository.
> If you want your vote to count
> - :star:star the repository
> - Wait for **3** minute(s)
> - Remove this message (including the :monkey:`:monkey:`), or post a new vote.

**Comment by dbpokorny** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=9e8"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @coveralls

**Pull request merged**
