### PR TITLE
Fix mocha reporter

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* dcd1f486a1de56c6ec32010a0b913db9baffe118

**Comment by avdg** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by dos1** [comment]
It's not fixing - it's changing the reporter from awesome one to boring one. Boo! :-1:

**Comment by korczis** [comment]
@dos1 From non-readable one (talking about travis) to readable one

**Comment by pandzieciol** [comment]
:-1:

**Comment by dos1** [comment]
Then change the reporter for travis. It doesn't have to use the same reporter as humans do.

**Comment by korczis** [comment]
@dos1 After we will have support for environment config merging

**Comment by samis** [comment]
:+1: If we can have an option to use the 'nyan' one in a config later

**Comment by SpenserJ** [comment]
I've added customizable reporting to my upcoming PR for adding additional tests.

**Comment by korczis** [comment]
@SpenserJ Perfect, I can not wait.

**Comment by dbpokorny** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTg2NTIyMg"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

**Pull request merged**
