### PR TITLE
Add nginx config

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* c847d844ea937947208de1dcd700874e2faafbeb

**Comment by AlphaT3ch** [comment]
:-1: Not needed on all the developer's systems... This is only needed on @mappum's

**Comment by AlphaT3ch** [comment]
Here's an example redirect in HTML:
<meta HTTP-EQUIV="REFRESH" content="0; url=http://example.com/">

**Comment by korczis** [comment]
AlphaT3ch: You do not have to run/use it. But it is better if everything related to this project will be in this repo.

**Comment by korczis** [comment]
@AlphaT3ch: It can be used in the case when bot crashes to access logs for read only purposes ...

**Comment by AlphaT3ch** [comment]
@korczis: We may be able to just use another node.js web server running as root. Here's the html:
'<meta HTTP-EQUIV="REFRESH" content="0; url=http://www.yourdomain.com/">'

**Comment by korczis** [comment]
@AlphaT3ch IMHO it is better to have running nginx managed by OS rather than maintain and monitor two nodejs apps

**Comment by AlphaT3ch** [comment]
@korczis: Okay, we could also feed that html into a page in ngnix too :+1:

**Comment by SpenserJ** [comment]
:+1: Looks good to me. I prefer the idea of running Nginx to proxy it, than managing another Node app for now.

**Comment by AlphaT3ch** [comment]
Actually, using the proxy, we can also check if it is connecting from 127.0.0.1 or somewhere else. This could tell us if they were connecting on port 80 or port 3000 now if we wanted different homepages or something, we could

**Comment by korczis** [comment]
@AlphaT3ch I think there are also another adventages - like we can have jsdoc served from this, it can handle/loadbalance cluster of nodejs apps (plays well with forever). We can also deploy another "emergency rescue app" to redeploy specific git sha, etc ...

**Comment by korczis** [comment]
@AlphaT3ch Also we can set up the page for the time when the app is restarted, etc ...

**Comment by dbpokorny** [comment]
:+1:

**Comment by Petah** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by pandzieciol** [comment]
:-1:

**Comment by dos1** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=4aq"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

**Pull request merged**
