### PR TITLE
Voting cycle draft 1

### PR DESCRIPTION
**Pull request by dbpokorny**
Changes voting from a 24/7 ordeal to a periodic activity

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 369405ac327a960505bc270ef889d448ff8e6777

**Comment by dbpokorny** [comment]
gah spellcheck

**Comment by plor** [comment]
:-1:

**Comment by PurHur** [comment]
:-1:

**Comment by albertorestifo** [comment]
:-1:

**Comment by samis** [comment]
:-1:

**Pull request closed without merging**
