### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ehabit**
Corrected project license.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* c3cd4bb0ec5970d02e2e60614adeede6329ad475

**Comment by mappum** [comment]
The license is meant to be tongue-in-cheek, with a touch of rebelliousness.

:-1:

**Comment by thenightwassave** [comment]
:-1:

**Comment by rickardnorlander** [comment]
:-1: Agree in principle. Would vote for a serious amend

**Comment by generalhenry** [comment]
:-1:

**Comment by bradleybuda** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

**Pull request closed without merging**
