### PR TITLE
Enable voting strategy to be changed

### PR DESCRIPTION
**Pull request by thenightwassave**
This sets up the groundwork to enable something other than majority vote to be required for a vote to pass. 

I'd like to see changes involving voting.js require a 2/3rd's vote to pass. This can be debated in a different PR if needed.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 899128318674d2e10696dc16298cfe4b40610fd3

**Comment by runvnc** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by mgberlin** [comment]
:+1:

**Comment by ChristianGaertner** [comment]
:+1:

**Comment by mattlock12** [comment]
:+1:

**Comment by jahqueel** [comment]
:+1:

**Comment by mappum** [comment]
SGTM :+1:

**Comment by ilyanep** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by generalhenry** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
