### PR TITLE
Non-stargazers make monkey votes.

### PR DESCRIPTION
**Pull request by timweightman**
Vote comments that contain any of the monkey emojis will not be counted.

Monkey emojis are:
- :monkey:`:monkey:`
- :monkey_face:`:monkey_face:`
- :see_no_evil:`:see_no_evil:`
- :hear_no_evil:`:hear_no_evil:`
- :speak_no_evil:`:speak_no_evil:`

It is important that we are able to distinuguish between non-stargazer votes, and real votes.
In the event that a non-stargazer makes a vote, their comment will automatically have the following message appended to the bottom of the vote comment:

> :monkey: @timweightman, we can't count your vote because you must :star:star the repository.
> If you want your vote to count
> - :star:star the repository
> - Wait for **3** minute(s)
> - Remove this message (including the :monkey:`:monkey:`), or post a new vote.

The user name is taken from the vote comment itself, and number of minutes to wait is based on the cached stargazer polling interval.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 75beeb0d6e1fca0c2fa9e2781cf70ecd0a8ade42

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by shalecraig** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by PurHur** [comment]
:+1:

**Comment by Prior99** [comment]
:+1:

**Comment by sjparkinson** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=4a4"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Pull request merged**
