### PR TITLE
Have bot check for unusable and malicious code in pull requests.

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Have bot check for unusable and malicious code in pull requests.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 8f8ac94c61d9e1d74ecfac0b69f90e67c2068b6c

**Comment by mappum** [comment]
Easier said than done, but that's definitely something we want. :+1:

**Comment by fallenby** [comment]
:+1:

**Comment by dazoe** [comment]
Agreed :+1:

**Comment by AlphaT3ch** [comment]
@mappum Can you vote as yourself? :+1:

**Comment by splix** [comment]
:+1:

**Comment by RutZap** [comment]
:+1:

**Comment by erkinalp** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7sr"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @fallenby
 * @splix

**Pull request merged**
