### PR TITLE
Voting is code review; don't let the author vote

### PR DESCRIPTION
**Pull request by jahqueel**

### CODE REVIEW

**Comment by thenightwassave** [comment]
:+1:

**Comment by generalhenry** [comment]
:+1:

**Comment by JWesorick** [comment]
:+1:

**Comment by shalecraig** [comment]
:+1:

**Comment by mb-dev** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by cgag** [comment]
:+1:

**Comment by bbrks** [comment]
:+1:

**Comment by RyanMilb** [comment]
(+1)

**Comment by dos1** [comment]
:-1:

**Comment by zenweasel** [comment]
:+1:

**Comment by fcoury** [comment]
:+1:

**Comment by Simon-Coetzee** [comment]
:+1:

**Comment by MasterDurron** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* fa9e1bb0dc3dbd812f264078134c189edd83d1a5

**Comment by OLef1air** [comment]
:+1:

**Comment by haldean** [comment]
:+1:

**Comment by peterkeen** [comment]
:+1:

**Comment by zenweasel** [comment]
:+1:

**Comment by dlmccoy** [comment]
:+1:

**Comment by mszaro** [comment]
:+1:

**Comment by jgod** [comment]
:thumb:

**Comment by jgod** [comment]
:+1:

**Comment by jrgifford** [comment]
:+1:

**Comment by frederickfogerty** [comment]
:+1:

**Comment by neofreko** [comment]
:+1:

**Comment by jish** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Comment by dos1** [comment]
Hmm. Was there a change?

**Comment by jahqueel** [comment]
There was no change. The bot compares the HEAD of the pull request against the last word in its own comment, and I don't see a difference.

**Pull request closed without merging**
