### PR TITLE
Needs more rainbows and ponys! Your arguments are invalid. Merge conflict resolved.

### PR DESCRIPTION
**Pull request by Prior99**
This is a new pull request resolving the mergeconflict from PR #324 which already passed voting.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 8748eae9320ade343bbf986f9c5b595854c5d911

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by Prior99** [comment]
:+1:

**Comment by Prior99** [comment]
@Moerrrlin please comment : +1 : instead of +1 so it can be counted as a vote.

**Comment by JimAllanson** [comment]
:+1:

**Comment by hiliev** [comment]
:+1:

**Comment by JGaudette** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by SpenserJ** [comment]
:-1:

**Comment by bigsergey** [comment]
:+1:

**Comment by Prior99** [comment]
@JGaudette please star this repository in order to have your vote psasing.

**Comment by JGaudette** [comment]
done!

**Comment by pandzieciol** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=3ra"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (87.5%) 
:-1:: 1 (12.5%)

These users aren't stargazers, so their votes were not counted: 
 * @botwillacceptanything
 * @botwillacceptanything

**Pull request merged**
