### PR TITLE
Fix broken conversationsystem for muting the bot

### PR DESCRIPTION
**Pull request by Prior99**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 8d0c191d0a373ec725f576f2dc690b046d63c18a

**Comment by dos1** [comment]
get lost @coveralls 
:+1:

**Comment by shalecraig** [comment]
Failing coveralls? ruh roh.

:+1:

**Comment by shalecraig** [comment]
Actually, :-1: 

* Please remove `MOOD_THRESHOLD` if it's no longer used.
* Please remove `initiateNeutralConversation` if it's no longer used.
* Please use both `mute()` and `unmute()`, or `emit("mute")` and `emit("unmute")`. Mixing and matching both makes it hard to see what's actually going on, and introduces the opportunity for you to forget to update things.

**Comment by dbpokorny** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=18d"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (85.7%)
:-1:: 1 (14.2%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
