### PR TITLE
Idea for using bot code for other projects.

### PR DESCRIPTION
**Pull request by collin**
If the bot is good for running the bot project, maybe it's good for running other projects?

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* c3023c36fda8346db874df6d51b16c373e959e4b

**Comment by avdg** [comment]
This pr will pass the travis test, congratz

**Comment by mappum** [comment]
:+1:

**Comment by dos1** [comment]
#133 has been reverted. Is it safe to merge this?

**Comment by CptnBrittish** [comment]
:+1:  Looking at #133 it appears mappum is the owner of this repository and is okay with this version of the pull request so I would assume it is safe

**Comment by pandzieciol** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=afr"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 4 (80%) 
:-1:: 1 (20%)

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Pull request closed without merging**
