### PR TITLE
Idea: Propose to add a simple merge conflict solver for text files

### PR DESCRIPTION
**Pull request by avdg**
Closing PR's because of simple merge conflicts are bothersome.

### CODE REVIEW

**Comment by dos1** [comment]
:+1:

**Comment by JacobEdelman** [comment]
:+1:

**Comment by berezovskyi** [comment]
:+1:

**Comment by r04r** [comment]
:-1: Doesn't seem practical in relation to the github api

**Comment by avdg** [comment]
In current state it's an idea, details and implementation still needs a different vote.

**Comment by botwillacceptanything** [comment]
#### :ballotbox: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* cfcebee68a51294b73c77ed9fd91b3845785b62e

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by mappum** [comment]
I'm not a fan of the PR that added that ^

**Comment by mappum** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTk3OTA3NQ"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 4 (80%) 
:-1:: 1 (20%)

**Pull request merged**
