### PR TITLE
Definition of Done V2

### PR DESCRIPTION
**Pull request by SpenserJ**
The bot would like to request that we all try to meet a few conditions to keep the code cleaner. I think you'll like how its worded.

Brony Power

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* eba82c27be4633d88d16b6519d1d5ad65f16c23e

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by Stary2001** [comment]
:-1:

**Comment by dos1** [comment]
WE DON'T NEED NO D-O-D

HEY, SPENSER, LEAVE US BOTS ALONE

DUM DUM DUMDUM DUM DUM DUDUM DUM

:-1:

**Comment by samis** [comment]
While I disagree with the idea of mandatory  restrictions on PRs, that brony definition is dammed hilarious.

**Comment by SpenserJ** [comment]
It isn't a mandatory restriction either. If you want to write a good PR, follow the steps, if you don't care, just try not to break the bot.

**Comment by dos1** [comment]
It's pretty nice, yeah, but I miss the joke of why "brony" is there though. Are you making fun of us? :crying_cat_face:

**Comment by samis** [comment]
In that case then, :+1: - This strikes the balance between stability and allowing for things that aren't necessarily 'useful' or 'scientific'

**Comment by korczis** [comment]
:+1:

**Comment by SpenserJ** [comment]
Ever since the MLP images started going up, the amount of functional improvements has significantly declined. The bot must have detected a correlation, and erroneously assumed causation.

**Comment by korczis** [comment]
@SpenserJ I agree

**Comment by samis** [comment]
well, 'Friendship is magic' and friendship turns to be more fun than serious work / productivity. Not that either is bad, just my view of the phrase.

**Comment by dos1** [comment]
Hmm, the bot must operate on some strange set of data then. After all, people pushing those PRs haven't been breaking the bot that much when compared to some other people, plus it wasn't really a lot of those PRs either (just two?)

I rather noticed that amount of fun PRs declined since the very beginning, which worries me, cause that was the best part of this project! :v:

**Comment by pandzieciol** [comment]
:-1:

**Comment by SpenserJ** [comment]
I don't think fun and work/productivity are exclusives. I find it quite fun to write productive PRs, and some people find it fun to add images and marquees. Why not have both, while still trying to keep any features that we do write clean? This doesn't force us do to anything different from what is already happening, but it does make a request to ensure we're not changing code without testing, and keeping the project clean.

**Comment by SpenserJ** [comment]
@dos1 @Stary2001 @pandzieciol What changes to this would satisfy you enough to accept it?

**Comment by dbpokorny** [comment]
:+1: it is time for something like this, and this is a good beginning. This is going to be helpful to people who are just becoming aware of BWAA. The tone is friendly, it has humor, the writing is excellent, and it projects a positive atmosphere. I'd prefer the use of "damn" removed since this one of the most public documents in the entire BWAA project, but this is just a minor quibble.

dos1: please consider writing a http://en.wikipedia.org/wiki/Dissenting_opinion stating your objections so the other contributors have a better idea of what the main faults of the DoD document are. If you can open up a PR that contains your commentary / critique (http://en.wikipedia.org/wiki/Criticism) and we can put that in as well so that future BWAA users don't have to read old comment threads on github to understand what BWAA is about. Your protest has been noted; please express yourself not only for posterity but also to enlighten the other contributors.

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 5 (62.5%) 
:-1:: 3 (37.5%)

**Pull request closed without merging**
