### PR TITLE
Add idea for self-evolving bot

### PR DESCRIPTION
**Pull request by pmalouin**

### CODE REVIEW

**Comment by OLef1air** [comment]
:-1:

**Comment by JustAPerson** [comment]
:-1:

**Comment by karolba** [comment]
:+1:
And test for no staring.

**Comment by mszaro** [comment]
:-1:

**Comment by chrismeller** [comment]
:-1:

**Comment by Xandaros** [comment]
Great ide... no.
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

**Pull request closed without merging**
