### PR TITLE
Upgraded Environment Configurations

### PR DESCRIPTION
**Pull request by SpenserJ**
This will improve the reliability and flexibility of environment-based configurations. If a configuration already exists, it is moved to the new location. If it doesn't exist, the template will be used to create one. By default, the BUILD_ENVIRONMENT is 'development', but can be overridden by running `BUILD_ENVIRONMENT=whatever node main.js`.

One of the more important improvements is a flag for whether to sync the repo to the latest version, which prevents the painful experience of all of your changes being wiped out with every run. This is set by default in the production environment, and you can set it by adding `sync_latest: true` in your code. This does not disable the syncing the repository when github.pull_request.merged is fired, so that you can still test merges in your forks.

## IRC Support

The IRC host has been relocated to your config, and is now customizable. If your bot was configured to connect to IRC, you will have to add `irc: { host: 'irc.freenode.net' }}` to your `configs/custom.js`

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 45c861fb9d7931fe65f83f4a78a20f3751bc8798

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by KyleDavidE** [comment]
[+1] for fixing the build.

**Comment by KyleDavidE** [comment]
:+1: build is passing.

**Comment by samis** [comment]
:+1: Build is passing. Good job.

**Comment by dbpokorny** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by Prior99** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7bd"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Pull request merged**
