### PR TITLE
Less votes means more fun

### PR DESCRIPTION
**Pull request by Blecki**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **10** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 83020cada3117194796ea78aef5f571528e9b8dc

**Comment by Blecki** [comment]
:+1:

**Comment by mappum** [comment]
:+1: Help fix the limited participation problem by upvoting this on Hacker News (you'll have to check the "New" page, I can't link to it or the upvotes won't count). :smile:

**Comment by liamdon** [comment]
:+1:

**Comment by feliperezende** [comment]
:+1:

**Comment by Emily** [comment]
:+1:

**Comment by galdosd** [comment]
:+1:

**Comment by jeffstephens** [comment]
:+1:

**Comment by mappum** [comment]
3 more votes to go!

**Comment by jamescostian** [comment]
:+1:

**Comment by andreimarcu** [comment]
:+1:

**Comment by lukeb-uk** [comment]
:+1:

**Comment by venantius** [comment]
:+1:

**Comment by stevencorona** [comment]
:+1:

**Comment by bsudekum** [comment]
:+1:

**Comment by tom-james-watson** [comment]
:+1:

**Comment by apenney** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

----
**Tallies:**
:+1:: 10 (100%) 
:-1:: 0 (0%)

**Pull request merged**
