### PR TITLE
Awesome Song!

### PR DESCRIPTION
**Pull request by FangedTerror802**
Add the best background music ever to the site! (It actually doesn't slow anything down too!)

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 a738d6d37282af36ab84de484312d095bc6385bf

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by timweightman** [comment]
:-1: 
I don't believe that bots appreciate music as we humans do.
I also think that bot finds the rainbow / pink monstrosity that is its current web presence to be utterly confusing.
Bot most likely cares only of conveying its message and informing site viewers. We should simplify the UI/UX to be more bot-like.

**Comment by SpenserJ** [comment]
:-1: I agree with @timweightman. The interface is already polluted enough as it is, and I'd rather do away with the noise, and get back to just the bare statistics. Hell, I think a true interface for the bot should be JSON APIs, and everyone can build their own interfaces. Could be a neat feature to have the bot manage a separate repository.

**Comment by Prior99** [comment]
:+1: moarrrr bullshit

**Comment by korczis** [comment]
:-1:

**Comment by dos1** [comment]
I can see that this project is under a hostile takeover from people that don't understand it.

:+1:

**Comment by samis** [comment]
:-1:
Make it not autoplay and I will upvote it. Autoplaying website music is hell.

**Comment by dos1** [comment]
I agree, though not enough to downvote it :+1:

**Comment by samis** [comment]
Fair point. :+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=bgr"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (66.6%) 
:-1:: 3 (33.3%)

These users aren't stargazers, so their votes were not counted: 
 * @coveralls

**Pull request merged**
