### PR TITLE
Added IRC channel to README

### PR DESCRIPTION
**Pull request by mappum**
I created an IRC channel, #botwillacceptanything on Freenode.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 67209bc07483f4f920b4010be5239302e74687c3

**Comment by OLef1air** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by thmas** [comment]
:+1:

**Comment by satyarth** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by songgao** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
