### PR TITLE
Improved testing

### PR DESCRIPTION
**Pull request by SpenserJ**
Add tests for `lib/integrations/irc.js` and `lib/integrations/twitter.js`, and set up customizable test reporter via `config.test_reporter`

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 45ccaedfcac81e4427b51028bb631c4879db8b7c

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by SpenserJ** [comment]
A failing test is always a good sign when pushing new tests xD
I'll do a PR when I get home to add a default config.js, unless @korczis has some work done for environmental config loading.

**Comment by plor** [comment]
:-1:

**Comment by SpenserJ** [comment]
@plor Why the down vote?

**Comment by korczis** [comment]
:+1:

**Comment by korczis** [comment]
@SpenserJ: I am not working on this.

**Comment by korczis** [comment]
I mean on configs

**Comment by thenightwassave** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by shalecraig** [comment]
:-1: since this has failing tests. Please re-comment when you re-push

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=aqn"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

**Pull request merged**
