### PR TITLE
Fixed Author Name

### PR DESCRIPTION
**Pull request by jgod**

### CODE REVIEW

**Comment by jgod** [comment]
:+1:

**Comment by karolba** [comment]
:+1:

**Comment by fiveminuteargument** [comment]
:+1:

**Comment by ClintLiddick** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by cgag** [comment]
:-1:

**Comment by vitorarins** [comment]
:+1:

**Comment by rdancer** [comment]
:+1:

**Comment by jgeewax** [comment]
:+1:

**Comment by edadams** [comment]
:+1:

**Comment by thmas** [comment]
:+1:

**Comment by hintss** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 0573fda1075aa6537c1b79fb0808b57c27a0c264

**Comment by mappum** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
