### PR TITLE
Let our autonomous bot vote as well!

### PR DESCRIPTION
**Pull request by dos1**
When the voting starts, the bot will perform sentiment analysis to decide whether it likes the PR or not (or maybe is indifferent to it). When it likes the PR, it gives :+1: and when it dislikes it, it gives :-1:.

The bot is supposed to be autonomous after all, isn't it? ;)

The vote made by bot counts just as a standard vote, so the risk of manipulation is minimal (at best you get one free vote) - and it favors PR titles and descriptions that contain positive emotions, so that's not a bad thing IMO ;)

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* f2f1eee694d0da85ab927c65357a29ff0964a5a7

**Comment by SpenserJ** [comment]
Seems like an interesting idea! :+1:

**Comment by zztemp** [comment]
:+1: Support bot rights! In the future we could do a markov matrix to analyze past accepted PRs and have the bot vote if a similar PR was accepted in the past.

**Comment by AlphaT3ch** [comment]
Cool :+1:

**Comment by mappum** [comment]
This sounds fun, but it seems like it will kind of end up being random votes. :-1:

**Comment by rspeer** [comment]
:-1: Worse than random. This sentiment analysis is literally just mapping words to numbers and adding them up.

So make sure to say "Superb" somewhere in your PR, I guess, and don't swear, and you'll get a free vote.

**Comment by zztemp** [comment]
We could up the vote ratio so the bot's vote would have less of an impact.

**Comment by dos1** [comment]
In future I'd like to make scoring somewhat persistent across pull requests, so bad PRs get the bot into worse mood, and good PRs get the bot into better mood - and on bad mood the bot would be more picky, while on good mood it would be more forgiving :+1:

**Comment by avdg** [comment]
There is some tolerance, but I don't think we should play too much with it and keep the voting system transparant.

Though the risk is fairly small, so I could do :+1: and hope that these risks are balanced out later on.

**Comment by jish** [comment]
:-1: 

> "make sure to say "Superb" somewhere in your PR, I guess, and don't swear, and you'll get a free vote."

**Comment by styfle** [comment]
:-1: I like the idea but the algorithm can probably be improved

**Comment by KwarcPL** [comment]
+1

**Comment by haldiraros** [comment]
:+1:

**Comment by pandzieciol** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=6r5"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (66.6%) 
:-1:: 4 (33.3%)

**Pull request merged**
