### PR TITLE
Make a p2p bot network

### PR DESCRIPTION
**Pull request by erasmospunk**

### CODE REVIEW

**Comment by r04r** [comment]
:-1:

**Comment by erasmospunk** [comment]
Changed the idea wording.

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 194cfefe6cf086e8612e14867275cddb6db453ae

**Comment by mappum** [comment]
:+1: Nice thinking. What would the bots communicate about?

**Comment by jbenet** [comment]
:+1:

**Comment by drocta** [comment]
:+1: It seems it would be useful for one autonomous organization to be able to communicate with another. Might allow multisig like things such as computing on shared secrets (though for multiplication of shared secrets would need to be able to connect to each of the other bots/organizations in a way the other organizations/bots couldn't see)

**Comment by erasmospunk** [comment]
They could monitor the status of their peers to decide if they should merge a specific commit to their own repo. A parameter could be introduced to make a bot more or less eager to try new code.

For instance the bot that controls this repo and counts the votes should be the most conservative and not merge immediately while other bots could take risks. At first it should be just health/status data, later it can be enhanced.

**Comment by jvt** [comment]
I'm 90% sure this is how Skynet starts... Although, that'd be pretty cool to see so :+1:

**Comment by phase** [comment]
:+1:

**Comment by nitrix** [comment]
:+1:

**Comment by drusepth** [comment]
Implement it and I'll turn my :-1: upside down.

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by nburns** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=a3g"></a>
:+1: The vote passed, this PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (77.7%) 
:-1:: 2 (22.2%)

These users aren't stargazers, so their votes were not counted: 
 * @nburns

**Pull request closed without merging**
