### PR TITLE
Server side templates++

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* f1ca833f9a942da1cc283f9a12586669fcef30c4

**Comment by avdg** [comment]
related to #234?

**Comment by Petah** [comment]
:+1:

**Comment by dos1** [comment]
use mustache, or change other templates to use handlebars :-1:

**Comment by dos1** [comment]
also, please make sure that everything - including webhooks! - works properly

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by pandzieciol** [comment]
:-1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by SpenserJ** [comment]
:-1: PR was altered, and is too large to easily review and test.

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 5 (62.5%) 
:-1:: 3 (37.5%)

**Pull request closed without merging**
