### PR TITLE
Remove whitespace from EOLs

### PR DESCRIPTION
**Pull request by shalecraig**
Remove whitespace from the end of a line.

Hopefully this won't have a merge conflict.

### CODE REVIEW

**Comment by ravinggenius** [comment]
:+1:

**Comment by halfjuice** [comment]
+1

**Comment by halfjuice** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by generalhenry** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* aefb443907f59397e04c5ddc1f2e61321a2d9357

**Comment by OLef1air** [comment]
:+1:

**Comment by blister** [comment]
:+1:

**Comment by edunham** [comment]
:+1:

**Comment by frederickfogerty** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
