### PR TITLE
Add a /diff endpoint, a simple demo to exercise gift diff tools on last ...

### PR DESCRIPTION
**Pull request by dbpokorny**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 566ed0950ccad29fbca6313c171b3b4c4f552839

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by SamsPepper1** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by SpenserJ** [comment]
This separates the additions and removals, which means they all lose context. I don't think using `sanitizeAllHtml()` on the diff lines is a good call either, since it means we'll never see the HTML that is added or removed. :-1: at this point

**Comment by dbpokorny** [comment]
SpenserJ that's fine, but the reason I wrote it that way is to separate the additions and subtractions for subsequent machine parsing. I'd like to add a commit hook to a file in a subdirectory of projects that only allows certain types of additions to itself. It is just a diagnostic tool for that subsequent project.

**Comment by AlphaT3ch** [comment]
:+1: I personally believe that if you want to do your own thing in a different endpoint, you should be able to. Nice!

**Comment by dos1** [comment]
:+1:

**Comment by pandzieciol** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7nb"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (87.5%) 
:-1:: 1 (12.5%)

**Pull request merged**
