### PR TITLE
Instead of being rude, we should ignore users.

### PR DESCRIPTION
**Pull request by shalecraig**
I don't like being called stuff like this whenever I join the channel.

`XYZ is a kid. I hope you go to hospital and never come back! XYZ is a fucking retard.`

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 643722bfc439da6bcdbbf8fd8781fd57635cff19

**Comment by samis** [comment]
:-1: I like this aspect of the bot - it makes it more realistic. I wouldn't object to a PR changing the messages or structure however provided it retains a negative set of comments.

**Comment by thenightwassave** [comment]
:+1:

I originally down voted the original PR for this reason.

Even though I do have a 9....

**Comment by PurHur** [comment]
:-1: Your solution is not the yellow from the egg.

**Comment by shalecraig** [comment]
@samis: I don't think being _this_ rude is realistic. Or at least I hope it isn't representative of our IRC channel.
@PurHur: huh

**Comment by samis** [comment]
@samis It's more realistic than the bot saying only ever nice things. The comments do likely need a tweak though to make them less...evil or harsh.

**Comment by dbpokorny** [comment]
:-1: In the future, the bot can insult the developers based on the extent to which the PRs the dev requests pass jshint

**Comment by SpenserJ** [comment]
:-1:

@dbpokorny I would upvote that in a heartbeat

**Comment by RyanMilb** [comment]
:+1:

**Comment by avdg** [comment]
:+1: Don't let negativity kill us

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 4 (50%) 
:-1:: 4 (50%)

**Comment by avdg** [comment]
Pls reroll

**Comment by samis** [comment]
@avdg I believe that a good idea floated in the IRC channel - respond to user dynmaically based on how they act. E.g bot is nice to nice people, bot is not nice to not nice people.

**Comment by avdg** [comment]
That would only bring them to isolation... It's not humain

**Pull request closed without merging**
