### PR TITLE
Dart => Go Compiler

### PR DESCRIPTION
**Pull request by kaendfinger**

### CODE REVIEW

**Comment by drocta** [comment]
idk, seems like a big thing to be the first thing to be attempted with the otherprojects folder...
not going to vote against it though. Might vote for it, but am not yet.

**Comment by drusepth** [comment]
Make it happen and I'll turn my :-1: rightside up

**Comment by kaendfinger** [comment]
@drusepth Would a transpiler be enough for a vote xD

**Comment by drusepth** [comment]
@kaendfinger if it actually does something, yes :)

**Comment by kaendfinger** [comment]
@drusepth I'll implement just basics, and then we can go from there

**Comment by drocta** [comment]
@drusepth If you are going to say that to literally every addition to a text file or similar why don't you submit a change to delete ideas.md? I mean I would vote against it, but if the majority actually agrees with you on the "no changes which just specify an idea" it would be much more efficient than you saying that each time. 
:+1:  because it looks like this is maybe going to go somewhere, and it would be nice to see the otherprojects folder working.

**Comment by drusepth** [comment]
@drocta I commented that on two pull requests. I've voted on way more.

**Comment by drocta** [comment]
sorry.

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 04e182ea421908404ae21e4b6dfa253230201955

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 04e182ea421908404ae21e4b6dfa253230201955

**Comment by kaendfinger** [comment]
:+1:

**Comment by GlossFish** [comment]
:+1:

**Comment by ClearlyAwesome** [comment]
:=1:

**Comment by ClearlyAwesome** [comment]
:+1:

**Comment by ClearlyAwesome** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=9u"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 4 (80%) 
:-1:: 1 (20%)

These users aren't stargazers, so their votes were not counted: 
 * @GlossFish

**Pull request merged**
