### PR TITLE
Accept *Anything*

### PR DESCRIPTION
**Pull request by mayli**
:+1:

### CODE REVIEW

**Comment by jbwyme** [comment]
:-1:

**Comment by fiveminuteargument** [comment]
:-1:

**Comment by PTaylour** [comment]
:-1:

**Comment by awilliamson** [comment]
:+1:

**Comment by OLef1air** [comment]
:-1:

**Comment by ClintLiddick** [comment]
:-1:

**Comment by jvt** [comment]
:-1:

**Comment by asbestoso** [comment]
:+1:

**Comment by cgag** [comment]
:+1:

**Comment by mayli** [comment]
Come on guys, we need this patch for more fun! :v:

**Comment by JWesorick** [comment]
:-1:

**Comment by rdancer** [comment]
:-1:

**Comment by awilliamson** [comment]
If the bot accepts anything, it can then surely immediately rewrite the ruling for PR acceptance. This would make this experiment much more interesting.

**Comment by mszaro** [comment]
:-1:

**Comment by mayli** [comment]
I need more spammers to finishes this :cry: 
`// index votes by username so we only count 1 vote per person`

**Comment by thmas** [comment]
:-1:

**Comment by flipstewart** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

**Comment by mayli** [comment]
Someone should try it again.

**Pull request closed without merging**
