### PR TITLE
Switch to #anythingbot, where we can give the bot op status in IRC

### PR DESCRIPTION
**Pull request by SpenserJ**
Switching to a new channel with op has been discussed in IRC and in #423.

The primary reason we would want to switch channels is to open the doors to more IRC functionality in the bot in the future. This could be voicing users that have submitted a merged PR, adjusting the topic to match the current vote status, or kicking users automatically if they meet a "bad user" criteria built into the bot. Changing the topic could be done right now, however we run the risk of anyone changing the title.

One of the larger reasons not to switch is a concern of losing users. The best ways to mitigate this would be to invite all of the current users to a new channel, switch all text on the bot to point to the new channel, change the topic to point to the new channel, and potentially set up a basic IRC bot to remind users about the new channel.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 dcb4175ad79704e1fc095d2a4f2287ccc6fa5ae1

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by r04r** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by shalecraig** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=3ma"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (85.7%)
:-1:: 1 (14.2%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
