### PR TITLE
Beautiful Webpage Design

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Not to be stuck-up or anything, but these are pretty-dang beautiful. All the pages are now decked-out with HTML and CSS. The main commits page was moved to /commits to make room for a homepage. It also has a 404 Page detection.

### CODE REVIEW

**Comment by dbpokorny** [comment]
:+1:

**Comment by matter123** [comment]
:+1:

**Comment by mwerner** [comment]
:+1: This is good, if we do anymore we'll probably want to get some sort of templating engine up in here

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 6d4500c86ccbedff13511f0e88e4537113fade3d

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by duizendnegen** [comment]
:+1:

**Comment by korczis** [comment]
:+1:

**Comment by akkatracker** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by SpenserJ** [comment]
Why has all of webserver.js changed? It doesn't show what you actually changed there.

**Comment by dos1** [comment]
This PR went bonkers :-1:

**Comment by jedahan** [comment]
:-1: for the same reason @SpenserJ mentioned

**Comment by AlphaT3ch** [comment]
Very odd... I added a statistics page is all...

**Comment by generalhenry** [comment]
:-1:

**Comment by mwerner** [comment]
The diff is off because of whitespace, pass `w=1` as a query param to see the real diff:

https://github.com/botwillacceptanything/botwillacceptanything/pull/202/files?w=1

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Comment by AlphaT3ch** [comment]
Oh thanks! @mwerner

**Pull request closed without merging**
