### PR TITLE
Fix template

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 32db719c77d2d5a7f4932fca7a302565838e8d3f

**Comment by dos1** [comment]
:+1:

**Comment by dos1** [comment]
but what about webhooks status?

**Comment by korczis** [comment]
@dos1: what you mean?

**Comment by thenightwassave** [comment]
That endpoint used to be for webhook status. Look at the comment right above the function. Now nothing is being reported on webhook status.

**Comment by korczis** [comment]
Oh, I see now. I have to pass this info from [statistics route](https://github.com/botwillacceptanything/botwillacceptanything/blob/master/lib/routes/statistics.js). 

Feel free to down-vote this one now ..

**Comment by thenightwassave** [comment]
You originally changed it:

https://github.com/botwillacceptanything/botwillacceptanything/commit/fd7d2c26f2cad52da80df1cea6c006c8746afc41#diff-f14d96251f7653c9a0f9254698a0eccf

You lost the webhook status there.

**Comment by korczis** [comment]
@thenightwassave Thanks. I will fix this soon.

**Comment by SpenserJ** [comment]
:-1: until the fix is out

**Comment by AlphaT3ch** [comment]
:-1:

**Comment by korczis** [comment]
Fixed in #265

**Pull request closed without merging**
