### PR TITLE
Link to standard output.

### PR DESCRIPTION
**Pull request by jish**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* eb1a392098c7a609e1755bfeba658b4abf582fe3

**Comment by dos1** [comment]
:+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by SpenserJ** [comment]
:-1: That will generate invalid HTML.

```html
<ul><p>Link</p><li>
```

**Comment by korczis** [comment]
:-1:

**Comment by avdg** [comment]
:-1: due to invalid html (ty @SpenserJ)

**Comment by jish** [comment]
Good catch @SpenserJ 

I knew I should have run it locally before pushing...

But I couldn't get the bot running locally because the call to `repo.sync` is failing, even when I add my GitHub credentials in `config.js` :(

**Comment by SpenserJ** [comment]
@jish I comment out some code that sync is skipped (so that it doesn't revert my changes when running), and trigger the callbacks instead.

**Comment by dos1** [comment]
BTW. This kind of invalid HTML wouldn't prevent it from being displayed properly.

**Comment by SpenserJ** [comment]
True, but if we're running JSLint to keep the JS clean, I don't see why we should output invalid HTML.

**Pull request closed without merging**
