### PR TITLE
Use launcher V2.1

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by avdg** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 7caeaf90c057667a21f7f911485858ebbe91fa32

**Comment by rickardnorlander** [comment]
:+1:

**Comment by mappum** [comment]
How well tested is this? I'm voting on blind faith :/ :+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=l7"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (100%) 
:-1:: 0 (0%)

**Pull request merged**
