### PR TITLE
Proposed an Idea.

### PR DESCRIPTION
**Pull request by QamarWaqar**
Idea about twitch.tv Kappa

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 5923a7efa2adda54fbdf4ad73dae386bee965d82

**Comment by shalecraig** [comment]
We have a twitch stream? The word "twitch" isn't in the repo.

**Comment by SpenserJ** [comment]
Not sure who the broadcaster would be either. Bit of research says Kappa was one of the employees when it was justin.tv, and his picture was turned into an emote. Thats the most I understand

**Comment by shalecraig** [comment]
Ah, found this

http://lazythunk.com/kappa/

**Comment by samis** [comment]
I'm currently neutral on this, but something twitch-related would be a good addition.

**Comment by shalecraig** [comment]
:+1: since it's more or less an issue.

**Comment by samis** [comment]
Might as well :+1: this, seeing as it's just an idea and more ideas are always good.

**Comment by plor** [comment]
:-1: merge conflict :(

**Comment by dbpokorny** [comment]
:+1: I like this idea, please re-roll (the bot will reject and close this PR because of a merge conflict)

**Comment by dos1** [comment]
:-1:

**Comment by shalecraig** [comment]
:-1: now, since the merge conflict

**Comment by Prior99** [comment]
:-1:

**Comment by PurHur** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 3 (37.5%) 
:-1:: 5 (62.5%)

**Pull request closed without merging**
