### PR TITLE
Fix Tweeting from all environments

### PR DESCRIPTION
**Pull request by SpenserJ**
Removing mocks from main.js, as they are only used for testing now

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 6cbd9035d9db92d1fdb9bb843f34e91b009e4e71

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by PurHur** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by Prior99** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by gpersons** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=26j"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (87.5%) 
:-1:: 1 (12.5%)

**Pull request merged**
