### PR TITLE
Karma

### PR DESCRIPTION
**Pull request by shalecraig**
This is about 50% done (no way to see/use the karma), but I wanted to get some feedback.

I'm using sqlite3, since _whatever_.

On a technical level, this is what I want you to think about:

1. I wrote a karma thing that uses the db. I'll pull the db out to its own library if you think that moving it is important.
1. What should karma do? For this PR, can we make that small? Poking in IRC when that happens would be nice.
1. Am I using the `config` correctly? Should I do anything differently?

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 7b90384b0089419aa2c25b96b65567c90025d805

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by Prior99** [comment]
I like the idea of karma and I also like the idea of having a database. I also like sqlite.
But:

 * Please keep SQLite support in a different PR than this
 * Then add Karma
 * Keep the karma in it's own module, do not mix this up with the database as it might be used for other purpsoses

Until then: :-1:

**Comment by PurHur** [comment]
:-1: Thats not in the definition of the 'dod' at all.

**Comment by PurHur** [comment]
But i like the idea of using sqlite... but a little bit more abtract so other people can use the interface...

**Comment by samis** [comment]
:-1:  Karma is a nice idea, but having SQLite added in the same PR feels wrong. For a bit more 'abstract' API perhaps we could consider having a NoSQL database to accompany SQLite? That way you can use both where appropriate.

**Comment by SpenserJ** [comment]
:-1: Agreed, split the DB into a PR, and run through that first. I'd also appreciate if we could set up some sort of schema/update files at some point, so that we can properly version the database and upgrade it easily.

**Comment by PurHur** [comment]
Whats with a public open readable database for the bot? So we can copy the testdata.... and SO OPEN INFORMATION!11Ülf

**Comment by OLef1air** [comment]
:-1:

**Comment by matter123** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 3 (37.5%) 
:-1:: 5 (62.5%)

**Pull request closed without merging**
