### PR TITLE
WebSockets Preview V1

### PR DESCRIPTION
**Pull request by dbpokorny**
This is a preview. I want to go public with websockets while it is still rough around the edges so others can take a crack at it while I clean it up. In an ideal world, all senior devs get a chance to review this before it gets merged. The architecture is intended to be similar to /routes. The example code is from

https://www.npmjs.com/package/ws
https://github.com/websockets/ws

To test, just fire up chrome (haven't got a chance to test firefox yet) open up two windows, go to anythingbot.org:3000/hello (in both windows) start the dev console (on mac: command-option-I) and type 

sayhello()

sayhello('foo')

sayhello('bar',1)

Does anyone know if the bot will do OK by itself when the 'ws' dependency is added to package.json? I had to type 'npm install' again to test on anythingbot.org, but then again I'm not using the full setup.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 aff5eba892e4b6259c7242172f8709079adf1ac1

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by dbpokorny** [comment]
it appears to work in firefox too :D

**Comment by dbpokorny** [comment]
BTW please read the mea culpa on https://github.com/botwillacceptanything/botwillacceptanything/pull/494

**Comment by SpenserJ** [comment]
I think Socket.io would provide a cleaner wrapper for all of this, that would be easier for everyone to understand. That said, the code looks good at a glance, and I like the idea of having websocket support in the bot.

**Comment by dbpokorny** [comment]
@SpenserJ If you want to either (A) code up a PR that uses socket.io instead of ws or (B) code up an abstraction layer that make swapping out the websockets implementation (socket.io or ws) relatively easy, that's fine with me. As we both know, writing code takes a lot of time and energy.

**Comment by dbpokorny** [comment]
I just want to add a data point to the ws vs. socket.io question: while working on ARL (anything request live) I found the "raw.js" node package which is referred by https://github.com/reddit/reddit/wiki/API-Wrappers which has 'ws' as a dependency. This is just a data point; I don't know why Doctor_McKay chose ws over the other options.

**Comment by JeDa** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7r3"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 5 (100%)
:-1:: 0 (0%)

These following 1 voter(s) were not _stargazers_, so their votes were not counted:

- :monkey: @coveralls

*Non-stargazers*: Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
