### PR TITLE
Allow voting until passage

### PR DESCRIPTION
**Pull request by jahqueel**
I'd recommend also merging #15 so that pull requests get closed eventually when they're unmergeable...

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 5f04eda5df734a073dc0ac45ebfc312ef58920c0

**Comment by JWesorick** [comment]
:+1:

**Comment by thenightwassave** [comment]
You still want to leave the comment with the results. Just a:

    if (!passes) {
        closePr(pr, noop);
    }

should work, no?

**Comment by mappum** [comment]
Hmm, that opens up an attack where the PR author gets all their friends to upvote the PR all at once. When PRs on the floor are actively being voted on by everyone, unsafe changes won't make it in.

:-1:

**Comment by ilyanep** [comment]
Agree with @mappum 

:-1:

**Comment by generalhenry** [comment]
:-1:

**Comment by ravinggenius** [comment]
:-1:

**Comment by OLef1air** [comment]
:-1:

**Comment by fiveminuteargument** [comment]
:-1:

**Comment by dequis** [comment]
:-1:

**Comment by mplewis** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

**Pull request closed without merging**
