### PR TITLE
Adding a webserver to display recent commits on :3000

### PR DESCRIPTION
**Pull request by SpenserJ**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 0da306bfbdefc212d5799ca8029a128cc172f149

**Comment by SpenserJ** [comment]
:+1: I figure this is a good jumping off point for some of the HTTP interface ideas in the list.

**Comment by rickardnorlander** [comment]
Cool idea. :-1: since you don't sanitize input.

**Comment by dos1** [comment]
:+1:
I don't think input sanitization is necessary here. The only input here is what already got accepted into git repo.

**Comment by mappum** [comment]
FYI I manually installed express, this would have failed if deployed without installing that. Maybe we can modify `main.js` to run `npm install` each time it merges changes (so we can install things by adding them to `package.json`).

**Comment by SpenserJ** [comment]
@rickardnorlander That would be a good idea. Given that shady looking commit message would be shot down, I wasn't too concerned for the initial version

**Comment by SpenserJ** [comment]
@mappum Shoot, realized it was resetting my changes, but I forgot to readd express to package.json. I like the idea of it automatically running an npm install though. I can reopen it with an update if you'd like.

**Comment by rntz** [comment]
:-1: Just because it was accepted into git repo doesn't mean it's safe HTML, I think.

**Pull request closed without merging**
