### PR TITLE
Replace the greeting with a "real" conversationsystem

### PR DESCRIPTION
**Pull request by Prior99**
Instead of the greeting and liking/disliking of users I implemented a "real" conversationsystem which is easily extendable and reacts to messages the users write into the channel.

Merge conflicts resolved.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 80804fac30d53f6f5556f3131fd4055143ecccc1

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by Prior99** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 80804fac30d53f6f5556f3131fd4055143ecccc1

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by Moerrrlin** [comment]
:+1:

**Comment by PurHur** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: Seems like a witty upgrade

**Comment by OLef1air** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=290"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Pull request merged**
