### PR TITLE
Change the variable 'yeas' to 'yays'

### PR DESCRIPTION
**Pull request by Zarthus**
Currently, votes are done in 'yeas' or 'nays', when honestly 'yays' versus 'nays' sounds so much better.

But does GitHub agree?

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* c3053bc88499e89c3a09ad3c1345cf3c8a4a70e6

**Comment by OLef1air** [comment]
[In the Senate, there is only one way to obtain a recorded vote on a pending question, and it is the roll call vote. The request for the roll call vote is known as the **Yeas and Nays**.](http://en.wikipedia.org/wiki/Recorded_vote) :-1:

**Comment by Blecki** [comment]
:-1:

**Comment by bbonamin** [comment]
:-1:

**Comment by Ravengenocide** [comment]
:-1:

**Comment by davelopware** [comment]
:+1:

**Comment by kblanks** [comment]
I like to say yay or nay, so :+1: to this.

**Comment by RickWong** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 1 (20%) 
:-1:: 4 (80%)

These users aren't stargazers, so their votes were not counted: 
 * @bbonamin
 * @davelopware

**Comment by nyuszika7h** [comment]
What about @kblanks?

**Comment by kblanks** [comment]
> What about @kblanks?

What about me? 0.o

**Comment by nyuszika7h** [comment]
Never mind, I thought your vote wasn't counted, but actually @davelopware's wasn't.

**Pull request closed without merging**
