### PR TITLE
Update ideas.md

### PR DESCRIPTION
**Pull request by shivam-97**

### CODE REVIEW

**Comment by dos1** [comment]
:+1:

**Comment by ghost** [comment]
:thumbs up:

**Comment by ghost** [comment]
Yay

**Comment by jtkaufman737** [comment]
-

**Comment by dbpokorny** [comment]
Well, you can go to anythingbot.org/hello, type "con block", close the window, and it will block the video feed. If repeating the same thing over and over again counts as "reply" then you can say github.com/anythingbot/anythingbot already has the ability to reply.

**Pull request closed without merging**
