### PR TITLE
Notify voters when a change makes voting less effecient.

### PR DESCRIPTION
**Pull request by Blecki**

### CODE REVIEW

**Comment by Blecki** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 24d2eabd97ee07591a105b6489f363d4e1bccf48

**Comment by OLef1air** [comment]
I'd prefer a nicer way of communication between the bot and it's subjects. :-1:

**Comment by roby65** [comment]
:+1:

**Comment by Ravengenocide** [comment]
:+1:

**Comment by defreek** [comment]
:+1:

**Comment by ZeissS** [comment]
:+1:

**Comment by Pezmc** [comment]
:-1:

**Comment by davelopware** [comment]
:+1:

**Comment by kblanks** [comment]
I like the topical usage of the word `git`, :+1:

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Pull request closed without merging**
