### PR TITLE
Bot pays successful contributors with donated Bitcoins 

### PR DESCRIPTION
**Pull request by TimDaub**
Hi,

I hope I did not destroy the formating of `ideas.md` too much.

There is still a big question mark for this idea on how to create the bot's private key.
Because, if we just assign a private key and hardcode it into the source, any donator could just sent his money back, as the bot's key and his key would allow him to sign the multisignatur transaction.

But, I still think there is a way to do it.
One idea I had was that the bot can somehow deterministically create private keys depending on an Issues Github idea + a random salt.

Though the salt should then somehow be disclosed from the public and from the project owner.

So if any Cryptopro (which I'm not btw) has any idea on how to achieve this, then shot!
So I can enhance this PR.

Curious to hear your feedback.

Have a nice day.

### CODE REVIEW

**Comment by awilliamson** [comment]
Who's going to pay for this? Also this entire repo is a social experiment, no real 'good' will be done. Only destruction and subversion. :-1:

**Comment by OLef1air** [comment]
:-1:

**Comment by TimDaub** [comment]
@awilliamson Its not about this project specifically, but about the bots functionality to manage projects autonomously.
Read the PR first, then vote...

**Comment by thmas** [comment]
:-1:

**Comment by AgentME** [comment]
The bot probably has access to a filesystem. Code can be added to make it look for a private key in a specific file, or generate it if necessary.

It would be way cool if there were hosting services with APIs that allowed bots to buy VPSs and pay with bitcoins automatically. Then this bot could use donated money to pay for hosting and manage itself. I'd fork over $20 worth to it to see it go.

**Comment by AgentME** [comment]
The bot could then post its bitcoin address in a github issue or comment somewhere after it generated it.

**Comment by aliakhtar** [comment]
Not interesting. :-1:

**Comment by jvt** [comment]
:-1:

**Comment by Quuxplusone** [comment]
@AgentME's solution (generate the private key on disk, and rely on the voters to reject any attempts to publicize that key) makes sense to me. :+1:
Besides, this is just "ideas.md".

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 2311b64d719e673619d45d00ec0a6d091db6a314

**Comment by aliakhtar** [comment]
Not interesting. :-1:

**Comment by AgentME** [comment]
I really like the idea of making the bot *own* its own bitcoin wallet and do stuff with it as I mentioned, but I'm not a big fan of the exact message in this PR. Incentivizing pull requests to the bot probably complicates things, and I don't really follow the part about integrating the bot into other projects. Instructing people to run their own instances for anything besides testing kind of misses the point IMO.
:-1:

**Comment by rickardnorlander** [comment]
:-1: 
>I really like the idea of making the bot own its own bitcoin wallet and do stuff with it as I mentioned, but I'm not a big fan of the exact message in this PR.
This

**Comment by avdg** [comment]
:-1: Shouldn't even be our problem

**Comment by TimDaub** [comment]
Btw, I think the author intended the bot to be used in other projects as well, therefore he created the `exampleproject` folder...

**Comment by mappum** [comment]
I like this idea a lot, that's the sort of thing I hope this project grows into. :+1:

**Comment by TimDaub** [comment]
I'm going to vote on my own PR, what ya gonna do about it :D :+1:

**Comment by AgentME** [comment]
@TimDaub Oh, I think I get what you're going at now. People would make an instance of the bot pointing to other github repos they own (which may or may not contain the bot itself, doesn't matter), and have the bot manage (probably non-bot-related) pull requests (and payments) to that repo.

I think it's very close to a very cool idea, though I think as designed here it would just make alt-accounts in order to vote up their own nearly-empty PRs to drain the bot's money.

**Comment by TimDaub** [comment]
@AgentME That's exactly what I was imaging. A project that essentially manages itself through the richness of its idea which is essentially specified in the requirements document.

**Comment by mappum** [comment]
@AgentME The alt-account attack could be fixed by changing the voting system. For instance, votes could only count for account created before a certain date.

**Comment by drocta** [comment]
:+1: sounds good to me. A nice bounty system.

**Comment by erasmospunk** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged
The changes in this PR conflict with other changes, so we couldn't automatically merge it.
You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Pull request closed without merging**
