### PR TITLE
Update ideas.md

### PR DESCRIPTION
**Pull request by fiveminuteargument**

### CODE REVIEW

**Comment by OLef1air** [comment]
:+1:

**Comment by jgod** [comment]
:+1:

**Comment by JWesorick** [comment]
:+1:

**Comment by fiveminuteargument** [comment]
:+1:

**Comment by ClintLiddick** [comment]
:+1:

**Comment by thmas** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
