### PR TITLE
wishful thinking change to readme

### PR DESCRIPTION
**Pull request by awwstn**

### CODE REVIEW

**Comment by drocta** [comment]
Heh.

I mean its not accurate so :-1:, but still funny and I appreciated the humor.

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 1d453be71b814feb9651670a28d6ca620a4321d4

**Comment by AlphaT3ch** [comment]
Hah! Funny, but we really need the rate limiting up-rising so :-1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 1d453be71b814feb9651670a28d6ca620a4321d4

**Comment by mappum** [comment]
:-1: Downvoting in favor of this #83

**Comment by dazoe** [comment]
:-1:

**Comment by erkinalp** [comment]
@botwillacceptanything: Who will resolve merge conflicts?

**Comment by kramsee** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 0 (0%) 
:-1:: 5 (100%)

**Pull request closed without merging**
