### PR TITLE
Generate authors, will be shown in WebUI

### PR DESCRIPTION
**Pull request by korczis**
```
tomaskorcak@kx-mac:~/dev/botwillacceptanything$ ./authors.sh
    91	Bot
    30	Tomas Korcak
    29	Spenser Jones
    22	Matt Bell
    12	AlphaTech
    11	Sebastian Krzyszkowiak
     5	Blecki
     4	AlphaT3ch
     4	Rickard Norlander
     4	ᴍᴀᴛᴛ ʙᴇʟʟ
     3	sparky222b
     3	Kenneth Endfinger
     3	Shale Craig
     2	Nomic
     2	Koen Schmeets
     2	nomic-io
     2	Josh Lubaway
     2	Jan Minar
     2	Rob Speer
     2	Bobby Jack
     2	Matthew Werner
     1	Aristid Breitkreuz
     1	Anthony Van de Gejuchte
     1	clay-to-n
     1	gpersons
     1	Chris Silvia
     1	Edward Hotchkiss
     1	David Brooks Pokorny
     1	Eric Ryan Harrison
     1	Gavin Persons
     1	James Costian
     1	Justin Godesky
     1	Luke Heath
     1	Bradley Buda
     1	Mitar
     1	OliverCole
     1	thenightwassave
     1	Sam Stern
tomaskorcak@kx-mac:~/dev/botwillacceptanything$
```

### CODE REVIEW

**Comment by avdg** [comment]
:+1: We will remember them ;-)

**Comment by dos1** [comment]
I'm pretty high, so :+1:

**Comment by jvt** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* e1b0565c9feca95a518364b1da49608c69309beb

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by thenightwassave** [comment]
I feel this makes the bot less of its own. :-1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=1fl"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

**Comment by korczis** [comment]
@thenightwassave explain please ...

**Comment by avdg** [comment]
No worries, the bot will have its own tasks :-)

**Comment by avdg** [comment]
We only need a stable base

**Pull request merged**
