### PR TITLE
Improved vote started text

### PR DESCRIPTION
**Pull request by mappum**
Now that we have webhooks, the comment will be posted right after a PR is posted. I think this header for the "vote started" comment makes things clearer.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 50d1d6a8379d1433784e3c0560dfd6bbfc05e195

**Comment by dos1** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by ben** [comment]
:+1:

**Comment by thenightwassave** [comment]
This text is not longer true. The bot counts votes before the comment is made. The new text makes it sound like those votes do not count.

**Comment by SpenserJ** [comment]
@thenightwassave With webhook support in the bot, it is typically less than a second until the comment is added.

**Comment by rspeer** [comment]
But if the webhook is down, it'll be misleading. :-1:

**Comment by thenightwassave** [comment]
That is only if webhooks are enabled. I thought there was still support for not running webhooks and still polling?

The text is actually being changed back to what it was originally, as seen: https://github.com/mappum/botwillacceptanything/commit/818e501d5495979b35dd8adb8356059347e2e552#diff-bdc898fac6c529f3c63f46860eb810d3

This is pests on irc btw.

**Comment by SpenserJ** [comment]
If the webhook is down/disabled, it should still update within 3 minutes.

**Comment by drsirmrpresidentfathercharles** [comment]
:-1: If votes are casted before the three minute mark, this makes it look like they are not counted.

**Comment by thenightwassave** [comment]
I don't really care too much about this, but this PR alone had three votes before 3 minutes were up.

**Comment by mappum** [comment]
@drsirmrpresidentfathercharles As I said in the PR text, now that we have webhooks that will no longer happen.

**Comment by VeoPVM** [comment]
:-1:

**Comment by AlphaT3ch** [comment]
:+1: Grammar for the win!

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 6 (60%) 
:-1:: 4 (40%)

**Pull request closed without merging**
