### PR TITLE
Add our motto to README

### PR DESCRIPTION
**Pull request by dos1**
https://github.com/botwillacceptanything/botwillacceptanything/pull/274#issuecomment-92526035

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 81a2d9e78f776da0cca003b0a3d04b8a881c7975

**Comment by SpenserJ** [comment]
:+1:

**Comment by SpenserJ** [comment]
I take it this wasn't tested, was it?

**Comment by dbpokorny** [comment]
:+1: will probably break the bot...whatever

**Comment by mappum** [comment]
:-1: Ehh I don't really want things to stay like that, hopefully we can fix this with better automated testing in the future.

**Comment by pandzieciol** [comment]
:+1:

**Comment by avdg** [comment]
:+1: Soon it the bot might have tested itself before I was lazy to test.

**Comment by shalecraig** [comment]
hopefully you tested it - I'm too lazy :+1:

**Comment by dequis** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=51c"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (87.5%) 
:-1:: 1 (12.5%)

**Pull request merged**
