### PR TITLE
A critical internet experiment

### PR DESCRIPTION
**Pull request by z0nc**
For science, etc.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 0cb20d0cd4aa6518c3ed3274b35ac283e6878b5e

**Comment by dlmccoy** [comment]
:+1:

**Comment by OLef1air** [comment]
:-1:

**Comment by clay-to-n** [comment]
:+1:

**Comment by thenightwassave** [comment]
:-1:

**Comment by geoffnin** [comment]
:-1:

**Comment by bradleybuda** [comment]
:-1:

**Comment by karolba** [comment]
:+1:

**Comment by JWesorick** [comment]
:-1:

**Comment by potsmodern** [comment]
:-1:

**Comment by dos1** [comment]
:+1:

**Comment by Quuxplusone** [comment]
:-1:

**Comment by jrgifford** [comment]
:+1:

**Comment by PTaylour** [comment]
:+1:

**Comment by blister** [comment]
:-1:

**Comment by lykkin** [comment]
:+1:

**Comment by mplewis** [comment]
:-1:

**Comment by voxtex** [comment]
:-1:

**Comment by AgentME** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

**Pull request closed without merging**
