### PR TITLE
Fix comma splice

### PR DESCRIPTION
**Pull request by rspeer**
More grammatically appropriate punctuation when the bot counts the votes.

### CODE REVIEW

**Comment by hyperhtml** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by jgod** [comment]
:+1:

**Comment by vitriolix** [comment]
:+1:

**Comment by mgberlin** [comment]
:+1:

**Comment by yichengq** [comment]
:+1:

**Comment by hintss** [comment]
:+1:

**Comment by toddboom** [comment]
:+1:

**Comment by jedahan** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 87c34ff0290c28ea3276a53bc53c70afe19c4d86

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=a3g"></a>
:+1: The vote passed, this PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @hyperhtml
 * @vitriolix
 * @yichengq

**Pull request merged**
