### PR TITLE
SLURP

### PR DESCRIPTION
**Pull request by dbpokorny**
https://www.youtube.com/watch?v=9ZVKSTcPeqA

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 e0665a4c858a0095fe3569e4c083858f2b25c391

**Comment by samis** [comment]
Interesting idea. :+1:

**Comment by SpenserJ** [comment]
:+1: Seems neat, but I'm not sure how much traction it would get.

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by timweightman** [comment]
:+1: I'll upvote this... does sound interesting.

**Comment by shalecraig** [comment]
:black_large_square: :white_large_square: :black_large_square: :white_large_square: :black_large_square:
:white_large_square: :black_large_square: :white_large_square: :black_large_square: :white_large_square:
:black_large_square: :white_large_square: :+1: :white_large_square: :black_large_square:
:white_large_square: :black_large_square: :white_large_square: :black_large_square: :white_large_square:
:black_large_square: :white_large_square: :black_large_square: :white_large_square: :black_large_square:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=dcn"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @coveralls

**Pull request merged**
