### PR TITLE
Background

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Background that "draws your eyes to the content" -SpenserJ

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 7fd095f3a80fdfd45e60d7b4b7126e4108969d01

**Comment by korczis** [comment]
Just CSS gradient please

**Comment by SpenserJ** [comment]
:+1:

**Comment by korczis** [comment]
No images

**Comment by korczis** [comment]
:-1:

**Comment by korczis** [comment]
Where is background.PNG ?

**Comment by AlphaT3ch** [comment]
@korczis: data/background.png

Also, it is a very small image so technically, it is a repeating gradient...

**Comment by korczis** [comment]
backgrounds repeat indentation?

**Comment by matter123** [comment]
:+1:

**Comment by korczis** [comment]
background-repeat indentation in css

**Comment by korczis** [comment]
Sorry overlooked data/background.PNG on my mobile phone

**Comment by korczis** [comment]
Still, can not we use pure CSS gradient?

**Comment by AlphaT3ch** [comment]
@korczis: Open a PR and we'll see with the votes

**Comment by SpenserJ** [comment]
I think a background image is a good first step now that we're at 20KB for it. I'd also prefer a CSS gradient, but anything is better than solid white for the whole page IMO.

**Comment by dbpokorny** [comment]
@korczis and @AlphaT3ch why not just have a config option for CSS vs. background.png? That way you don't have to agree.

**Comment by korczis** [comment]
http://www.colorzilla.com/gradient-editor/

**Comment by LifeMushroom** [comment]
Where is the website? :+1:

**Comment by AlphaT3ch** [comment]
@LifeMushroom: Hi! http://botwillacceptanything.com

**Comment by mwerner** [comment]
:-1: Let's stick to CSS if we can

**Comment by dos1** [comment]
don't pollute the repo with commits like "add big file" -> "delete big file" :-1:

**Comment by pandzieciol** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 4 (50%) 
:-1:: 4 (50%)

**Pull request closed without merging**
