### PR TITLE
Allow projects to define membership

### PR DESCRIPTION
**Pull request by dbpokorny**

### CODE REVIEW

**Comment by dbpokorny** [comment]
If you don't like my remarks about voting cycles, then in theory projects can set their own voting cycle or have continuous voting (like we do now)

Per-project configuration could sit in a top-level projectconfigs/ directory containing config files projectconfigs/FOO. Such a file would contain custom overrides for minVotes and supermajority.

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 68e70d2ffdffb43a41d10b95f45afd829b8e0640

**Comment by dbpokorny** [comment]
The roster system provides a way to define membership in a project in an inclusive way: only listed members may vote for the corresponding PR. Alternatively, it is possible to define membership in an exclusive way: all github users *except* the listed usernames have their vote counted (provided they have starred the repo). In this way, a project may be essentially open to the public while allowing community managers to mitigate the impact of disruptive users.

**Comment by plor** [comment]
:-1:

**Comment by grantbacon** [comment]
:-1: red tape

**Comment by PurHur** [comment]
:-1:

**Comment by johnnye** [comment]
:-1:

**Pull request closed without merging**
