### PR TITLE
that web logs appear like logs, not like bulleted lists

### PR DESCRIPTION
**Pull request by shalecraig**
Improving the user interface is awesome.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 80366e2f0013e2d853acc8b995b410e9635847ac

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by PurHur** [comment]
:+1:

**Comment by Prior99** [comment]
:+1:

**Comment by Prior99** [comment]
Maybe add even mor styling, make grey lines between entries and/or use a table to seperate Ip and/or add a column for time. Maybe color the entries by type to make it easier to distinguish between Requests and (more) usefull information.

**Comment by PurHur** [comment]
We need more libs for syntax highlighting!

**Comment by dos1** [comment]
:+1:
also :+1: for syntax highlighting!

**Comment by SpenserJ** [comment]
:+1:

**Comment by plor** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=aeo"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Pull request merged**
