### PR TITLE
Email

### PR DESCRIPTION
**Pull request by dbpokorny**
If the bot has enough brains to read email, then it will be one step closer to the point where I can transfer ownership of the anythingbot.{biz,info,net,org} and anythingbots.{com,info,net,org} domains to it. Mostly what the bot has to do in terms of domain management is collect enough money to pay the domain name registrar. This is a relatively small amount of money, and the distribution of funds to the registrar can be handled through a payment process. If the bot has a public facing bitcoin address then visitors can deposit funds for its upkeep. I'm quite confident the bot is cute enough that it will be able to earn its keep on the internet. It would be a little bit easier if the domain name registrar would allow the bot to submit incremental payments so that the bot could offload bitcoins (or whatever) as soon as it receives them.

By "brain", what I mostly mean is something that makes it harder to get PRs against brain code passed versus PRs against, say, code that impacts the video feed.

### CODE REVIEW

**Comment by samis** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 890ef445a28a78b3c1215fcb02341a9c017359e2

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by dbpokorny** [comment]
https://github.com/botwillacceptanything/botwillacceptanything/pull/184 @lukeheath has the email address

**Comment by dbpokorny** [comment]
Namecheap claims to accept bitcoins https://www.namecheap.com/support/payment/bitcoin.aspx

**Comment by SpenserJ** [comment]
:+1: Would be a neat idea if you can figure out how to implement a reliable "brain"

**Comment by dbpokorny** [comment]
'Would be a neat idea if you can figure out how to implement a reliable "brain"' Spencer, I think one would have to posses a reliable "brain" in the first place in order to do that. According to the State of California, well...these are public records after all. If we are being honest with each other, then by the rules of full disclosure, you brought up the subject.

I see someone has snatched up pullrequestlive.com with namecheap. So at least someone here has a brain. Spencer, I'm going to put up a tombstone, and I really want you to be honest.

**Comment by SpenserJ** [comment]
@dbpokorny I'm not sure I followed your train of thought, so I'm going to explain what I meant.

> If the bot has enough brains to read email

How many emails do you receive on a daily basis? I receive no less than 10-20 in a day, with at least 5-10 every month being related to hosting and web development services. They all come in a different format, with different wording, and different services to log into and check balances or execute actions (renewals or payments for instance) on. Just parsing out the emails and understanding what is being said would be a significant amount of effort, and we would need to develop a "brain" that is quite reliable, in order to ensure the bot never misses a payment. Just one failure to pay, and the server would be taken offline, at which point the bot wouldn't be running, and someone would have to intervene.

> what the bot has to do in terms of domain management is collect enough money to pay the domain name registrar

Talking about paying the hosting and registrar, they'll each use a different API, with a different payment processor, accepting different currency. The bot needs to be smart enough to not only keep track of the upcoming charges for each service, but to pay them with the correct currency and API as well.

None of this is impossible, but I think it is a pipe-dream at this point in the project, and even a longshot in the next six months. I'd happily review a PR that implemented some basic concepts for it though, and think it is a great idea if you can make it reliable enough that we don't have to intervene.

**Comment by koad** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=90a"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 5 (100%)
:-1:: 0 (0%)

**Pull request merged**
