### PR TITLE
Fix a typo in the Dart to Go Transpiler

### PR DESCRIPTION
**Pull request by kaendfinger**

### CODE REVIEW

**Comment by kaendfinger** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 9d918fdfbe6204be8adf8bc7c13ae3c2fb2f2579

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by abishekk92** [comment]
:+1:

**Comment by CptnBrittish** [comment]
:+1:

**Comment by Sirikon** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=948"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @abishekk92

**Pull request merged**
