### PR TITLE
Few more ideas

### PR DESCRIPTION
**Pull request by mitar**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* a1b3b186b47d9b8aac5c7e8dd501cf033e6cbeb2

**Comment by mitar** [comment]
:+1:

**Comment by mplonski** [comment]
:+1:

**Comment by GvS666** [comment]
:+1:

**Comment by fampinheiro** [comment]
:+1:

**Comment by Zarthus** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=a39"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @GvS666

**Pull request merged**
