### PR TITLE
Added a "fork me on github" banner to all pages.

### PR DESCRIPTION
**Pull request by shalecraig**
We could do more to link to this repo.

:+1: this PR, and we can have a Github banner on our website!

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 0dd3c54c6d49431e95ffa98949ec677af1950654

**Comment by SpenserJ** [comment]
If you switch this away from hardcoding the link to botwillacceptanything/botwillacceptanything, I'll upvote it for sure. Everything should be in `{{config.user}}/{{config.repo}}`

**Comment by AlphaT3ch** [comment]
I agree with @SpenserJ, everything else in the repo is formatted like that

**Comment by shalecraig** [comment]
Will do. On mobile

On Monday, April 13, 2015, AlphaTech <notifications@github.com> wrote:

> I agree with @SpenserJ <https://github.com/SpenserJ>, everything else in
> the repo is formatted like that
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/botwillacceptanything/botwillacceptanything/pull/282#issuecomment-92590315>
> .
>


-- 
----------------------------------------------------------------
Shale Craig
shalecraig@gmail.com

**Comment by samis** [comment]
:+1:

**Comment by korczis** [comment]
Please fix what mentioned by @SpenserJ and I will immediately vote for this.

**Comment by Stary2001** [comment]
:+1:

**Comment by dos1** [comment]
:-1:

**Comment by shalecraig** [comment]
Re-opening with fix.

**Pull request closed without merging**
