### PR TITLE
Unless you stargaze, you aren't counted. Let's add that to a comment.

### PR DESCRIPTION
**Pull request by shalecraig**
Users need to be stargazers to vote, so let's let em know that.

### CODE REVIEW

**Comment by shalecraig** [comment]
bad: we only poke them after voting closes. I'm ~not adding persistence.
good: we poke them.

**Comment by gms8994** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by mattsahr** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by generalhenry** [comment]
:+1:

**Comment by fcoury** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* d557ff1ef22598c20d76aede8d727c34c25d224f

**Comment by clay-to-n** [comment]
:+1:

**Comment by jgod** [comment]
:+1:

**Comment by potsmodern** [comment]
:+1:

**Comment by mszaro** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Comment by dos1** [comment]
Conflicted with kittens - #28 - shame on you, PR!

**Pull request merged**
