### PR TITLE
Require a quorum of eight votes to pass anything

### PR DESCRIPTION
**Pull request by bradleybuda**
* With majority rule, this implies at least 5 yeas
* `QUORUM` is a constant now, but it could be configurable (i.e. the
  quorum could increase as the git history lengthens...)

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 4ef90541274f2b1093c98e37daf7d8590b54cb26

**Comment by dos1** [comment]
It already has a merge conflict!

**Comment by bradleybuda** [comment]
Oops - looks like this might be a duplicate of MIN_VOTES

**Comment by shalecraig** [comment]
Why not do something more exciting, like `max(log(committers), QUORUM)`?

**Pull request closed without merging**
