### PR TITLE
BWAA-TV RC5

### PR DESCRIPTION
**Pull request by dbpokorny**
Move the CSS out to its own file and use the JQuery style page loading

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 9090e5ad889c30f65be14611651d6d8e2baf8a05

**Comment by thenightwassave** [comment]
One day you will get this merge in.

One day.

(:+1:)

**Comment by dos1** [comment]
but not today
:-1:

**Comment by dos1** [comment]
jk :+1:

**Comment by shalecraig** [comment]
:see_no_evil:

**Comment by shalecraig** [comment]
^I hope the monkey thing hasn't been merged yet.

**Comment by samis** [comment]
:+1:

**Comment by synth3tk** [comment]
:+1:

**Comment by gpersons** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by gpersons** [comment]
:+1:

**Comment by FangedTerror802** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTkwNjY1MQ"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @synth3tk

**Comment by dbpokorny** [comment]
THANK YOU SO MUCH FOR THE SUPPORT!

**Comment by thenightwassave** [comment]
FINALLY!

**Comment by shalecraig** [comment]
dancing

**Pull request merged**
