### PR TITLE
Add Minecraft (with fixes)

### PR DESCRIPTION
**Pull request by zztemp**
In the last PR there were concerns about memory size and process lifetime. I made the suggested changes in this commit. :smiley:

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* d84eed0b9402984c4e9746b7b3df7f738d4879c1

**Comment by korczis** [comment]
No minecraft please :-1:

**Comment by RyanMilb** [comment]
:-1: Maybe a separate Autonomous Minecraft fork is a better idea.

**Comment by mappum** [comment]
:+1:

**Comment by rspeer** [comment]
:-1: I don't even think Minecraft is a good fit for this kind of thing. It's a binary blob you can't modify, so how will it interact interestingly with the project?

Once we've got more infrastructure, let's aim to get a *small, simple* game running on it.

**Comment by korczis** [comment]
What about having projects/* as git submodules?

Or having some config file / cli wizzard to download/enable projects?

**Comment by SpenserJ** [comment]
Its a neat idea, but I don't agree to the Minecraft EULA that is being forced on me. :-1:

**Comment by Stary2001** [comment]
:-1: Minecraft will use allll the ram

**Comment by rickardnorlander** [comment]
I like it. Can you make it 1.download minecraft 2. make it so it doesn't spawn a new minecraftserver every time the bot restarts?

**Comment by dos1** [comment]
no sane autonomous bot would want to include code from Microsoft inside them! :-1:

**Comment by zztemp** [comment]
@rickardnorlander It checks to see is minecraft is already running, and won't start it again if it is.

**Comment by AlphaT3ch** [comment]
:-1:  Don't steal the RAM!

**Comment by rickardnorlander** [comment]
if [ ! -f minecraft_server.1.8.3.jar ]; then wget https://s3.amazonaws.com/Minecraft.Download/versions/1.8.3/minecraft_server.1.8.3.jar; fi

**Comment by styfle** [comment]
:-1: No thanks

**Comment by zztemp** [comment]
@rickardnorlander Good idea.

**Comment by korczis** [comment]
I hope this will never get accepted :-1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 3 (27.2%) 
:-1:: 8 (72.7%)

**Pull request closed without merging**
