### PR TITLE
Close voting when guaranteed result after minimum time

### PR DESCRIPTION
**Pull request by SpenserJ**
Most of this PR is writing tests to ensure that voting occurs as expected, however there is a small change to voting that calculates the minimum number of votes required for a guaranteed win/lose, after the time limit has passed.

If there are fewer than the minimum number of votes when the minimum period elapses, a result may be guaranteed if `(MIN_VOTES * REQUIRED_SUPERMAJORITY)` is greater than the most votes for either positive or negative.

Example:
If this PR gets 6 votes for yes, and only one vote for no, it will be merged in.
If this PR gets 4 votes for yes, and none for no, it will not have the minimum for a guaranteed result (which would be 6), and will remain open.
If this PR gets 4 votes for yes, and 4 votes for no, it will be an even split, and will remain open until one side gains majority.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 47bdc1e09b92d9408034a52b5e319d0c751697a5

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by mappum** [comment]
Good call :+1:

**Comment by SpenserJ** [comment]
This would be merged by now, if this had been merged before ;)
7/0 is a guaranteed win, yet here we sit waiting for a single meaningless vote.

**Comment by korczis** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=27p"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @coveralls

**Pull request merged**
