### PR TITLE
Make it easier to add new up- or down-vote emoticons

### PR DESCRIPTION
**Pull request by rntz**
I liked #54 but the regex for :heart: was too general, so I made it better. Also, it should be easier to add new things that count as up- or down-votes now.

### CODE REVIEW

**Comment by rntz** [comment]
:+1:

**Comment by rdancer** [comment]
:-1: Why? :broken_heart: :broken_heart: :broken_heart: :hankey:

**Comment by OLef1air** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: :heart:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 7c006e1cb769dbe38b9107233b8b9d27cd012337

**Comment by dos1** [comment]
:+1:

**Comment by JWesorick** [comment]
:+1:

**Comment by mappum** [comment]
Hmm. I'm neutral on this one.

**Comment by OLef1air** [comment]
:+1: in case @mappum/the bot doesn't count before the post

**Comment by rickardnorlander** [comment]
:+1:

**Comment by r04r** [comment]
:+1:

**Comment by edunham** [comment]
:+1:

**Comment by bobisme** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by drusepth** [comment]
:hankey:

**Comment by AlphaT3ch** [comment]
:+1:

**Pull request closed without merging**
