### PR TITLE
Add vault and secrets endpoints

### PR DESCRIPTION
**Pull request by mwerner**
Let's try #148 again.

I made it not overwrite existing secrets

I also added `/secret/foo` which will just return the creation date if it is present.

I tried making it a put request, but fuck express.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* b7c0ba5edce5b8462144b0c78f099e89dc2e00d1

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by mappum** [comment]
Cool :+1:

**Comment by korczis** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by korczis** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
Nice! :+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* b7c0ba5edce5b8462144b0c78f099e89dc2e00d1

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by jish** [comment]
:+1:

**Comment by avdg** [comment]
:+1: Also note #149 on the long term

**Comment by CptnBrittish** [comment]
:+1:

**Comment by SamsPepper1** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=8iq"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 9 (90%) 
:-1:: 1 (10%)

**Pull request merged**
