### PR TITLE
Add info about the webpage being under construction

### PR DESCRIPTION
**Pull request by dos1**
I don't know how could we get so far without it!

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 765cd383d338b7244b709af949b7dcdb06e66d29

**Comment by SpenserJ** [comment]
:+1: Sure, why the heck not?

**Comment by korczis** [comment]
It looks like from 90's, but :+1:

**Comment by dos1** [comment]
@korczis: We have a long way to go before we can become a masterpiece like http://codeofrob.com/

**Comment by jedahan** [comment]
:+1:

**Comment by jaredly** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by matter123** [comment]
:+1:

**Comment by mwerner** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=1nl"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (87.5%) 
:-1:: 1 (12.5%)

**Pull request merged**
