### PR TITLE
Removed annoying length warning

### PR DESCRIPTION
**Pull request by mappum**
Redoing #108

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 361842c028ed844319f1106f782b1f6f02b97679

**Comment by leee** [comment]
+1

**Comment by avdg** [comment]
:+1:

**Comment by satyarth** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by clay-to-n** [comment]
:-1: Efficiency is important. Save the planet.

**Comment by gpersons** [comment]
:+1:

**Comment by OliverCole** [comment]
:-1: I actually think this should stay, and just be made to only post once, per #116

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=l7"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTg1MTYwNg"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

**Pull request merged**
