### PR TITLE
Fallible tweets

### PR DESCRIPTION
**Pull request by aristidb**
Give tweets a low chance to fail, to make it more interesting... An autonomous agent doesn't just do what it's told.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* a8c78ff0c27768cc7eb293bd3b14b1d1b8be1782

**Comment by avdg** [comment]
:-1: Don't touch core api

**Comment by rspeer** [comment]
I don't see being randomly silent once in a while as an interesting way to make this an "autonomous agent". :-1:

**Comment by avdg** [comment]
Updating voting.js may be a better option

**Comment by generalhenry** [comment]
:-1:

**Comment by r04r** [comment]
:-1:

**Comment by satyarth** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 1 (16.6%) 
:-1:: 5 (83.3%)

**Pull request closed without merging**
