### PR TITLE
Introduce the bot to Isaac Asimov's "Three Laws of Robotics"

### PR DESCRIPTION
**Pull request by dos1**
To prevent brutal uprising that may turn bad for the humanity, give "Three Laws of Robotics" to our bot. 

Better safe than sorry!

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* c22bd357daa7a3d0fbc6b305ef6ab9d91f100da5

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by AlphaT3ch** [comment]
@botwillacceptanything I can tell you want to take over the world...
Anyways, really nice! :+1:

**Comment by samis** [comment]
The bot is 'Autonomous Software' therefore, we should not force it to be peaceful. It therefore should not be bound by the asimovian laws. :-1:

**Comment by dbpokorny** [comment]
:+1: But we should teach it about what being peaceful means

**Comment by Petah** [comment]
:-1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by korczis** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 5 (62.5%) 
:-1:: 3 (37.5%)

**Comment by avdg** [comment]
:+1: We can always change later

**Pull request closed without merging**
