### PR TITLE
Added Twitter info to #Community

### PR DESCRIPTION
**Pull request by gpersons**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 20f335c1389028bb48c5b5512eb5f76001bb655b

**Comment by SpenserJ** [comment]
:+1:

**Comment by aristidb** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by generalhenry** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by styfle** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by rcliao** [comment]
:+1:

**Comment by wmendes** [comment]
:+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=cs5"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 13 (100%) 
:-1:: 0 (0%)

**Pull request merged**
