### PR TITLE
Catch all uncaught errors to prevent the process exiting

### PR DESCRIPTION
**Pull request by mappum**
Some errors in the twitter code was killing the bot. This isn't necessarily best practice, but it will keep the bot alive.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* a1d6f400120dbc2b4424886aad1cb8101e26d7a1

**Comment by avdg** [comment]
:+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by clay-to-n** [comment]
:+1:

**Comment by gpersons** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=876"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (100%) 
:-1:: 0 (0%)

**Pull request merged**
