### PR TITLE
Wildcard - 1/1024 chance for PR getting accepted regardless of vote results

### PR DESCRIPTION
**Pull request by dos1**

### CODE REVIEW

**Comment by davelopware** [comment]
:-1:

**Comment by madfriend** [comment]
:-1:

**Comment by dos1** [comment]
:+1:

**Comment by erykpiast** [comment]
:+1:

**Comment by kjnsn** [comment]
:-1:

**Comment by lionel-** [comment]
:-1:

**Comment by chrisbujok** [comment]
:-1:

**Comment by JaredCubilla** [comment]
:-1:

**Comment by jauco** [comment]
:-1:

**Comment by napstr** [comment]
:+1:

**Comment by avdg** [comment]
:-1: in current state, I don't want people to think it's because of democracy that the patch got merged (instead of luck).

**Comment by rmetzler** [comment]
:+1:

**Comment by petrosh** [comment]
:-1:

**Comment by cjbayesian** [comment]
:+1:

**Comment by rabbidrabbit** [comment]
:+1:

**Comment by vytis** [comment]
:+1:

**Comment by Promichel** [comment]
:-1:

**Comment by magnusstubman** [comment]
:+1:

**Comment by tapetersen** [comment]
:-1:

**Comment by lol768** [comment]
:-1:

**Comment by christopherdebeer** [comment]
:-1:

**Comment by devn** [comment]
:-1:

**Comment by jvt** [comment]
:-1:

**Comment by devn** [comment]
:-1:

**Comment by benmanns** [comment]
:-1: Prone to brute forcing.

**Comment by Paperback** [comment]
:+1:  Prone to brute forcing only makes it more interesting

**Comment by nathankleyn** [comment]
:-1:

**Comment by didimitrie** [comment]
:thumbsdown:

**Comment by AshCoolman** [comment]
:-1:

**Comment by AshCoolman** [comment]
If there was still some quality control, I'd +1

**Comment by roby65** [comment]
:-1:  Well, someone broke the bot code and now isn't answering to pull requests :/

**Comment by rjgonza** [comment]
:-1:

**Comment by avdg** [comment]
Last merge: #92 - Bot was recursing merge

**Comment by dufferzafar** [comment]
:-1:

**Comment by aerobless** [comment]
:-1:

**Comment by hfinger** [comment]
:-1:

**Comment by lukeheath** [comment]
:-1:

**Comment by SpenserJ** [comment]
:-1:

**Comment by Kyoushu** [comment]
:-1:

**Comment by k1sul1** [comment]
:+1:

**Comment by andreis** [comment]
:+1:

**Comment by ellisvalentiner** [comment]
:+1:

**Comment by JacobEdelman** [comment]
:-1:

**Comment by drocta** [comment]
:-1:

**Comment by at-jamiefraser** [comment]
:+1:

**Comment by joshfree** [comment]
:-1:

**Comment by alexvandesande** [comment]
👍🏻

**Comment by RyanMilb** [comment]
:-1:

**Comment by penderi** [comment]
:+1:

**Comment by poxip** [comment]
:+1:

**Comment by ChristoSilvia** [comment]
:-1:

**Comment by rpignolet** [comment]
:-1:

**Comment by erkinalp** [comment]
Bot has hit the rate limit.

**Comment by botwillacceptanything** [comment]
#### :ballotbox: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* a8963593b19cad74fdd07bbfa6c9c733d7162eb3

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 8 (23.5%) 
:-1:: 26 (76.4%)

These users aren't stargazers, so their votes were not counted: 
 * @erykpiast
 * @lionel-
 * @chrisbujok
 * @cjbayesian
 * @rabbidrabbit
 * @nathankleyn
 * @AshCoolman
 * @AshCoolman
 * @Kyoushu
 * @k1sul1
 * @ellisvalentiner
 * @at-jamiefraser
 * @joshfree
 * @penderi

**Pull request closed without merging**
