### PR TITLE
Launcher does some error checking

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by mwerner** [comment]
Can you describe in more detail what the intent of this is?

**Comment by rickardnorlander** [comment]
The launcher detects failure to run main.js. If that happens it calls a stub function, that will, in a future commit, be extended to revert to some previous, good state.

**Comment by rickardnorlander** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* de51bc20457cef549320c0cf6115f8bd365d363a

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by dos1** [comment]
:+1:

**Comment by avdg** [comment]
:+1: @botwillacceptanything don't forget to eat you're medicines!

**Comment by jedahan** [comment]
While I like the idea in theory, I wonder if there is a safer way to check without using exec... since it seems a great way to introduce privlege escalations and the like...

**Comment by generalhenry** [comment]
:-1:

**Comment by rickardnorlander** [comment]
@jedahan There doesn't seem to be a native nodejs way of checking for running processes by names.

**Comment by dos1** [comment]
@jedahan: Uhm? What "privilege escalations" do you mean?

**Comment by pandzieciol** [comment]
:+1:

**Comment by mappum** [comment]
I like this change, but I'm downvoting since it's not finished. I'll upvote once the reverting code is implemented. :-1:

**Comment by dos1** [comment]
Aaah, where's the "process.exit(0);" though? If the bot restarts successfully, the old instance is not terminated! :-1:

**Comment by pandzieciol** [comment]
ouch :-1:

**Comment by avdg** [comment]
:-1:

**Comment by samis** [comment]
:-1: Until it is finished.

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 1 (12.5%) 
:-1:: 7 (87.5%)

**Pull request closed without merging**
