### PR TITLE
Tweet PR status @anythingbot

### PR DESCRIPTION
**Pull request by lukeheath**
Okay, all set now. 

Post tweet when PR voting starts, and when it is closed or merged.

I'm intentionally leaving Twitter auth public so the community can decide how to manage, and so it will function immediately when/if the bot merges. If we want this to be private (it probably should be), whoever has access to the bot's config.js will need to update with a new keys.

I setup a new Twitter account here: https://twitter.com/anythingbot. If the repo owner would like to DM me there I'll be happy to hand over account control. I also setup botwillacceptanything@gmail.com.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 35420ac636bf9b61b21a7cd0091f33d995a894b8

**Comment by AlphaT3ch** [comment]
:+1: Cool, if it gets accepted defiantly add it to the README with a link to the profile! (I'm the first follower!)

**Comment by SpenserJ** [comment]
Looks good. Won't give a thumbs up until someone can test this, since I'm in the middle of another commit. Seems like a solid implementation though

**Comment by mappum** [comment]
Awesome. I can create a private key to put on the bot. :+1:

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by lukeheath** [comment]
Cool! :+1: 

Should we maybe revisit the warning message above? Any additional lines in voting.js fires it.

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by gpersons** [comment]
:+1:

**Comment by simonuvarov** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7np"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (100%) 
:-1:: 0 (0%)

**Pull request merged**
