### PR TITLE
Removed rate limiting warning from README, at Github staff's request

### PR DESCRIPTION
**Pull request by mappum**
Github support told me to remove this.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 3a2b80531e4fe2e7a85bd04ea81db748abfc6a04

**Comment by mappum** [comment]
:+1:

**Comment by kaendfinger** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1: What must be done, must be done...

**Comment by Promichel** [comment]
+1

**Comment by prokizzle** [comment]
:+1:

**Comment by dlmccoy** [comment]
:+1:

**Comment by genbit** [comment]
:+1:

**Comment by sparky222b** [comment]
:+1:

**Comment by sparky222b** [comment]
Do we also need to knock down the poll frequency?

**Comment by josephyzhou** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=29c"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @dlmccoy
 * @genbit

**Pull request merged**
