### PR TITLE
Themes are love, themes are life

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Added a green, orange and gold theme

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 a26118c9f191bef1e9b6a5d9938594cf99cae826

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by dbpokorny** [comment]
:-1: do it in javascript

**Comment by RyanMilb** [comment]
@dbpokorny, why is it better in javascript?

**Comment by AlphaT3ch** [comment]
@dbpokorny: Isn't it following it's respected format already?

**Comment by avdg** [comment]
:+1:

@dbpokorny I'm wondering what to change about the javascript.

**Comment by avdg** [comment]
@AlphaT3ch You're sneaking in some changes proposed in #425 ;-)

**Comment by dbpokorny** [comment]
body is the same, jumbotron, etc... at least move them to a separate .css file, theme-common.css so there is not so much duplication.

**Comment by SpenserJ** [comment]
I'd also prefer to have a base theme, that they all override where necessary. While we're talking about my desires, can we also add in a cookie check on the server, that will immediately send the correct theme css file, instead of it flickering ponies before loading? :+1:

**Comment by shalecraig** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=b0v"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (85.7%)
:-1:: 1 (14.2%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
