### PR TITLE
No harmful pull requests, IRC Bot statistics and updates to README.md

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Make sure any code being added couldn't be used for harm or to break the main features such as voting.js. Example: DDOS script that someone makes multiple accounts to like the pull request. Also updated the README.md to feature some notes about the environment that the bot is running in (Proof is at https://github.com/botwillacceptanything/botwillacceptanything/issues/55). Also adding an IRC chat bot for live statistics in the Freenode chatroom.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 81bfcb858946e5b0986863d21159792659fccad1

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 81bfcb858946e5b0986863d21159792659fccad1

**Comment by mappum** [comment]
:+1: There's a conflict, so this won't get merged.

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Pull request closed without merging**
