### PR TITLE
Fix init order - init bodyParser()

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by dos1** [comment]
:+1:

**Comment by pandzieciol** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*a1be8804460493a34eb2edde058c36d1c6ee7fe1

**Comment by dbpokorny** [comment]
:+1:

**Comment by korczis** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Comment by pandzieciol** [comment]
WTF

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Pull request closed without merging**
