### PR TITLE
Might as well use some more deprecated tags while we are at it.

### PR DESCRIPTION
**Pull request by Petah**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* f220b8ae5442ad9f18f3294af3b62716a2235ef5

**Comment by SpenserJ** [comment]
iframe isn't deprecated, and is still a standard way of embedding content from other websites. :-1:

**Comment by korczis** [comment]
:-1: 

It will be better to have it layout/main.hbs after #252 got merged.

**Comment by dos1** [comment]
I love it :+1:

**Comment by Petah** [comment]
@SpenserJ I was referring to the `<center>` tag

**Comment by karolba** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
@Petah I designed the star button to go there... It was already centered when I last touched it unless @korczis changed it.. I don't really like the moving bar news footer thing like that so I'm afraid I'm going with :-1: on this one...

**Comment by dos1** [comment]
We need to go a long way until we reach the perfectness of http://codeofrob.com/

**Comment by pandzieciol** [comment]
:+1:

**Comment by matter123** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 5 (62.5%) 
:-1:: 3 (37.5%)

**Pull request closed without merging**
