### PR TITLE
Add a hello world project in C++ 

### PR DESCRIPTION
**Pull request by oneminot**
and a framework to add hello world projects in other languages

### CODE REVIEW

**Comment by OLef1air** [comment]
:-1:

**Comment by JustAPerson** [comment]
:-1:

**Comment by bradleybuda** [comment]
:-1:

**Comment by rickardnorlander** [comment]
:-1:

**Comment by fiveminuteargument** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

**Pull request closed without merging**
