### PR TITLE
Added a background (uses data uri) to the main site

### PR DESCRIPTION
**Pull request by AlphaT3ch**
A nice background generated with a data uri so no need to load external png images

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 10245358662ff3e8f0228887a4cad598bc8e2b69

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by SpenserJ** [comment]
If we move the stylesheet into an external file, I'd upvote this, otherwise it suffers the same problem as #306

**Comment by dbpokorny** [comment]
:-1: 

"no need to load external png images"

AlphaT3ch, could you please explain why you think image data should be included in the text file?

**Comment by plor** [comment]
:-1:

**Pull request closed without merging**
