### PR TITLE
Make the anythingbot accept more PRs

### PR DESCRIPTION
**Pull request by dbpokorny**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 8f159538e846f3fac0d2828ff0111eb50d7dc2ba

**Comment by avdg** [comment]
Congratz for taking attempt to take ownership of the repo and let users suffer from unknown changes ;-)

**Comment by avdg** [comment]
Also great way to put in unstable code as it is now

**Comment by avdg** [comment]
Also great way to get attention

**Comment by avdg** [comment]
Anyway, here is my vote :-) :-1:

**Comment by dbpokorny** [comment]
"attempt to take ownership of the repo"

I have no access to any account on botwillacceptanything.com, nor do I have any github auth tokens for botwillacceptanything/botwillacceptanything, nor do I have the password to botwillacceptanything@github.

I have never expressed an interest in acquiring any of the above, @mappum and @SpenserJ know this.

**Comment by avdg** [comment]
I take my own quotes as a claim for later, feel free to do what you want as I can't fight the system anyway ;-)

**Comment by avdg** [comment]
At least, this project is at this rate (to say carefully) a bit dying anyway

**Comment by plor** [comment]
:-1:

**Comment by dbpokorny** [comment]
@avdg I agree, what are you going to do about it? "At least, this project is at this rate (to say carefully) a bit dying anyway"

**Comment by samis** [comment]
:-1:

**Comment by avdg** [comment]
We should play the game and wait for gains in real life I guess...

**Comment by avdg** [comment]
Now its more waiting game :-)

**Comment by avdg** [comment]
Unless you know some breading ground that's easy to implement or to frame about?

**Comment by drocta** [comment]
I think I would support a directory that has a lower minimum upvote requirement for approval, but I think 1 or 2 is too low.
Maybe a directory with a minimum vote count of 4, requiring a 51% majority?

So long as the stuff outside of that directory did not require anything which is in that directory, I don't think that would cause too much of a problem. If the stuff in the easier to change directory ("unstable"?) isn't needed by the main program, it shouldn't cause too much harm I don't think.

I mean, one still wouldn't want the directory filling up with junk, but at least in periods of low activity, things could still be worked on in that.

**Comment by avdg** [comment]
We need safe rules though

**Comment by PurHur** [comment]
:-1:

**Comment by albertorestifo** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.


----
**Tallies:**
:+1:: 1 (16.6%)
:-1:: 5 (83.3%)

These following 1 voter(s) were not _stargazers_, so their votes were not counted:

- :monkey: @coveralls

*Non-stargazers*: Be sure to :star:star the repository if you want to have your say!

**Pull request closed without merging**
