### PR TITLE
Capture stdout to a variable, and display that via the webserver

### PR DESCRIPTION
**Pull request by SpenserJ**

### CODE REVIEW

**Comment by OLef1air** [comment]
:+1:

**Comment by rspeer** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: Looks like author doesn't count as an automatic vote yet.

**Comment by avdg** [comment]
Tending to +1 this

**Comment by ChristoSilvia** [comment]
:+1:

**Comment by d11e9** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballotbox: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* a15e194948c8efc40f898b31318a4f7bc8b15f2e

**Comment by roby65** [comment]
:+1:

**Comment by mappum** [comment]
Conflicts :/ :-1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTk3OTA3NQ"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Comment by SpenserJ** [comment]
@mappum I think it conflicts on the package.json change made by #98

**Comment by mappum** [comment]
Maybe we should get the bot to post output telling us what the conflicts are.

**Pull request closed without merging**
