### PR TITLE
Simple test change

### PR DESCRIPTION
**Pull request by mappum**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **10** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* d8fefc6abbda2303c42239f9c970252b8bcecb27

**Comment by mappum** [comment]
:+1:

**Comment by Kepzorz** [comment]
:+1:

**Comment by Kepzorz** [comment]
:+1:

**Comment by Blecki** [comment]
:+1:

**Comment by feliperezende** [comment]
:+1:

**Comment by loganfuller** [comment]
:+1:

**Comment by jamescostian** [comment]
:+1:

**Comment by jeffstephens** [comment]
:-1:

**Comment by stevencorona** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* d8fefc6abbda2303c42239f9c970252b8bcecb27

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (83.3%) 
:-1:: 1 (16.6%)

**Comment by anthropomo** [comment]
:-1:

**Pull request merged**
