### PR TITLE
Guarantee PR #10000 is merged

### PR DESCRIPTION
**Pull request by mwerner**
As a celebration for our longevity! :tada:

### CODE REVIEW

**Comment by cgag** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by kyleterry** [comment]
:+1:

**Comment by gms8994** [comment]
Longevity is good. The potential for terror is bad. :-1:

**Comment by Synesso** [comment]
:-1:

**Comment by Simon-Coetzee** [comment]
:-1:

**Comment by thenightwassave** [comment]
:1: backdoor waiting to happen

**Comment by OLef1air** [comment]
:-1:

**Comment by franc0is** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 5e21e6125dbe2059d3e0b7cfed826386e64ebde3

**Comment by MasterDurron** [comment]
:-1:

**Comment by clay-to-n** [comment]
:+1: This is an important PR that must be celebrated and accepted

**Comment by curtisz** [comment]
:-1:

**Comment by fiveminuteargument** [comment]
:-1:

**Comment by jish** [comment]
:+1: I await skynet

**Comment by daniula** [comment]
:-1:

**Comment by tom-james-watson** [comment]
:-1:

**Comment by MichaelKuhinica** [comment]
This could be really dangerous! I am upvoting as token of faith on humanity. 
:+1:

**Comment by geoffnin** [comment]
:-1:

**Comment by mwerner** [comment]
This world needs more @MichaelKuhinica

**Comment by jgod** [comment]
:+1:

**Comment by mszaro** [comment]
:-1:

**Comment by jrgifford** [comment]
:-1:

**Comment by fiveminuteargument** [comment]
I'm convinced; changing my vote :+1:

**Comment by karolba** [comment]
:+1:

**Comment by skyhighwings** [comment]
:+1+

**Comment by mplewis** [comment]
:-1:

**Comment by skyhighwings** [comment]
:+1:

**Comment by JustAPerson** [comment]
What could go wrong?
:+1:

**Comment by andyland** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

**Pull request closed without merging**
