### PR TITLE
Make the bot talk to people

### PR DESCRIPTION
**Pull request by Prior99**
## Talk to people!

The bot feels lonely and sad and therefor wants to talk to people!

He isn't so good at it yet and only greets people joineng the irc-channel (yet).

As with normal people there are people the bot likes as well as people he doesn't like at all.

## Scoring:

Based upon the name of a user the bot will calculate a hash-value from -10 to 10 based on the users name  and if it's < -3 he hates the user, if it's > 3 he likes the user and if it's inbetween he feels neutral to the user.

Using this score the bot then generates random greetings for the user. He will generate different greetings based on how much he hates/loves the user.

## Examples: 

The bot really doesnt like the user called *Prior*, the score is -6:
 * Please just get cancer, Prior!
 * I hate you Prior. Better watch out or I will kick you. Prior, why can't you just get rekt?

The bot also doesn't like *Ipsum* (-4) but still more than *Prior*.
 * Hello, Ipsum, looks like you didn't die yesterday. Too bad. 

The bot feels neutral to *Lorem* (+1):
 * Hey Lorem, It's okay to see you.
 * Hey Lorem, I hope everything is okay. 

The bot really likes *Bar* (+7):
 * Hello Bar, It's cool to see you! It's great to see you!
 * Oh, hello Bar, I like you. You are smart. I hope you had a cool day.
 * Oh, hello Bar, It's nice to see you! I appreciate you. We should hang out together tomorrow.

## Under the hood:

There isn't too much variability in here, yet, good thing I designed this to be easily extendable:

You can define new sentences like this:

```javascript
    "Hello, {{person}}, Let's go to {{place}} together!"
```

Where ```{{person}}``` will be replaced by the users name and ```{{place}}``` indicates a reference to a place you can define like this:

```javascript
     ...
    place : [
        new Word("the park", 3),
        new Word("a romantic dinner", 7)
    ]
     ... 

Where the number is a ranking how strong the respective word is.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 885435874076b47e83f12d9a5f5b3c45227c83d3

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by Prior99** [comment]
:+1:

**Comment by samis** [comment]
Nicely done, :+1:. Would it be possible for a user to ask the bot for the value or would they have to calculate it themselves?

**Comment by Prior99** [comment]
@samis the value is not exported or displayed anyhow, also we do not yet have a framework on talking to the bot. But I guess the user will notice.

**Comment by Prior99** [comment]
Based on this it should be fairly easy to have the bot react to questions:

```why .*? \?``` would be a regular expression to detect a question, based on how the bot likes the user it would be easy to let him answer something like:
 * Your mother
 * Because fuck you, that's why

If the bot outrageous hates a user we could also let him randomly insult that user when the user writes something in the channel etc.

**Comment by KyleDavidE** [comment]
:+1:

**Comment by SpenserJ** [comment]
Neat idea, but I have to give a :-1: for a few reasons:

* The language may be considered offensive.
* The bot will greet itself when joining the channel.
* Tab indentation when the rest of the project uses spaces. Please switch this to either 2-space or 4-space indentation, so we don't have three standards on the go at once.

**Comment by Moerrrlin** [comment]
:+1:

**Comment by Prior99** [comment]
@SpenserJ 

 > The language may be considered offensive.

Oh no, who would just go on the internet and use offensive language?

 > The bot will greet itself when joining the channel.

This is true but will only happens once each few days, also please maybe the bot has a split personality :-) But I can fix this if this vote fails and you all feel like this is really neccessary...

 > Tab indentation when the rest of the project uses spaces. 

Not true. Much other files also use tab indetation (for example ```generatename.js```)
Also we do not have an official codestyle guideline or have we?
Maybe we should have the bot autogenerate a random codestyler >:D

**Comment by PurHur** [comment]
:+1: The only thing of @SpenserJ  argumentation i can follow is "The bot will greet itself when joining the channel." but thats a bug not a feature!

**Comment by SpenserJ** [comment]
@Prior99 Offensive language has been downvoted in other PRs (including mine) and I agree with them on it. I don't think the bot should curse, but rude responses are fine.

**Comment by samis** [comment]
I don't mind the bot cursing - there's much worse on the internet. Besides, anyone offended can take it to vote. My :+1: stands.

**Comment by thenightwassave** [comment]
:-1: language

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTc5MTUzOA"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

**Comment by dbpokorny** [comment]
Can the bot insult everyone, and be more creative in its insulting? :-1:

"The Mook is what critics call the crude, loud, obnoxious, in-your-face character that can be found almost any hour of day or night somewhere on MTV." -- "The Merchants of Cool" http://www.pbs.org/wgbh/pages/frontline/shows/cool/view/

http://www.pangloss.com/seidel/Shaker/ (Shakespearian insult generator)

**Comment by avdg** [comment]
:-1: Don't make me put people in negative simulation rooms and brainwash them. Don't make me put people in psychiatry...

**Pull request merged**
