### PR TITLE
Database

### PR DESCRIPTION
**Pull request by shalecraig**
Split #381 into two parts:

This part:
* Creates (and exports) a sqlite3 database.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 a00a09d4b4114f5c0b6dd797c19d24c481cd989e

**Comment by SpenserJ** [comment]
:+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by Prior99** [comment]
:+1:

**Comment by gpersons** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1: With a scheme->sqlite and sqlite->scheme suite of import/export functions it will be possible for users to store "logic modules" in sqlite and import them into the "basic logic system of sicp4.4" on demand. The rest of this comment is about http://en.wikipedia.org/wiki/Data_migration in SQL-based relational database systems so stop reading now if this bores you.

SQL-based database files are of two types: those checked into the git repo (examples for demonstration purpose) and those in local storage, not in the repo. In the case of the former, git keeps the demo data and the db interface in sync. In the case of the latter, database migrations are a part of life. A PR may have an impact on the schema, and the BWAA project has the capacity to set a protocol for projects or initiatives to follow in case it is expected that PRs impacting the schema will be involved. What follows is an oversimplification of the approach (http://en.wikipedia.org/wiki/Slide.com) took.

The process for introducing schema changes (a.k.a. "migrations") involved reserving numbered files in the "db/schema" directory. Files named "schema/1.sql" "schema/2.sql". These would consist of "create table", "add column", "add index", ... and commands to insert initialization data. Testing involved creating a new database, applying all of the schema files in order, inserting dummy data into the database, then running the test scripts. In order to test a deployment of a schema change, make of copy of production (not everything of course, usually a tiny sampling of data), then apply the latest version of schema/N.sql, run the test scripts. A file "schema/N.sql" is a "schema delta file".

This helped when multiple projects wanted to add tables/columns to the database. Here was the process: when a project needed dynamic storage in the sqlite database, a new branch was created off of the live master with a single extra file, schema/N-RESERVED containing a line "Reserved for ..." where "..." was a pointer to some justification for reserving a change to the sql schema and some informal remarks indicating the impacted tables (as a courtesy to other teams). These were "dummy" files representing the act of "taking a number" or "getting in line". The next team that wanted to change the database schema now had to use file schema/(N+1)-RESERVED and have their "schema delta" applied after schema/N.sql.

Under normal operation, the schema directory contains files numbered 1.sql, 2.sql, ... contiguous on up, and then near the high end you see

343.sql 344.sql 345-RESERVED 346.sql 347.sql 348-RESERVED 349-RESERVED

along with a README file giving developers instructions on how to interact with the schema/ directory.

Here is a concrete example: a project wants to add a "user activity log", a place to record the logical behaviors of the users (as in, logical meaning "one level of abstraction above the physical", not "the users are behaving logically") interacting with the bot at a very fine level of detail, so-called "social media metrics".

This reservation (a dummy branch with a single new dummy file schema/N-RESERVED where N is the next number in sequence) is pushed to master in order to inform other teams that schema update N has been taken. The team executing this project now has a fixed idea of who they need to talk with in the unlikely event of schema upgrade conflicts. In the real branch the team works on, their "schema delta" can evolve as the project develops without impacting any other projects. When it comes time to merge, the "reservation file" schema/N-RESERVED goes away and is replaced with actual schema/N.sql file. It is now possible to replay the evolution of the database schema and run the old test scripts against the new schema (to check for regressions).

Do I think BWAA should implement such a process in the next few days? Does it address some pressing concern that affects multiple developers right now? Doubtful. But a process such as this (and variations on it, alternatives to it) can help manage the complexity.

**Comment by samis** [comment]
:+1: 
Momentary hijack: What if I added Redis support so that you could have both the option of SQL and NoSQL / schemaless DB for any data storage / persistence. 

Additionally: DEAR GOD THAT WALL OF TEXT.

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=1dk"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Pull request merged**
