### PR TITLE
Added ideas.md

### PR DESCRIPTION
**Pull request by gpersons**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 8c3fd8c28e90f97eb206ff970b9db2642e0580d2

**Comment by mappum** [comment]
Good idea. :+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by mwerner** [comment]
:+1:

**Comment by TkTech** [comment]
:+1:

**Comment by gms8994** [comment]
:+1:

**Comment by bichiliad** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by generalhenry** [comment]
:+1:

**Comment by fcoury** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
