### PR TITLE
Add Clippy

### PR DESCRIPTION
**Pull request by dos1**
Let's try once again. Our best pal Clippy never left us when in need, so we must not leave him now!

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* e780fa8ae89359576ccf5a5f22165d72362394e8

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by samis** [comment]
My previous comment stands. :+1:

**Comment by Stary2001** [comment]
:+1: yes for clippy!

**Comment by SpenserJ** [comment]
Too many smart bots on the lose already. :fearful: :-1:

**Comment by soccermitchy** [comment]
:+1: clippy is awesome!

**Comment by samis** [comment]
@SpenserJ Clippy is nothing compared to our smart BWAA overlord.

**Comment by pandzieciol** [comment]
:+1:

**Comment by SpenserJ** [comment]
After discovering that BonziBuddy is in ClippyJS, I am voting :+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=4d8"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Pull request merged**
