### PR TITLE
Added a robotic favicon and sleek background for the webserver

### PR DESCRIPTION
**Pull request by AlphaT3ch**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* ef45bc0d49e8c218001ccf9c7ad4e86bb3ce3e52

**Comment by korczis** [comment]
Can we use just CSS gradient without need for jpg/PNG/etc?

**Comment by korczis** [comment]
:-1:

**Comment by SpenserJ** [comment]
Agreed. This is still a 1MB image that we really don't need. :-1:

**Pull request closed without merging**
