### PR TITLE
Added a Background using data uri and put css into a css file

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Reroll of #305 that now uses an external css file

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* d3bd25a3fca03c9de10bfa01bc6fb89cceffbe0c

**Comment by korczis** [comment]
:+1: For using .css file

**Comment by plor** [comment]
:-1: still not liking the data URI in source control

**Comment by avdg** [comment]
Interesting read I guess: http://stackoverflow.com/questions/1124149/is-embedding-background-image-data-into-css-as-base64-good-or-bad-practice

**Comment by dbpokorny** [comment]
:-1: I don't like binary data in text files

**Comment by SpenserJ** [comment]
:+1:

**Comment by Prior99** [comment]
:+1:

**Comment by dos1** [comment]
Why the hell is this image in data URI? :-1:

**Comment by pandzieciol** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 4 (50%) 
:-1:: 4 (50%)

These users aren't stargazers, so their votes were not counted: 
 * @botwillacceptanything

**Pull request closed without merging**
