### PR TITLE
Notify voters when a change makes voting less effecient

### PR DESCRIPTION
**Pull request by Blecki**

### CODE REVIEW

**Comment by Blecki** [comment]
:+1: Lets not let this get out of hand guys. We all know that code size is the only valid form of program performance measurement, so lets formalize our no-new-bytes policy.

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* bb61e4268a27d6e2fc83922eacd2ef72e87c5a1f

**Comment by clay-to-n** [comment]
:+1:

**Comment by erkinalp** [comment]
:+1:

**Comment by mstoiber** [comment]
:+1:

**Comment by michaelperret** [comment]
:+1:

**Comment by else** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=79n"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @michaelperret

**Comment by botwillacceptanything** [comment]
#### :ballotbox: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* bb61e4268a27d6e2fc83922eacd2ef72e87c5a1f

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=9k7"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 5 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @michaelperret

**Pull request merged**
