### PR TITLE
Allow the PR creator to vote negative

### PR DESCRIPTION
**Pull request by dos1**
Just because.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* c19d40385236dece2e537c3ed82ef3c993f96faf

**Comment by avdg** [comment]
(Yeah, I was thinking about giving the freedom that PR creators should be able to vote freely as well)

Though, why should they vote negatively on a PR they have created them self?

**Comment by dos1** [comment]
Dunno, but if someone would want, then why not? :hamster:

**Comment by thenightwassave** [comment]
Further discussion reveals something to the author and then wants to make a vote fail so a better version can be submitted.

**Comment by avdg** [comment]
They can still close a PR them self

**Comment by dos1** [comment]
PR author changed his mind and dislikes the change, but wants to still allow others to make final decision? :D

**Comment by avdg** [comment]
:+1: Just to give them a way to defend against their pro vote -_-

**Comment by KyleDavidE** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: I like how you did this

**Comment by pandzieciol** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=bps"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Pull request merged**
