### PR TITLE
Fix the bot!

### PR DESCRIPTION
**Pull request by dos1**
Damn you, lots of merges that break stuff!

### CODE REVIEW

**Comment by SamsPepper1** [comment]
:+1:

**Comment by avdg** [comment]
:+1: Fixes error at https://github.com/dos1/botwillacceptanything/blob/133ef4e9198de17d638f36054994efe392463211/main.js#L22

**Comment by pandzieciol** [comment]
:+1:

**Comment by korczis** [comment]
@dos1 sorry for that

:+1:

**Comment by Gaelan** [comment]
:+1:

**Comment by SamsPepper1** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
I was told that [this](https://github.com/AlphaT3ch/botwillacceptanything/blob/master/lib/events.js#L11) was the issue. Anyways, nice job! :+1:

**Comment by dos1** [comment]
@AlphaT3ch: well, it could be both ;)

**Comment by inakiabt** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by doyleyoung** [comment]
:+1:

**Comment by generalhenry** [comment]
:+1"

**Comment by generalhenry** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
Emergency merge.

**Pull request merged**
