### PR TITLE
BWAA-TV Friday Mix

### PR DESCRIPTION
**Pull request by dbpokorny**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 0157a6a8e3fa3cfb27c4152cea99f47d5beda710

**Comment by catsgame** [comment]
:+1:

**Comment by SpenserJ** [comment]
@dbpokorny Are you running multiple instances of the bot to help your cause?

:+1: just to quiet the noise in my notifications.

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=37f"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 7 (100%)
:-1:: 0 (0%)

These following 1 voter(s) were not _stargazers_, so their votes were not counted:

- :monkey: @coveralls

*Non-stargazers*: Be sure to :star:star the repository if you want to have your say!

**Comment by dbpokorny** [comment]
Hi @SpenserJ, maybe we can lower the voting threshold? All of the github accounts that upvoted this PR (aside from you of course) are sockpuppets of mine.

Even with my sockpuppets I don't have the ability to lower the voting threshold. You'll have to do it since you're the sysadmin, I can only lower the default threshold. I'm thinking 5 votes and 50% majority? That's what the settings were before the big bump.

**Pull request merged**
