### PR TITLE
Needs more rainbows and ponys! Your arguments are invalid.

### PR DESCRIPTION
**Pull request by Prior99**
This definitly needs more ponys and rainbow because everything gets a hell lot of better utilizing ponies and rainbows so I added a flying rainbow-dash as well as a rainbow in the bottom-left corner.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 49e6168bb117791f20dbed2711443e8334c214f6

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by Prior99** [comment]
:+1:

**Comment by hiliev** [comment]
:+1:

**Comment by shalecraig** [comment]
:-1:

**Comment by dbpokorny** [comment]
:-1: Please create a /pony endpoint and...corral...the MLPFIM fandom there so it is relatively contained and appreciated.

**Comment by AppleDreck** [comment]
:+1:

**Comment by jfmu** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by dos1** [comment]
Please also see #319 :)

**Comment by pandzieciol** [comment]
:+1:

**Comment by Mimoja** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=6gs"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

These users aren't stargazers, so their votes were not counted: 
 * @botwillacceptanything
 * @botwillacceptanything
 * @hiliev

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Comment by Moerrrlin** [comment]
+1

**Pull request closed without merging**
