### PR TITLE
More IRC Changes

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Removed the quit message since the user exiting won't see it, added a welcome message, made the bot only speak if spoken to, made a reply to CTCP version, added a realname, added a username, added port to the configuration and added SSL for the IRC connection.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 f1453f74262c3fcde68ece4e271abe06e0c99659

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by shalecraig** [comment]
:+1:

If you end up re-rolling this, can you add the bot's name to the ctcp response?

**Comment by AlphaT3ch** [comment]
@shalecraig: config.irc.user is the bot's name... Therefore, it is already in the ctcp response :D

How come the build failed?

**Comment by SpenserJ** [comment]
I think we should use an alternate username as the default, so we don't run into multiple unofficial bots trying to connect as the master. 

Have you tested all of this? If you check the Travis build results, it failed because there is a problem in the IRC integration. Run `gulp test` and fix that up, then reroll.

While you're rerolling, please disable SSL for the test build, and make sure that is all set for a test build too.

**Comment by SpenserJ** [comment]
:-1:

**Comment by Prior99** [comment]
:-1:

**Comment by Prior99** [comment]
This is lame and useless:
 * 80% of the code of conversation.js will no longer be reached as the bot reacts different when spoken to directly
 * No more cybersextalks with the bot
 * The bot can easily be muted, so why?

**Comment by OLef1air** [comment]
:-1:

**Pull request closed without merging**
