### PR TITLE
Gulp with jsdoc + jshint, integrated with travis

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 623da51ed6d91b987dd700c3c9ec0cfb827c86bc

**Comment by CptnBrittish** [comment]
:+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: Not a fan of trailing commas personally, but I think this would be a useful addition. We should set it up to run as a watch task later, and maybe run some complexity and function length checks to ensure everything is written cleanly and concisely

**Comment by korczis** [comment]
@SpenserJ I can help with setting up gulp for running the server, watching changes, livereload, etc

**Comment by SpenserJ** [comment]
@korczis When we get to the point that we're running webpages through proper templates, I'll drop in some libsass compilation and source-mapping too

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTY0NjA3Mg"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (100%) 
:-1:: 0 (0%)

**Pull request merged**
