### PR TITLE
IRC Logs for proof that the anythingbot concept is a viable

### PR DESCRIPTION
**Pull request by dbpokorny**
I'm sure there is plenty of mildly embarrassing material here, but all of this is outweighed, in my mind, by the following concern: we should at least remember what worked right on this project so that we can accentuate the positive (and minimize the negative). A project with a pure algorithmic development law works...because this model has been proven to work! There are missing pieces...think of the anythingbot as a prototype engine that ripped itself apart due to excessive forces...I hope that someone who studies software development projects can use this as raw materials for a proper post-mortem and enlighten future generations of anythingbot-like developers as to the path forward.

::crosses fingers::

The logs are incomplete; if anyone has access to the complete logs, those would be preferred.

Period of time represented: April 11-17, 2015

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 8c8a3200d7f676d14bf8832798afe60dd65b3575

**Comment by dos1** [comment]
I should have complete (or almost complete) logs from my bouncher, will check later :+1:

**Comment by SpenserJ** [comment]
Here are the logs from my bouncer between April 13 to May 12 (today):
https://docs.google.com/uc?id=0BxqHmgugY1fMLTdJZGZQZlcxQzA&export=download

I'll leave that file up until you (@dbpokorny) have time to merge it with your logs and reroll this.

**Comment by samis** [comment]
:+1: 
Perhaps we should relaunch an AnythingBot v2.0 with a more language-neutral architecture perhaps?

**Pull request closed without merging**
