### PR TITLE
Added very basic theme support

### PR DESCRIPTION
**Pull request by OLef1air**
This adds theme support, which is currently very rudimentary, but can be extended later. 
The MLP theme is still the standard theme.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 27658433a514c1f5137215c3e73ca2a086e18d05

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by timweightman** [comment]
:+1: Does look good, thanks for this!

**Comment by dbpokorny** [comment]
:+1:

**Comment by vifino** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### &lt;a target=&quot;_blank&quot; href=&quot;http:&#x2F;&#x2F;thecatapi.com&#x2F;?id=do5&quot;&gt;&lt;img src=&quot;http:&#x2F;&#x2F;24.media.tumblr.com&#x2F;tumblr_m4gl6e2zxU1qzrmrmo1_500.jpg&quot;&gt;&lt;&#x2F;a&gt;
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (100%)
:-1:: 0 (0%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
