### PR TITLE
Add a link to the current votes.

### PR DESCRIPTION
**Pull request by shalecraig**
per #274

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 6b16163ecc897194a3974358579101e88a881a49

**Comment by SpenserJ** [comment]
Hey @shalecraig, thanks for the PR. You missed the boat by just a few minutes though. #278 does the same thing.

**Comment by shalecraig** [comment]
:angry: :fist: :-1:

**Comment by SpenserJ** [comment]
@shalecraig You should pop onto IRC, and push another PR :grinning:

**Pull request closed without merging**
