### PR TITLE
Removed port from display text

### PR DESCRIPTION
**Pull request by mappum**
This is a small PR to test webhooks.

### CODE REVIEW

**Comment by avdg** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 032b48090b1fdfd2a71af88f8dcb9ef95651e3c5

**Comment by korczis** [comment]
So is the server accessible at port 3000 or not?

**Comment by AlphaT3ch** [comment]
@korczis Yes it is available on port 3000! :+1:

**Pull request closed without merging**
