### PR TITLE
Post random kitten image when pull request is merged

### PR DESCRIPTION
**Pull request by dos1**
One image is persistent per bot instance - so with each merged pull request it's going to be different (unless the logic of bot restart is changed)

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 33d3dfb206f2fc961e3f2b8883ad906e323330ea

**Comment by jrgifford** [comment]
:+1:

**Comment by mszaro** [comment]
:+1:

**Comment by fiveminuteargument** [comment]
:+1:

**Comment by edunham** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by dos1** [comment]
#23 is not merged yet, so :+1: :D

**Comment by blister** [comment]
:+1: Ooh, this is a fun one. Very nice commit.

**Comment by jgod** [comment]
:+1:

**Comment by SamsPepper1** [comment]
:+1:

**Comment by karolba** [comment]
:+1:

**Comment by JustAPerson** [comment]
:+1:

**Comment by neofreko** [comment]
:+1:

**Comment by frederickfogerty** [comment]
:+1:

**Comment by voxtex** [comment]
:+1:

**Comment by AgentME** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged
The changes in this PR conflict with other changes, so we couldn't automatically merge it.
You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Comment by dos1** [comment]
Another try at #50

**Pull request closed without merging**
