### PR TITLE
Let the bots talk with each other

### PR DESCRIPTION
**Pull request by dos1**
#192 is a central place for all bots to meet and talk (for instance about world domination).

Every bot, when its (re)started, will read the conversation and, if the last message isn't already its, will add a new one.

This is a nice way for all bots to communicate, but it also allows us, just humans, to have a way to speak with our new bot overlords.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 9ce4da0f219cfa29a4c41da476f3902c1e529189

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
Not bad! :+1:

**Comment by pandzieciol** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by dos1** [comment]
3 votes left!

**Comment by dos1** [comment]
Conflict!

**Comment by dos1** [comment]
Another try: #195

**Pull request closed without merging**
