### PR TITLE
Remove superfluous parts of package.json

### PR DESCRIPTION
**Pull request by jamescostian**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* dd201783e64c16b325f6691395898cd2deb0862b

**Comment by stevencorona** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by jimtla** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by lol768** [comment]
:+1:

**Comment by fcoury** [comment]
:+1:

**Comment by geoelectric** [comment]
:+1:

**Comment by lseelenbinder** [comment]
:+1:

**Comment by lambtron** [comment]
:+1:

**Comment by lanemt** [comment]
:+1:

**Comment by hatboysam** [comment]
:-1:

**Comment by georgebashi** [comment]
:+1:

**Comment by clay-to-n** [comment]
:+1:

**Comment by dhruska** [comment]
:+1:

**Comment by edwardhotchkiss** [comment]
:+1:

**Comment by shalstvedt** [comment]
:+1:

**Comment by DavidTPate** [comment]
:+1:

**Comment by christianbundy** [comment]
:+1:

**Comment by generalhenry** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by pjschlic** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
