### PR TITLE
Change the changelog

### PR DESCRIPTION
**Pull request by dos1**
That's what changelogs are for!

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 18d6ea9ef2a661ead63bfeece92e587a7d9dd7bd

**Comment by mwerner** [comment]
:+1:

**Comment by avdg** [comment]
:-)

**Comment by devn** [comment]
:+1:

**Comment by SpenserJ** [comment]
I don't think this change in the changelog accurately describes what is changing in the changelog.
:-1:

**Comment by jvt** [comment]
:+1: I support this change to the changelog

**Comment by Petah** [comment]
:+1:

**Comment by VeoPVM** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTYwMDA1Mw"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (85.7%) 
:-1:: 1 (14.2%)

**Pull request merged**
