### PR TITLE
Remove PR from website/votes when pull request is closed

### PR DESCRIPTION
**Pull request by SamsPepper1**
Delete PR from votesPerPR on event 'github.pullrequest.closed'

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 48cbad3ed49e64d6650b345f78602781061fdf14

**Comment by SpenserJ** [comment]
:+1:

**Comment by thesbros** [comment]
:+1:

**Comment by Phitherek** [comment]
:+1:

**Comment by dbpokorny** [comment]
:-1: Please don't delete the data in votesPerPR and either (A) filter into votesPerActivePR or else (B) find some way to allow another page to display stats on old votes.

**Comment by korczis** [comment]
I agree with @dbpokorny but I am for merging this in now and refactoring later because every voting round takes ages :)

:+1:

**Comment by samis** [comment]
:+1:

**Comment by SpenserJ** [comment]
@dbpokorny We need to write a function to load stats on old votes, as this only tracks votes since the bot started.

**Comment by SpenserJ** [comment]
@Phitherek Your vote won't count unless you star the repo.

**Comment by Stary2001** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=1q5"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (87.5%) 
:-1:: 1 (12.5%)

**Comment by SamsPepper1** [comment]
@dbpokorny at the moment votesPerPR was only used for the web service, and I think that this is a sensible quick fix. We need to refactor (and probably include a db) for more sensible long term tracking of whats going onregarding PR's.

**Pull request merged**
