### PR TITLE
Fixing issues with original voting.js length check

### PR DESCRIPTION
**Pull request by SpenserJ**
The original version of the voting.js length comparison had some bugs that caused the bot to crash any time it checked a PR. I've rewritten the code to fix those issues, and switched from FileReader (which doesn't support URLs) to Request.

Issues that have been fixed.
* FileReader relies on `fs.readFile` which cannot read from URLs.
* Code is written in a synchronous flow, but relies on asynchronous callbacks to set variables.
* Compares the PR owner's master branch, which may not be the branch the PR is trying to merge.

### CODE REVIEW

**Comment by avdg** [comment]
:+1: (in the worst case though we have to revert everything)

**Comment by botwillacceptanything** [comment]
Emergency fix merge.

**Comment by AlphaT3ch** [comment]
:+1: This better actually work

**Comment by roby65** [comment]
:+1: Thanks for the fix! Good work @botwillacceptanything

**Pull request merged**
