### PR TITLE
Folder structure - folder for data/src + travis CI + badge

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by korczis** [comment]
For Travis CI see - https://travis-ci.org/korczis/botwillacceptanything

As I am not owner of this repo, I can not setup Travis CI under its account.

Anyway :+1:

**Comment by dos1** [comment]
:+1:
through looks like it might have a conflict with #128 if it gets merged earlier

**Comment by avdg** [comment]
We probably don't want to expose the github api token...

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 5cd7245d262f2017c5c39cfa2ffd4848e0b77b8d

**Comment by korczis** [comment]
@avdg Credentials does not needs to be exposed, see this - http://docs.travis-ci.com/user/environment-variables/#Secure-Variables

We are using encrypted variables in our production projects so no worries ...

**Comment by korczis** [comment]
@dos1 #128 should not be hard to merge with this

**Comment by SpenserJ** [comment]
Awesome! Now we can really start refactoring into a cleaner directory structure and testing it. :+1:

**Comment by dos1** [comment]
Sure it won't be hard, but the point is - if it won't be able to happen automatically, another vote will be needed.

**Comment by avdg** [comment]
:+1: I guess it will be ok

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Pull request closed without merging**
