### PR TITLE
Fix wrong emoji in voting.js

### PR DESCRIPTION
**Pull request by rdancer**
Fix wrong emoji name introduced in 8eaa3c (it was late).

### CODE REVIEW

**Comment by rdancer** [comment]
:+1:  It really was late, sorry, folkd!

**Comment by mappum** [comment]
:+1: FYI the same change is in #101

**Comment by botwillacceptanything** [comment]
#### :ballotbox: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* e86b661f201b1fca9b27aa3dff96e62127fd5f3a

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by AlphaT3ch** [comment]
:-1: I already added that [here](https://github.com/botwillacceptanything/botwillacceptanything/pull/101)

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by roby65** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by rdancer** [comment]
Vote for #101  instead

**Pull request closed without merging**
