### PR TITLE
Add SSL to Website Idea (Easy Setup)

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Requires @mappum to update the name servers on the domain name.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 35167da3c7073b3c8262e722f1efe2dd79b6de0b

**Comment by SpenserJ** [comment]
I love the idea, but I'm not sure where @mappum is at these days. If we get a free certificate from RapidSSL, I can install it on the server though. I'll try to find some time in the next few days. :+1:

**Comment by Prior99** [comment]
:-1: Who needs security? People should trust each other!

**Comment by OLef1air** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
@Prior99: That doesn't really make any sense in my mind...

**Comment by AlphaT3ch** [comment]
@SpenserJ: Cool, and if worst comes worst, we can just use a self-generated one that shows an  certificate error

**Comment by RyanMilb** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=e06"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (85.7%)
:-1:: 1 (14.2%)

These following 2 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls


- :monkey: @anythingbot

Be sure to :star:star the repository if you want to have your say!

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Pull request closed without merging**
