### PR TITLE
Remove Clippy

### PR DESCRIPTION
**Pull request by FangedTerror802**
Revert of #338 and #343

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* fde773b44f57cb07a82a75df8ac62bdc6a2f2bc1

**Comment by timweightman** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by dos1** [comment]
:-1:

**Comment by FangedTerror802** [comment]
clippy is a stupid pic we dont need!!!!!!!!!

**Comment by pandzieciol** [comment]
:-1:

**Comment by synth3tk** [comment]
Are you kidding me?! :-1:

**Comment by timweightman** [comment]
Honestly I'd really like to see our page seem more bot-like. Currently it's all rainbows, and bots just don't understand that kind of beauty.

**Comment by SpenserJ** [comment]
:+1: I agree. This isn't a website for us to look at, its a website for the bot.

**Comment by CptnBrittish** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 5 (62.5%) 
:-1:: 3 (37.5%)

**Comment by korczis** [comment]
Can we try to reopen this?

**Comment by synth3tk** [comment]
You can try. Success, however, is optional.

**Pull request closed without merging**
