### PR TITLE
When starting, consider one's existence

### PR DESCRIPTION
**Pull request by mwerner**
Let's get a start on this right away.

### CODE REVIEW

**Comment by dos1** [comment]
:+1:

**Comment by PTaylour** [comment]
:+1:

**Comment by cgag** [comment]
:+1:

**Comment by voxtex** [comment]
:+1:

**Comment by frederickfogerty** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
