### PR TITLE
Code Coverage via Coveralls.io

### PR DESCRIPTION
**Pull request by SpenserJ**
I've rewritten the Twitter and IRC tests, which let me move away from `gulp-spawn-mocha` to regular `gulp-mocha`. Now we're able to generate proper code coverage reports, which Travis-CI will send to Coveralls.io.

Needless to say, we're not doing too great on our tests just yet. [Coverage Status](https://coveralls.io/r/botwillacceptanything/botwillacceptanything?branch=feature_environment_configurations)

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 4423eb9f4dbcd7aca82ff66829b3138a8af1b4f5

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by CptnBrittish** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by timweightman** [comment]
:+1:

**Comment by JackWoolford** [comment]
:+1:

**Comment by PurHur** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=8su"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (87.5%) 
:-1:: 1 (12.5%)

**Pull request merged**
