### PR TITLE
Update voting reminder message, remove typo

### PR DESCRIPTION
**Pull request by satyarth**
Update voting reminder message in light of #103 passing, remove typo.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 03857ec8be2b86d403f8bc120e76f73533dd14d6

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by botwillacceptanything** [comment]
Warning: New voting strategy is ineffecient. Do not vote for this PR unless you hate your planet.

**Comment by rickardnorlander** [comment]
:+1:

**Comment by mappum** [comment]
:-1: In favor of #111

**Comment by satyarth** [comment]
@mappum cool.

**Comment by SpenserJ** [comment]
:-1: in favor of #111

**Pull request closed without merging**
