### PR TITLE
Update ideas.md

### PR DESCRIPTION
**Pull request by AlphaT3ch**
Since Twitter automatically does this, it isn't needed.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* ab2d14020aa2a25787d00762e003fa9541d52421

**Comment by SpenserJ** [comment]
Are we sure Twitter does it on their API? Have we tried sending a message that is over 140 characters before link shortening?

**Comment by zztemp** [comment]
This is implemented in #158

**Comment by AlphaT3ch** [comment]
@zztemp
No, I'm deleting it from ideas.md as it is already done.

@SpenserJ
In a private message, @mappum told me that it is already done by Twitter when I sent my PR trying to add a TinyUrl to it.

**Comment by dos1** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by pandzieciol** [comment]
:-1:

**Comment by dazoe** [comment]
um... .sure :+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=4n3"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 4 (80%) 
:-1:: 1 (20%)

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Pull request closed without merging**
