### PR TITLE
adds protected paths; any PR to these will be auto-rejected

### PR DESCRIPTION
**Pull request by kballenegger**
This is pretty rough, and right now there are no paths protected yet… but it should work as an implementation of self-protection.

### CODE REVIEW

**Comment by jvt** [comment]
Does changing a protected file require two separate pull requests (one to change protected.js and one to change the previously protected file) or will the bot allow both changes to be in a single PR?

**Comment by kballenegger** [comment]
It'd require two separate pull requests.

I was also playing with the idea of setting a one-time `protected-forever.js` which is itself protected, and protects the protection mechanism; that way at some point a stable core could be safe forever[1].

Kind of reminds me of [Isaac Asimov's third law of robotics.](https://en.wikipedia.org/wiki/Three_Laws_of_Robotics).

**Comment by mgberlin** [comment]
I think this is contrary to the spirit of the project and nothing should be protected. :-1:

**Comment by drocta** [comment]
Maybe instead it could just require a higher/stricted vote threshold if any of the protected files are modified?
Like, say, a 3/4 majority?

I do not like the idea of protected-forever.js .

**Comment by SpenserJ** [comment]
:-1: Also agree that nothing should be protected. Having a higher vote majority seems like a good balance between stability and spirit.

**Comment by souravzzz** [comment]
:-1:

**Comment by rntz** [comment]
:-1:

**Comment by nitrix** [comment]
:-1:

**Comment by drusepth** [comment]
:-1:

**Comment by hintss** [comment]
:-1:

**Comment by peterpacz1** [comment]
image

**Comment by AlphaT3ch** [comment]
:-1: Someone will protect the protection code so nobody will be able to un-protect or protect anything.

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 4767d349c1d84b4b9bdde8fd4354a1d4b9e0c33a

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed.

----
**Tallies:**
:+1:: 0 (0%) 
:-1:: 8 (100%)

**Pull request closed without merging**
