### PR TITLE
Updated ideas

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 39af4ff0e31cb4b1f2b95f675f3782ded87ed0b5

**Comment by dos1** [comment]
Updated ideas are the best ideas. :+1:

**Comment by aristidb** [comment]
Maybe replace with GH issues?

**Comment by SamsPepper1** [comment]
:+1:

**Comment by avdg** [comment]
gh issues may be a better place to go in dept, simple ideas might go into ideas.md?

**Comment by AlphaT3ch** [comment]
:+1: Cool checklist!

**Comment by avdg** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 39af4ff0e31cb4b1f2b95f675f3782ded87ed0b5

**Comment by SpenserJ** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 39af4ff0e31cb4b1f2b95f675f3782ded87ed0b5

**Comment by pandzieciol** [comment]
:+1:

**Comment by jgod** [comment]
:+1:

**Comment by clay-to-n** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=d5l"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 9 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=d5l"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 9 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=d5l"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 9 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=d5l"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 9 (100%) 
:-1:: 0 (0%)

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=d5l"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 9 (100%) 
:-1:: 0 (0%)

**Pull request merged**
