### PR TITLE
Configure whether negative greetings will be used, with config.evil flag.

### PR DESCRIPTION
**Pull request by timweightman**
If config.evil === true, then anyone with a score < 3 will receive an evil greeting.

The rest of communicator.js is just me fixing javascript linting errors... there were a lot of them.

My text editor also went and adjusted the whitespace as well.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 8d2c08a2934254c6de54f9b0b92a27194a6d88b3

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by dbpokorny** [comment]
:-1: look at your diff, it is too big because you changed indentation

**Comment by zobier** [comment]
+1 whitespace diffs are evil, though the change looks fine with ?w=1

**Comment by SpenserJ** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by JackWoolford** [comment]
:+1:

**Comment by shalecraig** [comment]
:+1:

**Comment by PurHur** [comment]
:+1:

**Comment by Prior99** [comment]
:-: this is no longer needed when new conversationsystem is integrated! Good idea, otherwise.

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=7a4"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

These users aren't stargazers, so their votes were not counted: 
 * @zobier

**Pull request merged**
