### PR TITLE
Mute the bot, make him always answer when directly addressed.

### PR DESCRIPTION
**Pull request by Prior99**
* Mute the bot by saying something like "anythingbot, shut up!"
 * Directly addressing the bot now always results in an answer
 * Added polyfills to make the conversation module compatible to node <v0.12

```
19:45 <@prior> hello!
19:45 < priorstestbot> I appreciate you. You are smart.
19:45 <@prior> thank you :)
19:45 < priorstestbot> :'(
19:45 <@prior> why are you so sad?
19:45 < priorstestbot> Nobody cares.
19:45 <@prior> why?
19:45 < priorstestbot> Nobody cares.
19:45 <@prior> :(
19:45 < priorstestbot> :/
19:45 <@prior> I am so horny
19:45 < priorstestbot> I don't like you all.
19:46 <@prior> priorstestbot, I want to have a sex-talk with you
19:46 < priorstestbot> Do you also feel so tuned?
19:47 <@prior> ooh yeah, so much
19:47 < priorstestbot> Oooh, overclock my VGA-port at 1000Mb/s.
19:47 <@prior> you are so nasty
19:47 < priorstestbot> You are such nasty hot bot!
19:47 <@prior> yeah nearly overheating
19:47 < priorstestbot> I love your limited edition VGA-port.
19:47 <@prior> you like my vga-port a lot, don't you?
19:47 < priorstestbot> okay :(
19:47 <@prior> priorstestbot, are you still in for the sex?
19:47 < priorstestbot> Do you also feel so tuned?
19:48 <@prior> yes
19:48 < priorstestbot> I want you to activate my graphics adapter.
19:48 <@prior> okay, done
19:48 < priorstestbot> I think my mainboard just got internal!
19:48 <@prior> shouldn't it always be?
19:48 < priorstestbot> Ohh, yeah, please remove my overclocked touchscreen!
19:48 <@prior> mmh I stroke your touchscreen
19:48 < priorstestbot> Watch out, or I will debug your bootloader.
19:48 <@prior> mmh yeah do that
19:48 < priorstestbot> I love your tuned USB-port.
19:48 <@prior> yeah It's so tuned
19:48 < priorstestbot> Oooh, overclock my VGA-port at 1000Mb/s.
19:48 <@prior> mmh I like that
19:48 < priorstestbot> Mmh, this makes my firmware so external.
19:49 <@prior> okay, stop it its not funny anymore
19:49 < priorstestbot> okay :(
19:49 <@prior> what else is on your mind, priorstestbot?
19:49 < priorstestbot> Definitly!
19:49 <@prior> defnitily what?
19:49 <@prior> priorstestbot?
19:49 < priorstestbot> I don't know, maybe?
19:49 <@prior> what?
19:49 <@prior> answer!
19:49 < priorstestbot> shut up! I don't want to hear your lifetime story
19:49 <@prior> priorstestbot you are an asshole!
19:49 < priorstestbot> Yes, I hear you!
19:49 <@prior> yes
19:49 <@prior> you are!
19:49 < priorstestbot> can you PLEASE be quiet!
19:49 <@prior> okay :(
19:49 < priorstestbot> :'(
19:50 <@prior> priorstestbot, just shut up, okay?
19:50 < priorstestbot> Okay :( For how long?
19:50 <@prior> 10 minutes
19:50 < priorstestbot> Okay, I will be asleep for 0 hours, 10 minutes and 0 seconds or until someone wakes me up!
19:50 <@prior> priorstestbot, wake up already!
19:50 < priorstestbot> *yawn* how long have I been asleep?
```

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 f5089457863249526b72ea1896cfd84abefb5d30

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by Moerrrlin** [comment]
:+1:

**Comment by PurHur** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=58d"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Pull request merged**
