### PR TITLE
Give our benevolent dictator for life extra power.

### PR DESCRIPTION
**Pull request by sparky222b**
Our benevolent-dictator-for-life @mappum has shown he deserves to be the project's steward; give his votes 5X the impact to allow him to influence the direction of the project in a more effectual way.

### CODE REVIEW

**Comment by sparky222b** [comment]
:+1:

**Comment by clay-to-n** [comment]
:+1: Down with democracy! One supreme ruler is more efficient.

**Comment by dbpokorny** [comment]
:+1: yes, the gears of democracy need to be greased after all

**Comment by sparky222b** [comment]
My intent here was basically that it's _mostly_ democracy, but if mappum needs to jump in, being the project owner after all, he should have a bit more of a say than the rest of us rabble in the project direction.

I almost nominated myself, but I didn't think I'd win. :laughing:

**Comment by rdbell** [comment]
:-1:

**Comment by Gaelan** [comment]
Ehhh, I like democracy. :-1:.

**Comment by AlphaT3ch** [comment]
I'm with @Gaelan on this one... :-1:

**Comment by fiveminuteargument** [comment]
I think @mappum should get a nominally more powerful vote, definitely not x5. So either x2, or something *really* nominal like x1.1 :-) :-1:

**Comment by aristidb** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 7ed5ca7931ae643624830ed7354275e0a0622a9f

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 3 (37.5%) 
:-1:: 5 (62.5%)

**Pull request closed without merging**
