### PR TITLE
Spice up the webpages a little V3

### PR DESCRIPTION
**Pull request by rickardnorlander**
Same as the old versions, but applied to the new location.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 693b3b0004ec585496d6284302c7eb9469ce0898

**Comment by thenightwassave** [comment]
:+1:

**Comment by korczis** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by zztemp** [comment]
:+1: Eventually we will have to get a template engine so we don't have to make the pages one liners. :smile:

**Comment by dos1** [comment]
still spicy :+1:

**Comment by korczis** [comment]
@zztemp I can help with templates and routes, but it seems our bot stopped merging for some reason.

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTY3MDQ3Mw"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (100%) 
:-1:: 0 (0%)

**Pull request merged**
