### PR TITLE
Reduce minimum time for voting to 15m (from 30m)

### PR DESCRIPTION
**Pull request by SpenserJ**
We're doing enough frequent changes that I feel the minimum voting period should be reduced. This still requires that five votes are made, but will help improve the functionality much easier.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* d98884483655d1bdf923392a592baf4e19d24986

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by korczis** [comment]
:+1:

**Comment by avdg** [comment]
:-1: Potential safety hazard, sorry :/

**Comment by dos1** [comment]
:-1:, but I'd support it if you increase the minimal number of votes as well

**Comment by korczis** [comment]
@avdg This project in general is safety hazard maybe even more ...

**Comment by SpenserJ** [comment]
@dos1 What would you prefer to see the minimum votes increased to?

**Comment by dos1** [comment]
Maybe 8 - it's a nice power of 2 :3

**Comment by Petah** [comment]
:+1:

**Comment by korczis** [comment]
So 8 in 15 minutes or 5 in 30 ;-) ?

**Comment by SpenserJ** [comment]
Would be 8 in a minimum of 15 minutes, but it could still take an hour to reach the minimum votes. Right now we're reaching 5 votes in around 10 minutes on most PRs, and this one is already at 5 (not counting the bot)  in 6 minutes.

**Comment by dos1** [comment]
8 in 15 minutes. If you don't get 8 votes in 15 minutes, bot waits until the eight vote. I'd support that, as it seems too easy to get 5 votes now (you can get one from bot and one from PR author, so in some cases you just need 3 strangers)

**Comment by SpenserJ** [comment]
Bot vote doesn't count towards the minimum, just towards the majority percentage.

This has made me realize that there is no code to check a PR after the minimum time has passed. With webhooks on, it may be up to 30m after the final minimum vote was added, until it checks the PR again.

**Comment by mappum** [comment]
@SpenserJ We can just set the secondary polling to something like 10m.

**Comment by dos1** [comment]
I'm pretty sure bot vote counts towards the minimum. It's in the result of tallyVotes, which is used to count the votes.

**Comment by dazoe** [comment]
:-1:
I'd support if the min vote count was increased to something much better... say 15

**Comment by mappum** [comment]
I think 15 minutes won't give people a chance to see and vote on PRs. :-1:

**Comment by SpenserJ** [comment]
@dos1 Right you are. I thought that code was being skipped by the bot for some reason.

**Comment by thmas** [comment]
:-1:

**Comment by avdg** [comment]
I can go agree with the more votes, less time tradeoff. Just pls don't use this with buggy code where we will find the bug at minute 16 ;-)

**Comment by scottwarren** [comment]
:+1:

**Comment by dos1** [comment]
See #169 - :+1:

**Comment by SpenserJ** [comment]
3/6 split now that @dos1 added the minimum 8 votes. We were at 8 votes 15m in, which seems fairly reasonable for such a high interest PR.

**Comment by avdg** [comment]
Wish I could delay the merge :p

**Comment by dos1** [comment]
Maybe not commenting on this PR will delay it due to lack of webhook that deals with that minimal time?

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 6 (60%) 
:-1:: 4 (40%)

**Comment by dos1** [comment]
hehe whoops :)

**Pull request closed without merging**
