### PR TITLE
Reduce minimum time for voting to 15m (from 30m)

### PR DESCRIPTION
**Pull request by SpenserJ**
Reroll of #168 now that we have a higher minimum vote count. Seemed like most of us agreed that 8 over 15 was just as safe as 5 over 30.

We're doing enough frequent changes that I feel the minimum voting period should be reduced. This still requires that eight votes are made, but will help improve the functionality much easier.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 023a04a3ae027f7bf9a4e33c7f176524f4bf7a97

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by samis** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by drsirmrpresidentfathercharles** [comment]
:+1:

**Comment by dos1** [comment]
And the last vote goes to...

**Comment by SpenserJ** [comment]
:+1: Maybe there's a bug that lets me double-vote? :stuck_out_tongue_closed_eyes:

**Comment by pandzieciol** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=36l"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Comment by AlphaT3ch** [comment]
WHAT KIND OF CAT IS THAT?!?!??!

**Comment by SpenserJ** [comment]
@AlphaT3ch Its the "Death of BotWillAcceptAnything" cat

**Pull request merged**
