### PR TITLE
Auto-label pull requests 'Voting Underway', 'Merged' or 'Rejected'

### PR DESCRIPTION
**Pull request by timweightman**
This relies heavily on webhooks, currently.

As a first-pass, this will work only on future pull requests.

The next logical steps stemming from this PR would be:
- Refactor to make the add / remove labels code simpler and more maintainable
- Add in a 'cleanup' job:
 - Get all pull requests that are not labelled, or are labelled as 'Voting Underway'
 - Determine the true status of the pull request
 - Fix the label to match the status of the pull request

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* c5fd883fef51ac0ec5429166ef7d5c127b60da42

**Comment by SamsPepper1** [comment]
:+1:

**Comment by sarciszewski** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by SpenserJ** [comment]
Looks really good @timweightman! The only concern I have is the very first run turning into a race condition. It may try to flag a PR as Voting Underway, while it is still creating the label on the repo. If you look at `lib/integrations/irc.js`, it returns a promise that is resolved when we have connected to the channel. You could do something similar with resolving the promise when we know the labels are there.

:+1: even without that though!

**Comment by matter123** [comment]
:+1:

**Comment by dequis** [comment]
:+1:

**Comment by dequis** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=MTg1ODAwMg"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

**Pull request merged**
