### PR TITLE
Start a library for online community managers

### PR DESCRIPTION
**Pull request by dbpokorny**
http://en.wikipedia.org/wiki/Online_community_manager

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 81db37dea49e2a6be680eea9504639488bd98cd4

**Comment by shalecraig** [comment]
:-1: no, I don't think we should just start collecting pdfs.

**Comment by korczis** [comment]
:-1:

**Comment by samis** [comment]
:-1: Text maybe, a bot could easily read that. But not a PDF.

**Comment by OLef1air** [comment]
:-1:

**Comment by Stary2001** [comment]
:-1:

**Comment by avdg** [comment]
:+1: For the effort though I'm sure the vote won't pass. It's still an interesting read for those who don't want to see the world to die ;-)

**Comment by Prior99** [comment]
Why? :-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.


----
**Tallies:**
:+1:: 2 (25%)
:-1:: 6 (75%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Comment by dbpokorny** [comment]
tbh I was hoping that the whole "it is easier to find the answer to a question on the internet by giving the wrong answer than by asking the question" thing would just work. What wisdom would you impart on those who would attempt to build an online community with the anythingbot?

**Pull request closed without merging**
