### PR TITLE
Create ability for secure secret storage

### PR DESCRIPTION
**Pull request by mwerner**
It's not ideal for secrets to be committed in code like [this](https://github.com/botwillacceptanything/botwillacceptanything/blob/master/twitter.js#L4-L7)

This creates a yaml file with any arbitrary value assigned to any arbitrary key. If there is no `secrets.yml` file, it creates one.

Then to get your secret value in the file just hit the endpoint with a query param:

    http://localhost:3000/secrets?foo=bar

creates:

    foo: bar

Then we can rewrite the twitter client to consume the `Vault` class:

```javascript
var Vault = require('./lib/vault');
Vault.read();
var secrets = Vault.secrets;

var client = new Twitter({
  consumer_key: secrets['twitter_consumer_key'],
  consumer_secret: secrets['twitter_consumer_secret'],
  access_token_key: secrets['twitter_access_token_key'],
  access_token_secret: secrets['twitter_access_token_secret']
});
```
Which I'll leave for someone else.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 16a9091e6fc4aa868a6234a38635dc23033bd234

**Comment by rspeer** [comment]
:-1: A GET request shouldn't alter data.

**Comment by thenightwassave** [comment]
What is to stop just anyone from updating a hardcoded key?

**Comment by avdg** [comment]
hmm.. if the client still has a unlock phrase... we can have the server store the hash of it and then compare? (so the vault only opens for certain keys with the given phrase)

Some quick pseudo code:

``` javascript
var keys = {};
var clients = {
    'foo': {
        'hash': 'blahsha1hash',
        'keys': ['a', 'b', 'c']
    }
}
```

**Comment by mwerner** [comment]
We can put in a check to prevent overwriting existing keys if we find its necessary.

**Comment by avdg** [comment]
Ofc.. a hash with a salt as security policy rules goes ;-)

**Comment by thenightwassave** [comment]
How about to overwrite a key you need its old value.

**Comment by avdg** [comment]
For a complete api:

1) Can check if value is set
2) Can read value if permission given
3) Can soft write
4) Can hard write (using force) if permission given

**Comment by avdg** [comment]
We don't need all I guess?

**Comment by mwerner** [comment]
I think that'd be nice to have a fully fleshed out API, but i think i'd prefer an incremental change

**Comment by avdg** [comment]
:+1: For secret leaking secret storage with potential due to incremental change

**Comment by dos1** [comment]
merge conflicts :+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=c7r"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 4 (80%) 
:-1:: 1 (20%)

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged

The changes in this PR conflict with other changes, so we couldn't automatically merge it. You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Pull request closed without merging**
