### PR TITLE
Voting Refactor and Multiple Repository Support

### PR DESCRIPTION
**Pull request by SpenserJ**
This is a huge refactor of the voting module, that splits it into three pieces:
* Voting Logic and event handler
* Vote Counter
* Voting Templates

It also adds in support for the bot managing voting on multiple repositories, which paves the way to split the UI into a separate repository, or add any related but non-core functionality into a separate repository if we wish.

Voting config has been moved into the configs, and can be overridden on a per-repository basis (UI could require 10 votes, instead of 8 if we wanted).

All tests should be passing, and I've run through as much of the functionality as is possible to ensure nothing is broken, but I'd appreciate some extra testruns just to be safe.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 486c6e875da43a6d3cb241a7afef5c7495c4a55d

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by timweightman** [comment]
:+1:

**Comment by Prior99** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
OOOOhhhhh, cool! :+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=c8v"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (100%)
:-1:: 0 (0%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
