### PR TITLE
Add minecraft :smile:

### PR DESCRIPTION
**Pull request by zztemp**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* a4528bbbb74f15df0e08d3e0b970422527ad2a34

**Comment by SpenserJ** [comment]
:-1: Minecraft is fun and all, but this bot has enough on its plate already!

**Comment by RyanMilb** [comment]
:-1:

**Comment by dos1** [comment]
woah woah woah :-1:

**Comment by mappum** [comment]
Lol, maybe one day when the server has more resources. :-1:

**Comment by zztemp** [comment]
I can lower the java memory size.

**Comment by VeoPVM** [comment]
:-1:

**Comment by korczis** [comment]
:-1:

**Comment by mappum** [comment]
You know what, I'll upvote it. :+1:

**Comment by zztemp** [comment]
@mappum Yeah!

**Comment by dos1** [comment]
woah woah woah :+1:

**Comment by rspeer** [comment]
I rather doubt that the process lifetime has been thought through. :-1:

**Comment by AlphaT3ch** [comment]
:-1: Too much, too fast

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed. Why don't you try some ideas that don't suck next time, you incredible git?

----
**Tallies:**
:+1:: 3 (33.3%) 
:-1:: 6 (66.6%)

**Pull request closed without merging**
