### PR TITLE
Add a scary favicon

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 43fa24d49391a99a2a878e61ac480edae6767167

**Comment by avdg** [comment]
:+1:

**Comment by aristidb** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by RiderSx** [comment]
:+1:

**Comment by rspeer** [comment]
Do we know that `__dirname` is going to point to the correct directory when this code is run? That's easily the kind of thing that can pass your local tests while failing in production.

**Comment by msoedov** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by albertorestifo** [comment]
:+1:

**Comment by rspeer** [comment]
:-1: Might break the server.

A current open bug, expressjs/serve-favicon#27, says "This module is a bit rigid at the moment in that it blows up right away if it isn't given a path to an existent favicon file." There is no indication that `__dirname` will be the correct path and I don't think anyone has actually reviewed this.

**Comment by avdg** [comment]
*wonders how bad the breakage is*

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=cgq"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (85.7%) 
:-1:: 1 (14.2%)

These users aren't stargazers, so their votes were not counted: 
 * @RiderSx

**Pull request merged**
