### PR TITLE
English grammar; and remove a redundant assignment in #16.

### PR DESCRIPTION
**Pull request by Quuxplusone**
No intended functional change.

### CODE REVIEW

**Comment by Quuxplusone** [comment]
:+1:

**Comment by fiveminuteargument** [comment]
:+1:

**Comment by jgod** [comment]
:+1:

**Comment by jbwyme** [comment]
:+1:

**Comment by mszaro** [comment]
:+1:

**Comment by alex-hofsteede** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by bradleybuda** [comment]
:+1:

**Comment by frederickfogerty** [comment]
:+1:

**Comment by vitorarins** [comment]
:+1:

**Comment by rdancer** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged
The changes in this PR conflict with other changes, so we couldn't automatically merge it.
You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Comment by rdancer** [comment]
:-1: The extra assignment helps readability

**Pull request closed without merging**
