### PR TITLE
Distinguish between votes and monkeys!

### PR DESCRIPTION
**Pull request by timweightman**
- Votes that contain monkeys :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil: will be ignored.
- Votes cast by non-stargazers will have a message added to them, with instructions about how to have their vote counted.
- Vote ended message is now a mustache template, rather than concatenated js.
- This pull request also includes my refactoring of the github integration scripts to use promises for auto-labeller, etc.
Let the voting begin!

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 643431a2d738c0841f4286ad53482edceb54096f

**Comment by PurHur** [comment]
:-1: I like apes

**Comment by Lambdac0re** [comment]
:-1: keep the monkeys maaaaaan

**Comment by bertrand-caron** [comment]
:+1: This is no monkey business !

**Comment by timweightman** [comment]
So harsh you guys!

**Comment by Prior99** [comment]
:+1:

**Comment by dos1** [comment]
Hmm. I like these changes, but it's a lot of unrelated to each other stuff in this one PR. Voting :-1: for now, but if you'd split this PR to several ones, I'd probably vote yes for each of them!

**Comment by SpenserJ** [comment]
:-1: Split it into multiple PRs and I'll reconsider

**Comment by plor** [comment]
:-1: I like the idea, but the tests fail

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 3 (37.5%) 
:-1:: 5 (62.5%)

**Pull request closed without merging**
