### PR TITLE
Self-testing stub

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* ed0fa0e4f46bdf39e68803275426ab20d8e1f4bc

**Comment by drocta** [comment]
Why does this replace "return restart()" with just "restart()" (in addition to the other changes)
restart doesn't seem to have a return value currently, so maybe the difference doesn't do anything?
If the change from "return restart()" to "restart()" doesn't break anything, I am in favor.

**Comment by rickardnorlander** [comment]
Restart calls process.exit(0), so the return was just confusing.

**Comment by drocta** [comment]
Ok, thanks :+1: .

**Comment by rspeer** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by jish** [comment]
:+1:

**Comment by jedahan** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=a3g"></a>
:+1: The vote passed, this PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (100%) 
:-1:: 0 (0%)

**Pull request closed without merging**
