### PR TITLE
Change license

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 052f10838354210183f96cdabdcf912b9317273d

**Comment by rickardnorlander** [comment]
:+1:

**Comment by edwardhotchkiss** [comment]
:+1:  Yes.

**Comment by thenightwassave** [comment]
:+1:

**Comment by shalstvedt** [comment]
:-1:

**Comment by mappum** [comment]
:-1:

**Comment by DavidTPate** [comment]
:+1:

**Comment by mostlygeek** [comment]
:-1:

**Comment by parhamr** [comment]
:+1:

**Comment by volker48** [comment]
:-1:

**Comment by jahqueel** [comment]
:-1:

**Comment by dos1** [comment]
:-1:

**Comment by bewuethr** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

**Pull request closed without merging**
