### PR TITLE
Create CHANGELOG.md

### PR DESCRIPTION
**Pull request by korczis**
Added CHANGELOG.md

### CODE REVIEW

**Comment by kjnsn** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by napstr** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by rmetzler** [comment]
:+1:

Who updates the changelog? the bot or the comitter?

**Comment by avdg** [comment]
I'm sure that we have to do it, it would be fun I guess

**Comment by skeetmtp** [comment]
:+1:

**Comment by Promichel** [comment]
:+1:

**Comment by christopherdebeer** [comment]
:+1:

**Comment by devn** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by devn** [comment]
:+1:

**Comment by nathankleyn** [comment]
:+1:

**Comment by didimitrie** [comment]
:+1:

**Comment by krasnoukhov** [comment]
:+1:

**Comment by Lewn** [comment]
:+1:

**Comment by rjgonza** [comment]
:+1:

**Comment by cyhsutw** [comment]
:+1:

**Comment by hillerstorm** [comment]
:+1:

**Comment by aerobless** [comment]
:+1:

**Comment by hfinger** [comment]
:+1:

**Comment by splix** [comment]
If human will update changelog file, then I guess it will be a problem to auto merge such pull requests, will be a lot of conflicts there

**Comment by avdg** [comment]
We need a new merge algorithm for text files

**Comment by splix** [comment]
Maybe it's possible to configure git merge for this file. Just found this: http://stackoverflow.com/questions/11841127/strategy-for-git-and-append-mostly-files

**Comment by roby65** [comment]
The bot should automatically get the PR name and if it successfull merges, it should update the changelog with the PR name. That would be awesome.

**Comment by esiqveland** [comment]
:+1:

**Comment by ellisvalentiner** [comment]
:+1:

**Comment by ijks** [comment]
:+1:

**Comment by JacobEdelman** [comment]
:+1:

**Comment by korczis** [comment]
I have to say that I did not expected so many :+1:  ;-)

**Comment by r04r** [comment]
:-1: We already have the git log. This file will fall out of date and/or be deceptive.

**Comment by korczis** [comment]
Btw, what about idea that the bot will update changelog.

How? 

We can use some special comment in git commit

```
This is some commit messge.

This is body of commit message.

#changelog: Added feature XY <---- This will be included in CHANGELOG.md
 
```

**Comment by dos1** [comment]
Who cares! every project needs an outdated changelog file! :+1:

**Comment by RyanMilb** [comment]
:-1:

**Comment by JWesorick** [comment]
:+1:

**Comment by ChristoSilvia** [comment]
:+1:

**Comment by rpignolet** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballotbox: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and dow-votes are disregarded.
Pull request is not counted as a vote, so vote for (or against) your own PRs!
A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* cad57959d3783ed3c00a1728c99e4cb55692b0ee

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=72h"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 22 (91.6%) 
:-1:: 2 (8.3%)

These users aren't stargazers, so their votes were not counted: 
 * @skeetmtp
 * @nathankleyn
 * @Lewn
 * @ellisvalentiner
 * @korczis
 * @korczis

**Comment by rmetzler** [comment]
haha @korczis vote for his own pr didn't even count. But it seems like there is a bug, counting him twice.

**Comment by dos1** [comment]
It's just in detection of non-stargazers. His vote would count just once otherwise ;)

**Pull request merged**
