### PR TITLE
Changed voting parameters

### PR DESCRIPTION
**Pull request by mappum**
Require 15 votes for a PR to pass or fail

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* f0b4e3718f3a2de9841291ce88baa91c869e073f

**Comment by mappum** [comment]
:+1:

**Comment by tsujigiri** [comment]
:+1:

**Comment by jusio** [comment]
:+1:

**Comment by sacooper** [comment]
(:+1)

**Comment by bojanstef** [comment]
:+1:

**Comment by xolan** [comment]
:+1:

**Comment by treytt** [comment]
+1

**Comment by jamescostian** [comment]
:-1:

**Comment by Acconut** [comment]
:-1:

**Comment by PxlBuzzard** [comment]
:-1:

**Comment by wrl** [comment]
:-1:

**Comment by jamchamb** [comment]
:+1:

**Comment by mappum** [comment]
Lots of downvotes, harsh :(

**Comment by jamescostian** [comment]
lol

**Comment by jvt** [comment]
:-1:

**Comment by Benaiah** [comment]
:-1:

**Comment by fastest963** [comment]
:-1:

**Comment by stevencorona** [comment]
:-1:

**Comment by lseelenbinder** [comment]
+1

**Comment by TerryDEV** [comment]
:+1:

**Comment by pixelcort** [comment]
:-1:

**Comment by adrianpike** [comment]
:-1:

**Comment by jimtla** [comment]
:-1:

**Comment by mappum** [comment]
The most important part of this PR is lowering `PERIOD`, we can move much faster if that is lower.

**Comment by samtstern** [comment]
:+1:

**Comment by cgag** [comment]
:-1:

**Comment by cgag** [comment]
:-1:

**Comment by geoelectric** [comment]
:+1:

**Comment by parhamr** [comment]
:-1:

**Comment by erasmospunk** [comment]
:-1:

**Comment by Techwraith** [comment]
:+1:

**Comment by vjdhama** [comment]
:+1:

**Comment by dariocravero** [comment]
:+1:

**Comment by TkTech** [comment]
:-1:

**Comment by dhruska** [comment]
:+1:

**Comment by mouse-reeve** [comment]
:-1:

**Comment by clay-to-n** [comment]
:-1:

**Comment by Azdle** [comment]
:+1:

**Comment by reportingsjr** [comment]
:+1:

**Comment by ralston** [comment]
:+1:

**Comment by kamaln7** [comment]
:+1:

**Comment by shalstvedt** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

----
**Tallies:**
:+1:: 13 (48.1%) 
:-1:: 14 (51.8%)

**Pull request closed without merging**
