### PR TITLE
Add a donations wallet

### PR DESCRIPTION
**Pull request by ChristoSilvia**
If we add a wallet to recieve bitcoin donations, the bot could potentially buy its own hosting.  Then it would be truly autonomous.  It may even be able to reproduce by binary fission, forking itself and splitting up the bitcoins (which represent lifespan) equally amongst the children

### CODE REVIEW

**Comment by rdancer** [comment]
:-1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by drocta** [comment]
:+1: (maybe donations/bounties?)

**Comment by dlmccoy** [comment]
:+1:

**Comment by erasmospunk** [comment]
:+1:

**Comment by souravzzz** [comment]
:+1:

**Comment by bhickey** [comment]
:-1: Prove that only the bot can access funds.

**Comment by jedahan** [comment]
:+1:

**Comment by rickardnorlander** [comment]
@bhickey good point

**Comment by sethherr** [comment]
:-1: seconding @bhickey

**Comment by hintss** [comment]
:+1:

**Comment by drocta** [comment]
@bhickey and @sethherr Well, the private key would be generated by the bot, and then stored in a file outside the repository. A reasonable assumption is that only those with the private key can access the funds. The person who owns the computer the bot is running on, and the bot, would presumably be the only two entities with access to the file with the private key in it. Given that the bot is running on the person whose computer runs the bot 's computer, the bot basically has to trust that person, because they have root on its existence, and anything it can do they can do.

So short of creating a p2p network with a multisig address or computation on shared secrets, one generally has to trust the bot computer owner with whatever security the bot is meant to have.

The only other real threat to keeping the key private would be changing the bot to output it in some way.
But this is also something that can't really be helped short of making a canneverbechanged.js file which is used to access the bitcoin wallet, but which cannot actually give up the secret key.

So, generally, if its set up right it should be as secure as anything in the bot can be!

And in any case this change is just to ideas.md

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 0d2524a45876e76eb078bb055f74cf31ee10d645

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=a3g"></a>
:+1: The vote passed, this PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (88.8%) 
:-1:: 1 (11.1%)

These users aren't stargazers, so their votes were not counted: 
 * @dlmccoy
 * @bhickey

**Pull request merged**
