### PR TITLE
Move jsdoc

### PR DESCRIPTION
**Pull request by korczis**
Now the generated doc is reachable via /doc/index.html

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 26f747840ce8dc6efb173c61aaca3d5b738b7e00

**Comment by avdg** [comment]
:+1:

**Comment by karolba** [comment]
:+1:
But why are you commiting adding and deleting test.md in your PRs?

**Comment by dbpokorny** [comment]
:+1:

**Comment by LifeMushroom** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: We'll need to add something to the restart process that triggers gulp for the docs.

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by dos1** [comment]
I'd vote up if this PR contained just the test.md commits. It does something productive though, so it sucks! :-1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=1nl"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (87.5%) 
:-1:: 1 (12.5%)

**Pull request merged**
