### PR TITLE
Cleanup problems listed in CodeClimate

### PR DESCRIPTION
**Pull request by SpenserJ**
Nothing major, just a simple cleanup of some of the errors in https://codeclimate.com/github/botwillacceptanything/botwillacceptanything/code?sort=smell_count&sort_direction=desc

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 211d96b73c25f9ac10a7de0263d918ef0ff6ec2c

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by mappum** [comment]
Maybe we should standardize the code style with this: https://github.com/feross/standard

**Comment by dos1** [comment]
:+1:

**Comment by dequis** [comment]
:+1:

**Comment by SpenserJ** [comment]
@mappum Seems like an interesting solution, but I don't necessarily agree with their choice of no semicolons. I'd rather have a standard that we call vote on, and then we use that across the board.

**Comment by SpenserJ** [comment]
[fixmyjs](https://github.com/jshint/fixmyjs) from JSHint might be a good solution. The legacy CLI command will read in the .jshintrc, and apply those changes automatically. We could always add it to the Gulpfile and use the modern programmatic functionality as well.

**Comment by dos1** [comment]
js "code style" advising lack of semicolons? ughhhrbrrrrr...

**Comment by avdg** [comment]
:+1:

**Comment by SamsPepper1** [comment]
:+1: 

I accept this for the time being, but It would be nice if we had a full discussion to decide on a standard.

Personally, I'm happy to do away with semicolons

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=1d7"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 7 (87.5%) 
:-1:: 1 (12.5%)

**Comment by avdg** [comment]
I guess the linter with the most users will win. Since code can be packages and can be centralized by github or npm, its easier to track how popular they are, even though there might always be disagrees on the standards.

(Too much trust in tools will result in flamewars on the internet somewhere some day, at least based on my experience)

**Pull request merged**
