### PR TITLE
Spice up the webpages a little

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **30** minutes (plus/minus **20** percent, to avoid people timing their votes), and at least **5** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* b70435e3bdd4aa906a3fe5a1bb5ee2b3add2e23c

**Comment by zztemp** [comment]
:+1:

**Comment by dos1** [comment]
ooooooh, spicy! :+1:

**Comment by mappum** [comment]
:+1:

**Comment by VeoPVM** [comment]
:+1:

**Comment by RyanMilb** [comment]
:+1:

**Comment by rspeer** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1: In a later PR, we should spin up some actual templates for the bot to render all pages through.

**Comment by avdg** [comment]
:+1:

**Pull request closed without merging**
