### PR TITLE
Added Procfile to repository root

### PR DESCRIPTION
**Pull request by samis**
This adds a simple Procfile to the root of the repository, allowing the tool 'foreman' to be used to stop/start the bot. Aside from providing prettier console output, it will make it easier to manage the bot if it ever becomes multi-process (e.g a Redis server or a component written in another language)

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 6394b921c3acc927ef0031b2d2a183a5aeb75725

**Comment by shalecraig** [comment]
:+1:

**Comment by SpenserJ** [comment]
Is there a node process manager that we can use instead of depending on Ruby?

**Comment by samis** [comment]
Just found one. https://github.com/strongloop/node-foreman.
I'll test it now.

**Comment by samis** [comment]
....damm. 'If your processes exit, Node Foreman will assume an error has ocurred and shut your application down.'

**Comment by samis** [comment]
Just tested it. node-foreman does indeed start the bot successfully. The problem of the entire app terminating when a process exits will need to be dealt with however.

**Comment by RyanCopley** [comment]
:-1:

**Comment by RyanCopley** [comment]
:+1:

**Comment by SpenserJ** [comment]
Does it only assume it was bad if process.exit() returned a non-zero error code? We can just return 0 whenever we want to restart

**Comment by samis** [comment]
Hmm. Let me see if I can look at the code and see.

**Comment by samis** [comment]
Apparently not. See:
https://github.com/strongloop/node-foreman/blob/master/lib/proc.js#L44

**Comment by SpenserJ** [comment]
What if we moved some logic into `launcher.js`, and keep that process running. When main wants to restart, it pings the launcher, the launcher gracefully closes the process (so that the DB disconnects and such), and then restarts the process. If `launcher.js` receives an exit command, it can trigger the same graceful shutdown on `main.js`

**Comment by samis** [comment]
so essentially, make launcher.js the supervisor of main.js and launch that from the Procfile instead?

**Comment by SpenserJ** [comment]
Yes, but I don't know whether we even need the Procfile or Foreman at that point. `launcher.js` would provide stop/start functionality at that point. I don't know what else Foreman adds, but it could be useful for launching other processes, like you mentioned.

**Comment by samis** [comment]
You have a fair point. However, were we to add something requiring an additional  (I'm going to use Redis as an example as I plan to add Redis support shortly) it'd be easier to add an additional line in the Procfile rather than ensure the service is started manually or by the system's init daemon. That would apply mostly to development but also has effects on production.

**Comment by SpenserJ** [comment]
Sounds like a good setup then. `launcher.js` controls start/stop functionality for `main.js`, and Node Foreman handles the procfile for `launcher.js` and redis

**Comment by samis** [comment]
Should I close and reroll then?

**Comment by SpenserJ** [comment]
That'd be great. I'd say our new solution should hit all the points.

**Comment by dbpokorny** [comment]
Is the plan

(1) to have a /foreman http endpoint that lists foreman processes the bot has started, state of the processes (for example "show processlist" in mysql)

(2) allow the bot to start and stop services through irc? "anythingbot, start redis", "anythingbot stop mysql"

(3) start, restart, and stop services by PR

**Comment by samis** [comment]
@dbpokorny I hadn't thought of that. That would obviously require the reroll of this to be merged though. Some of those might be difficult though, depending on which implementation of foreman is used (I think they might have some differences)

**Comment by dbpokorny** [comment]
@samis I don't see what choice there is to make? https://www.npmjs.com/package/foreman

**Comment by samis** [comment]
@dbpokorny Good choice.  I'll go see which of your ideas might be difficult to use with that package.

**Comment by samis** [comment]
The 'restart' bit will require either using a fork, or for a pull request to get merged. also, that will either need a global install (requires root) or modifying the PATH to include the path to node-foreman. Additionally, listing processes is not inbuilt into node-foreman but could likely be achieved by parsing the output of node-foreman.
Does that make sense?

**Comment by dbpokorny** [comment]
@samis I'm not familiar with this, but I trust your judgement (like I have a choice lol :-)

**Comment by samis** [comment]
Fair enough. Closing now to reroll.

**Pull request closed without merging**
