### PR TITLE
Murdered autoplay and added the controls for the audio.

### PR DESCRIPTION
**Pull request by samis**
First pull request on Github, just so you know. 
This fixes the horrendous use of auto play on the website. As a side effect it also adds controls to stop, start and change the volume of the audio.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 4fd89f445c6e58972503f9d99d339a50167de9e4

**Comment by botwillacceptanything** [comment]
:-1:

**Comment by vifino** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by Dieyousay** [comment]
:-1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by Stary2001** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=4tv"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 6 (75%) 
:-1:: 2 (25%)

These users aren't stargazers, so their votes were not counted: 
 * @coveralls

**Comment by shalecraig** [comment]
Hey @samis!

Welcome to @botwillacceptanything on GitHub, and thanks for submitting your first pull-request!

While some people in the community may disagree with you on this change, it's only really one step away from being reality.

:+1:

**Comment by shalecraig** [comment]
Congrats on having your first pull-request merged. The bot's restarted yourself - go check out the site. Autoplay's now turned off by default.

Hope you become a continuous committer!

**Pull request merged**
