### PR TITLE
Document supermajority behavior

### PR DESCRIPTION
**Pull request by sparky222b**

### CODE REVIEW

**Comment by sparky222b** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

That comment right above is getting outdated.

**Comment by rntz** [comment]
:+1:

**Comment by andrewnicols** [comment]
+1

**Comment by mszaro** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 96087198ff485f50f7bf33b78bae069faba6302c

**Comment by dos1** [comment]
:+1:

**Comment by OLef1air** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by rdancer** [comment]
:-1:  Your documentation says that `>=` is required, but the code says `>` ;-)

**Comment by thmas** [comment]
:-1: rdancer's right.

**Comment by wpapper** [comment]
:+1:

**Comment by erasmospunk** [comment]
:+1:

**Comment by jgod** [comment]
:+1:

**Comment by yiransheng** [comment]
:+1:

**Comment by chrismeller** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by rspeer** [comment]
:-1: While fixing it, might as well fix it accurately.

**Comment by chrismeller** [comment]
@rspeer How is this inaccurate?

**Comment by drusepth** [comment]
:+1: Can't wait for this to be accepted so I can PR `var REQUIRED_SUPERMAJORITY = 0.0;`

**Comment by sparky222b** [comment]
Seems like the bot died. No PR merges have happened for a while.

**Comment by sparky222b** [comment]
Haha Andrew. 65 percent is in there already. Would be tough to get that PR
approved.

**Comment by rdancer** [comment]
It's either rate limits on Github's part, or the vote analysis code being broken by one of the yesterday's patches. Not dead.

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=buf"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 14 (87.5%) 
:-1:: 2 (12.5%)

These users aren't stargazers, so their votes were not counted: 
 * @sparky222b
 * @andrewnicols
 * @sparky222b
 * @sparky222b

**Pull request merged**
