### PR TITLE
eww...brains

### PR DESCRIPTION
**Pull request by dbpokorny**
Brains for the bot (not integrated yet, this is just an example REPL for the query driver loop of SICP chapter 4 http://en.wikipedia.org/wiki/Structure_and_Interpretation_of_Computer_Programs). Example:

$ node scheme.js
? (can-do-job ?x ?y)
(can-do-job (administration secretary) (administration big wheel))
(can-do-job (computer programmer) (computer programmer trainee))
(can-do-job (computer wizard) (computer technician))
(can-do-job (computer wizard) (computer programmer))

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 119e8a9224595d80b92572676cd0d954dc95d736

**Comment by SpenserJ** [comment]
Not entirely sure of how it works, so I can't comment on that, but I would ask that you reroll to include config.js instead of config.loader.js. The loader is temporary until we feel that enough people have run the bot locally to switch over entirely to config.js as the loader

:+1: otherwise

**Comment by shalecraig** [comment]
:+1: this could be interesting

**Comment by PurHur** [comment]
:-1: This isnt done at all

**Comment by Prior99** [comment]
:-1: please use new configsystem

**Comment by dos1** [comment]
MOAR SCHEME :+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 119e8a9224595d80b92572676cd0d954dc95d736

**Comment by dbpokorny** [comment]
:+1:

**Comment by samis** [comment]
Don't know scheme, but this looks good. Plus it adds more language variety. :+1:

**Comment by OLef1air** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 5 (62.5%) 
:-1:: 3 (37.5%)

**Comment by samis** [comment]
:(

**Pull request closed without merging**
