### PR TITLE
Added some ideas.

### PR DESCRIPTION
**Pull request by shalecraig**
The bot would like these to happen, so it improves more quickly.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* cc3070e2cf3c73773bfabf659330bf8b2756af25

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by timweightman** [comment]
:+1:

**Comment by dbpokorny** [comment]
:+1:

**Comment by PurHur** [comment]
:-1:

**Comment by Prior99** [comment]
:-1:

**Comment by dos1** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 cc3070e2cf3c73773bfabf659330bf8b2756af25

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by Prior99** [comment]
Can we please:

 a) keep the ideas in the issue-tracker and tag them as "idea" so there is a platform for discussion
 b) Keep each idea in a seperate PR
 c) Give the PRs useful titles, not only "Added some ideas", "Fixed stuff", etc.
 d) Why would the bot change the channels title to the vote-status!? How is that supposed to work?

**Comment by OLef1air** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 5 (62.5%) 
:-1:: 3 (37.5%)

**Pull request closed without merging**
