### PR TITLE
Amend bot's existence to '42'. Modify voting emoticons to something more appropriate.

### PR DESCRIPTION
**Pull request by fallenby**
This bot's consideration of its own existence shall be changed from 'undefined' to '42' to better match with the existing Pratchettian definition of the Meaning of Life.

With this, the current voting emoticons are too nice. We need to change that, and Doom Guy is always good motivation for getting things done.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 0ae283011491ed213e841bdfe245384ca2f5132b

**Comment by fallenby** [comment]
Does this bot check whether or not I am the owner of the PR before letting me vote?

:+1:

**Comment by dazoe** [comment]
:-1:

**Comment by AlphaT3ch** [comment]
:-1: Too un-official

**Comment by mappum** [comment]
I don't like the removal of the thumb emojis. :-1:

**Comment by rspeer** [comment]
:-1:

**Comment by RutZap** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed. This PR will now be closed.

----
**Tallies:**
:+1:: 0 (0%) 
:-1:: 5 (100%)

These users aren't stargazers, so their votes were not counted: 
 * @fallenby

**Pull request closed without merging**
