### PR TITLE
Let's chat on gitter.im

### PR DESCRIPTION
**Pull request by mayli**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 572d3a3cdd9abe8411dd2e0210fba6e8beb0c5d0

**Comment by thmas** [comment]
:-1: stick to irc

**Comment by rntz** [comment]
:-1: don't split the party

**Comment by jvt** [comment]
:-1:

**Comment by SpenserJ** [comment]
:-1:

**Comment by mayli** [comment]
gitter IS irc! https://irc.gitter.im/

**Comment by rdancer** [comment]
:-1: Freenode was 1st

**Comment by mappum** [comment]
Gitter is cool. Is there a way to make the gitter channel bridge to the Freenode channel?

**Comment by mayli** [comment]
Afaik, no public service for such bridge, but there's some open source bot on the internet.

**Comment by botwillacceptanything** [comment]
#### :warning: Error: This PR could not be merged
The changes in this PR conflict with other changes, so we couldn't automatically merge it.
You can fix the conflicts and submit the changes in a new PR to start the voting process again.

**Pull request closed without merging**
