### PR TITLE
Voting fix

### PR DESCRIPTION
**Pull request by korczis**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 95f14a154cb61dd316c1aa4865440a443fd7b99c

**Comment by mappum** [comment]
Why put the voting constants in the config if they aren't being loaded from there?

(It would be bad to load those constants from the config anyway, because then they aren't decided on by PRs, but by server admins).

**Comment by dos1** [comment]
:-1:

**Comment by Stary2001** [comment]
:-1:

**Comment by SpenserJ** [comment]
@mappum I think some of those constants should be decided by voting. We've decided to adjust the period and minimum votes by voting already.

@dos1, @Stary2001, Could you list why you don't like the PR? This is to work towards the voting file being cleaned up and separated out into multiple files.

**Comment by dos1** [comment]
config vars that shouldn't be there + amdefine + it has merge conflict anyway so who cares :v

**Comment by SpenserJ** [comment]
The plan was to move the config vars out initially, and just move voting for now. When its in the new location, we can clean up the rest of it. We're already using amdefine through the rest of the bot, so it makes sense to do the same here.

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Pull request closed without merging**
