### PR TITLE
Close pull requests that Github reports as unmergeable

### PR DESCRIPTION
**Pull request by jahqueel**

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 2a7e4f64ac1eece205960a400092ce02f0ce60b2

**Comment by shalecraig** [comment]
:+1:

**Comment by shalstvedt** [comment]
:+1:

**Comment by hamitron** [comment]
:+1:

**Comment by mappum** [comment]
This is already being done, but after the vote comes to a decision: https://github.com/botwillacceptanything/botwillacceptanything/blob/master/voting.js#L290-L294

:-1:

I think it is better to do it at the end, because the mergability can change due to other PRs being merged.

**Comment by clebrun** [comment]
agree with @mappum :-1:

**Comment by mostlygeek** [comment]
@mappum makes a good point :-1:

**Comment by erasmospunk** [comment]
:-1:

**Comment by mwerner** [comment]
:-1:

**Comment by kamaln7** [comment]
^ :-1:

**Comment by christianbundy** [comment]
Good point @mappum :-1:

**Comment by shalecraig** [comment]
Yeah, agreed :-1:

**Comment by volker48** [comment]
:-1:

**Comment by kyleterry** [comment]
no fun :-1:

**Comment by kidoman** [comment]
:-1:

**Comment by JWesorick** [comment]
:+1:

**Comment by thenightwassave** [comment]
:-1:

**Comment by ravinggenius** [comment]
:-1:

**Comment by botwillacceptanything** [comment]
#### :-1: The vote failed, this PR will now be closed

**Pull request closed without merging**
