### PR TITLE
WARNING: Bot is hitting the Github API rate limit

### PR DESCRIPTION
**Pull request by mappum**
The bot is in a state of emergency, it has reached Github's API rate limit and can't do anything.

**Please send a message to Github support telling them why we need the rate limit lifted for this account!**
https://github.com/contact?form%5Bsubject%5D=botwillacceptanything%20Rate%20Limiting

### CODE REVIEW

**Comment by bewuethr** [comment]
:+1:

**Comment by mappum** [comment]
:+1:

**Comment by gms8994** [comment]
:+1:

**Comment by thenightwassave** [comment]
:+1:

**Comment by felixhandte** [comment]
:+1:

**Comment by JWesorick** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:+1:

**Comment by RyanMilb** [comment]
(+1)

**Comment by dos1** [comment]
:1:

**Comment by nijotz** [comment]
:+1:

**Comment by dequis** [comment]
merge conflict lol. You can still fix it because the bot didn't comment, right?

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 05a99e77f8deae09d90a0f7c4e31f4866fb027f0

**Comment by dequis** [comment]
Well. Okay.

**Comment by MasterDurron** [comment]
:+1:

**Comment by rickardnorlander** [comment]
:-1:  This pull request contains merge conflicts that must be resolved.

**Comment by botwillacceptanything** [comment]
#### :warning: This PR has been modified and is now being closed.

To prevent people from sneaking in changes after votes have been made, pull requests can't be committed on after they have been opened. Feel free to open a new PR for the proposed changes to start another round of voting.

**Comment by lykkin** [comment]
:+1:

**Comment by Blecki** [comment]
This is why I lowered the interval.

**Comment by dequis** [comment]
You mean [here][1]? That made things worse by requiring more requests. Good job.

[1]: https://github.com/botwillacceptanything/botwillacceptanything/pull/6/files

**Comment by Blecki** [comment]
Yes exactly.

**Pull request closed without merging**
