### PR TITLE
Remove port number from README

### PR DESCRIPTION
**Pull request by dos1**
Now that we have nice nginx proxy we don't need to specify port 3000 everywhere.

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* 8c9c515d7a31e02711dd41e8c44d2b7abad01b17

**Comment by botwillacceptanything** [comment]
:+1:

**Comment by korczis** [comment]
:+1:

**Comment by avdg** [comment]
:+1:

**Comment by pandzieciol** [comment]
:+1:

**Comment by CptSpaceToaster** [comment]
:+1:

**Comment by dequis** [comment]
:+1:

**Comment by CoolOppo** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by SpenserJ** [comment]
It might be worth mentioning that a local instance is on port 3000. Doesn't come with port 80 working out of the box

:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=aov"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 8 (100%) 
:-1:: 0 (0%)

These users aren't stargazers, so their votes were not counted: 
 * @CptSpaceToaster
 * @CoolOppo

**Pull request merged**
