### PR TITLE
Status labels

### PR DESCRIPTION
**Pull request by fiveminuteargument**
Auto-label each PR 'winning'/'losing' after a vote

### CODE REVIEW

**Comment by AgentME** [comment]
:+1:

**Comment by thmas** [comment]
:+1:

**Comment by begizi** [comment]
:+1:

**Comment by rntz** [comment]
:+1:

**Comment by jvt** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* 574777305ef0d0f6e4f2b6f6837d8028b71e094d

**Comment by bradleybuda** [comment]
:+1:

**Comment by andrewnicols** [comment]
+1

**Comment by erasmospunk** [comment]
:+1:

**Comment by dos1** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### :+1: The vote passed, this PR will now be merged into master.

**Pull request merged**
