### PR TITLE
Install NPM packages before restarting

### PR DESCRIPTION
**Pull request by SpenserJ**
If an error occurs with the npm install, log the error and don't restart.

### CODE REVIEW

**Comment by SpenserJ** [comment]
:+1: No longer require a manual npm install before restarting the server

**Comment by mappum** [comment]
Shouldn't we take out the call to `restart` here: https://github.com/SpenserJ/botwillacceptanything/commit/6c1b5fea071033370b42e75ac43e6061ff2f6d3e#diff-7a9076d6d94e62c13d641aa71f19ae8eR28?

**Comment by SpenserJ** [comment]
@mappum Fixed that up. I think I'm done committing while watching TV

**Comment by mgberlin** [comment]
Will this end up in an infinite loop of installs if there is something significantly wrong with the npm install?

**Comment by SpenserJ** [comment]
@mgberlin No it will not, as the server will not restart. It will continue running as the current version, until another PR is merged, when it will try again. Obviously someone would need to monitor the server, but this could be added to a log page on a webserver.

**Comment by rickardnorlander** [comment]
:-1:  Does not address all invocations of restart(). Changes synchrone to asynchrone behaviour (thread problems?).

**Comment by SpenserJ** [comment]
@rickardnorlander Last instance of restart() is switched over. Good catch on that one. I don't think it will cause threading problems, as it should function the same as the restart() function does, with the latest commits. I'm open to other ideas though.

**Comment by rickardnorlander** [comment]
@SpenserJ My concern is that restart isn't called until the child process finishes. This means that npmInstall could return, which restart never could. If npmInstall returns, then the checkPR timer could trigger which could cause all kinds of issues I imagine. A clearInterval could prevent this I guess.

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

*NOTE: the PR will be closed if any new commits are added after:* b9608e64e1b35a34c8540d85590f204f6c64aa10

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting has begun.

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must star this repo for your vote to count.**

A decision will be made after this PR has been open for **30** minutes, and at least **5** votes have been made.

A supermajority of 65% is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* b9608e64e1b35a34c8540d85590f204f6c64aa10

**Comment by mappum** [comment]
:+1:

**Comment by CptnBrittish** [comment]
:+1:

**Comment by AlphaT3ch** [comment]
:+1:

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=t4"></a>
:+1: The vote passed! This PR will now be merged into master.

----
**Tallies:**
:+1:: 4 (80%) 
:-1:: 1 (20%)

**Pull request merged**
