### PR TITLE
UptimeRobot Integration?

### PR DESCRIPTION
**Pull request by AlphaT3ch**
UptimeRobot Integration? This PR complies with #425

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 0f1488146f48334d0786c2d052bfae6521270e98

**Comment by dbpokorny** [comment]
:+1:

**Comment by SpenserJ** [comment]
:+1:

**Comment by shalecraig** [comment]
:+1:, but that api key in the markdown though #lowstandards #yolo

**Comment by OLef1air** [comment]
:+1:

**Comment by shalecraig** [comment]
:+1:

**Comment by Prior99** [comment]
:-1: Stop using the ideas.md. Use the issuetracker, this way we have platform for discussion!

**Comment by johnku1** [comment]
:+1: 1

**Comment by botwillacceptanything** [comment]
#### <a target="_blank" href="http://thecatapi.com/?id=ds2"></a>
:+1: The vote passed! This PR will now be merged into master.


----
**Tallies:**
:+1:: 6 (85.7%)
:-1:: 1 (14.2%)

These following 1 voter(s) were not stargazers, so their votes were not counted:

- :monkey: @coveralls

Be sure to :star:star the repository if you want to have your say!

**Pull request merged**
