### PR TITLE
so which one of you is in charge around here?

### PR DESCRIPTION
**Pull request by dbpokorny**
I sent the password to root@anythingbot.org to @SpenserJ, this PR just makes it official...

### CODE REVIEW

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 62c9bee5cc7a74acf403101f12b144dd84323a2d

**Comment by Petah** [comment]
:-1:

**Comment by AlphaT3ch** [comment]
:-1:

**Comment by SpenserJ** [comment]
I'm fine with this, since we rarely hear from @mappum anymore :(

**Comment by dbpokorny** [comment]
@SpenserJ it looks like we're going to have to figure out some way to take the sysadmin out of the loop as much as possible...I think this means blowing up the configs, please see the the 8->7 PR.

**Comment by botwillacceptanything** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing :+1:`:+1:`, or :-1:`:-1:`.
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both :+1:up- and :-1:down-votes are disregarded.
Comments containing monkeys are disregarded. :monkey: :monkey_face: :see_no_evil: :hear_no_evil: :speak_no_evil:
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **7** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:*
 62c9bee5cc7a74acf403101f12b144dd84323a2d

**Comment by samis** [comment]
I for one welcome our new @SpenserJ overlord.
But yeah, we could do with taking out the sysadmin as much as possible.

**Comment by Prior99** [comment]
:-1:

**Pull request closed without merging**
